{
  "hash": "06740dbb13ba920aec57c1eadbb2d5e9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Leadership Transitions and Survival:\\n Coups, Autocoups, and Power Dynamics\"\n\nauthor:\n  - name: Zhu Qi\n    affiliations: University of Essex\n    email: qz21485@essex.ac.uk\n  \nformat:\n  aps-html: default\n  aps-pdf: \n    documentclass: report\n    keep-tex: true\n    colorlinks: true\n    urlcolor: blue\n    link-citations: true\n    linkcolor: blue\n    fig-asp: 0.618\n    number-sections: true\n    shift-heading-level-by: -1\n    toc: true\n    toc-title: Contents\n    lof: true\n    lot: true\n    crossref: \n      lof-title: Figures\n      lot-title: Tables\n    linestretch: 1.618\n    indent: true\n    fontsize: 12pt\n    mainfont: \"Times New Roman\"\n    sansfont: \"Arial\"\n    monofont: \"Courier New\"\n    #latex-engine: pdflatex\n    pdf-engine: xelatex\n    geometry:\n      # - showframe\n      - top = 3cm\n      - bottom = 3cm\n      - left = 3cm\n      - right = 2.7cm\n    header-includes:\n      - \\usepackage{sectsty}\n      - \\chapterfont{\\centering}\n      - \\usepackage{lscape}\n      - \\newcommand{\\blandscape}{\\begin{landscape}}\n      - \\newcommand{\\elandscape}{\\end{landscape}}\n      \n  docx: default\n    \ncategories: [Article, Coups, Autocoups, Leadership Survival]\nbibliography: references.bib\n#include-before-body: title.tex\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n\n## Acknowledgements {.unnumbered}\n\nThe completion of this thesis has been a significant journey, filled with hard\nwork, learning, and moments of joy. Throughout this time, I have received support\nand encouragement from many individuals, without whom this dissertation would not\nhave been possible.\n\nFirst and foremost, I would like to express my deepest gratitude to my great\nsupervisor, Professor Kristian Skrede Gleditsch, for his invaluable guidance,\nunwavering support, and insightful feedback throughout this journey. His\nexpertise and encouragement have been instrumental in shaping this dissertation.\nI would also like to extend my heartfelt thanks to the chair of my board panel,\nProfessor Han Dorussen, for his continuous support and constructive criticism,\nwhich have significantly enhanced the quality of my research.\n\nI am profoundly grateful for the comments, advice, and suggestions from several\nesteemed scholars who have contributed to this work. Dr. Brian J Phillips, Dr.\nPrabin Khadka, and Dr. Winnie Xia, their expertise and thoughtful input have been\ngreatly appreciated and have enriched this dissertation.\n\nFinally, I want to thank my family for their unwavering support and love. To my\nbeloved wife, Ji Zhi, who has been my rock throughout this journey, and to my\ndear daughter, Siyan, and son, Sisheng, who have been my source of joy and\nmotivation. I am deeply thankful to my father for his enduring support, and to\nthe memory of my late mother, whose love and guidance continue to inspire me.\n\nAll errors and faults are my own.\n\n## Abstract {.unnumbered}\n\nThis dissertation examines the dynamics of irregular power transitions,\nparticularly coups and autocoups, and their influence on leader survival. It\nhighlights the critical role of power dynamics, shaped by **regime type**, in\ndetermining coup success rates and attempt frequency. Utilizing a **double probit\nmodel with sample selection**, the study reveals that expected coup success\nsignificantly influences attempts, with military regimes facing a heightened\nvulnerability due to their power structure.\n\nWhile often understudied, autocoups are shown to have a substantial impact on\ndemocratic trends. This research introduces a refined definition of autocoups\nalongside a novel dataset encompassing events from 1945 to 2022, enabling a more\nrobust quantitative analysis.\n\nEmploying survival analysis, the study compares the longevity of leaders who rise\nto power through coups versus autocoups. The findings demonstrate that\ncoup-installed leaders face a significantly shorter tenure and higher risk of\nremoval. This contrasts with autocoup leaders who manipulate the system to extend\ntheir rule, suggesting the potential for autocoups to incentivize power grabs and\ncontribute to democratic backsliding.\n\nThis work contributes significantly to the political science literature by:\n\n-   Defining key concepts: It establishes a clear definition of autocoups, a\n    previously understudied phenomenon.\n\n-   Introducing a novel dataset: This dataset enables researchers to conduct more\n    comprehensive quantitative analyses of autocoups.\n\n-   Establishing a general framework: The framework provides a comparative\n    approach to studying the dynamics of irregular power transitions and their\n    impact on democratic stability.\n\n**keywords:** *Coups, Autocoups, Power transitions, Leadership Survival*\n\n## Introduction\n\n### Research question\n\n\n\n\n\nIrregular power transitions, marked by a disregard for constitutional procedures,\nare a critical area of study in political science. They not only disrupt\nestablished rules but often require unconstitutional tactics to secure power.\nFurthermore, these transitions can inspire copycat behaviour among other\nambitious leaders.\n\nDespite their central role in political science and the extensive research\nconducted on irregular power transitions, a long-standing question continues to\nintrigue political scientists: ***Why are some leaders ousted before their terms\nexpire, while others complete their full terms or even overstay beyond their\noriginally mandated limits?*** In other words, why do some leaders survive for\ndecades while others last for only years, months, or even days? This dissertation\nfocuses on this question and seeks to provide a comprehensive analysis, dedicated\nto understanding how leaders come to power through unconstitutional means and\nwhat factors determine the duration of a leader's rule following an irregular\nascent.\n\n### Analyses on coups and autocoups in a general framework\n\nWhen discussing irregular power transitions, the concepts that often come to mind\nare irregular entries or exits, such as coups, assassinations, rebellions,\nprotests, and foreign interventions. Among these methods, coups hold a prominent\nposition due to their frequent occurrence. According to the Archigos dataset\n[@goemans2009], from 1945 to 2015, there were approximately 145 instances of\nirregular leader exits, with coups[^1] accounting for more than half (79\nleaders). The often-cited Global Instances of Coups (GIC)[^2] dataset\n[@powell2011] records even more leaders (245 cases) removed by coups from 1950 to\n2023.\n\nGiven their prevalence and substantial influence on political systems, coups have\nbeen extensively studied, particularly since 2000 [@thyne2019]. Consequently, the\nconcept of a coup is comparatively clear and widely accepted in academic circles.\nMany scholars, including this study, follow the definition by @powell2011, which\ndescribes coups as \"illegal and overt attempts by the military or other elites\nwithin the state apparatus to unseat the sitting executive... \\[a coup is\nsuccessful\\] if the perpetrators seize and hold power for at least seven days\"\n(P. 252). Although debates persist, two elements are clear: first, the\nperpetrators are elites within the ruling group, and the victims of coups are\nincumbent executive leaders. Second, the strategy or aim of a coup involves\ncompletely removing the incumbents, not merely seizing part of their power or\nforcing them to concede on specific policies. Beyond defining coups, several\ndatasets have been developed for quantitative analyses, such as the Global\nInstances of Coups [@powell2011], the Cline Centre Coup d’État Project Dataset\n[@peyton2024], and the Colpus Dataset [@chin2021]. These datasets are\nwell-developed and frequently used in political science research.\n\nHowever, irregular power transitions are not limited to irregular entries and\nexits but should also include irregular \"overstays.\" Using illegal means to\noverthrow an incumbent leader before their term expires is undoubtedly an\nirregular power transition. Similarly, an incumbent using illegitimate means to\nextend their term beyond term limits is also an irregular power transition.\n\nAlthough academic attention to irregular retention of power has increased since\nthe 1990s, especially after Peru’s President Alberto Fujimori's self-coup in\n1992, it remains comparatively understudied and has several shortcomings. First,\nthere is no universally accepted terminology for this \"overstaying in power\" type\nof irregular power transition, unlike the clear term \"coup.\" Consequently,\nvarious terms such as self-coup, autogolpe, and executive coup are used by\ndifferent scholars. This dissertation will use 'autocoup' to refer to this type\nof irregular power transition, which will be thoroughly discussed in Chapter 3.\nSecond, there is no consensus on the definition of an autocoup. Existing\ndefinitions remain vague, often conflating power expansions and power\nextensions[^3]. For example, @cameron1998a defines an autogolpe as a temporary\nsuspension of the constitution and dissolution of Congress by the executive, who\nthen rules by decree. This definition focuses on power expansion instead of power\nextension, leading to conceptual confusion and misalignment with the definition\nof a classic coup. Third, a consensus autocoup dataset is lacking. While several\nrelated datasets exist, as discussed by @baturo2022 in coding their Incumbent\nTakeover dataset, the terminologies, definitions, and coverage years vary,\nlacking wide acknowledgement and extensive academic exploration. In summary,\nautocoup has not been analysed in a comparative manner connected with coups.\n\nAnalysing coups and autocoups separately is less problematic. However, from a\ncomprehensive framework perspective on irregular power transitions and leader\nsurvival, coups and autocoups should be, and can be, analysed within the same\nframework. Both coup and autocoup significantly influence democratic backsliding\nand are the most frequent means of irregular power transition. Furthermore, as\nboth are called \"coups,\" classic coups and autocoups are very similar since a\ncoup is launched to replace the current leader, while an autocoup is staged to\nreplace the future leader.\n\n### Academic Contributions\n\nThis study addresses a critical gap in the literature by offering a comprehensive\nframework for analysing both coups and autocoups, which are the most common forms\nof irregular power transitions. While existing research often examines these\ntopics separately with varying terminologies, definitions, methods, and datasets,\nthis dissertation integrates these elements to provide a unified perspective on\nirregular power transitions and leader survival.\n\nOur contributions are threefold:\n\n-   **Emphasis on power dynamics and regime types**: We highlight the significant\n    role of power dynamics, particularly the influence of regime types, in\n    determining the success and frequency of coup attempts. Our analysis\n    underscores how the expected chances of coup success motivate such attempts,\n    with military regimes being notably susceptible.\n\n-   **Refined definition and novel dataset for autocoups:** We introduce a\n    refined definition of autocoups and develop a novel dataset covering events\n    from 1945 to 2022. This enables a comparative analysis with classic coups,\n    providing clearer insights into the nature and impact of autocoups on\n    political systems.\n\n-   **Survival analysis of leaders from different entry modes:** By applying\n    survival analysis to existing coup data and our new autocoup dataset, we\n    demonstrate how different modes of entry into power significantly affect\n    leader survival. Our findings reveal that leaders who come to power through\n    coups typically have shorter tenures and face higher removal risks compared\n    to those who extend their rule through autocoups.\n\nOur analysis of irregular power transitions is particularly relevant to\nunderstanding democratic backsliding. These transitions violate democratic norms\nand disrupt the path towards stable democracy. Leaders who gain power through\nirregular means often employ undemocratic tactics, such as suppressing\nopposition, to consolidate their illegitimate hold on power. This creates a\nvicious cycle where the erosion of democratic institutions is both a cause and\nconsequence of efforts to maintain power.\n\n### Overview of the thesis\n\nThis study is structured into three main chapters beyond the introduction, each\naddressing key aspects of irregular power transitions and their implications for\npolitical stability and democratic processes.\n\n**Chapter 2** examines the determinants of classic coup attempts. While extensive\nresearch exists on coups, most studies focus on observable factors before coups,\nsuch as economic performance, political stability, previous coups, and\ncoup-proofing strategies. This chapter, however, emphasizes the less observable\nbut crucial factor of expected chances of coup success, which have been often\noverlooked. Utilizing the double probit model with sample selection, the analysis\nreveals that expected success rates significantly influence coup attempts. These\nsuccess rates are primarily shaped by the balance of power between incumbents and\nchallengers, which is largely determined by regime type. The findings indicate\nthat military regimes face a much higher risk of coups compared to dominant-party\nregimes.\n\n**Chapter 3** focuses on the concept of autocoups, specifically on power\nextensions by incumbent leaders. It distinguishes autocoups from broader concepts\nlike self-coups or executive coups by redefining them as instances where\nincumbent leaders refuse to transition power as mandated, thereby overstaying in\noffice. Based on this refined definition, a novel dataset of autocoup events from\n1945 to 2022 is introduced, encompassing 110 attempts and 87 successes. The\nchapter includes case studies and empirical analyses that demonstrate the utility\nof this dataset for quantitative research, providing a basis for empirical\nanalysis on autocoups.\n\n**Chapter 4** investigates how the method of power acquisition impacts the\nlongevity of leaders who come to power through coups versus those who extend\ntheir rule through autocoups. The hypothesis is that the method of accession\nsignificantly affects leader tenure. Using the Cox proportional hazards model and\na time-dependent Cox model, the chapter provides evidence of differing survival\ntimes between these two types of leaders. The results indicate that leaders who\ncome to power through coups face a significantly higher risk of removal compared\nto those who extend their rule through autocoups. This finding highlights the\nimplications for political stability and democratic processes, suggesting that\nthe relatively low cost and high returns of autocoups could incentivize\nincumbents to seize power in this manner, potentially leading to democratic\nbacksliding and the personalization of power.\n\nIn **Chapter 5**, the study concludes by summarizing the main findings,\ndiscussing policy implications, and acknowledging the limitations of the\nresearch. It also outlines directions for future research, emphasizing the need\nfor further exploration of irregular power transitions, particularly coups and\nautocoups.\n\n## Power Dynamics and Coup Attempts: A Selection Mechanism Analysis\n\n### Introduction\n\n\n::: {#tbl-coup_year_counts .cell layout-ncol=\"2\" tbl-cap='Coups by year and by country' tbl-subcap='[\"by year frequency\",\"by country frequency\"]'}\n\n```{.r .cell-code}\n#load coup data\n\ndownload.file(\"https://www.uky.edu/~clthyn2/coup_data/powell_thyne_coups_final.txt\", \"data/Coup.txt\")\nCoup <- fread(here(\"data/Coup.txt\"))\n\ncoups <- Coup |>\n  summarise(\n    `Coup attempted` = n(),\n    `Coup succeeded` = sum(coup == 2),\n    .by = country\n  )\n\nattempts <- length(Coup$country)\nsucceeded <- length(Coup$country[Coup$coup == 2])\n\nCoup |> \n  summarise(counts = n(),\n            .by = year) |> \n  arrange(desc(counts)) |> \n  head(15) |>\n  clean_names(case = \"title\") |> \n  gt() |> \n  tab_options(\n    table.width = pct(95),\n    column_labels.font.weight = \"bold\") |>\n  tab_source_note(source_note = md(\"***Source: GIC dataset***\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gbddxvqkpg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gbddxvqkpg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gbddxvqkpg thead, #gbddxvqkpg tbody, #gbddxvqkpg tfoot, #gbddxvqkpg tr, #gbddxvqkpg td, #gbddxvqkpg th {\n  border-style: none;\n}\n\n#gbddxvqkpg p {\n  margin: 0;\n  padding: 0;\n}\n\n#gbddxvqkpg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 95%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gbddxvqkpg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gbddxvqkpg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gbddxvqkpg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gbddxvqkpg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gbddxvqkpg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gbddxvqkpg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gbddxvqkpg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gbddxvqkpg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gbddxvqkpg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gbddxvqkpg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gbddxvqkpg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gbddxvqkpg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gbddxvqkpg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gbddxvqkpg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gbddxvqkpg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gbddxvqkpg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gbddxvqkpg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gbddxvqkpg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gbddxvqkpg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gbddxvqkpg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gbddxvqkpg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gbddxvqkpg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gbddxvqkpg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gbddxvqkpg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gbddxvqkpg .gt_left {\n  text-align: left;\n}\n\n#gbddxvqkpg .gt_center {\n  text-align: center;\n}\n\n#gbddxvqkpg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gbddxvqkpg .gt_font_normal {\n  font-weight: normal;\n}\n\n#gbddxvqkpg .gt_font_bold {\n  font-weight: bold;\n}\n\n#gbddxvqkpg .gt_font_italic {\n  font-style: italic;\n}\n\n#gbddxvqkpg .gt_super {\n  font-size: 65%;\n}\n\n#gbddxvqkpg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gbddxvqkpg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gbddxvqkpg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gbddxvqkpg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gbddxvqkpg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gbddxvqkpg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gbddxvqkpg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gbddxvqkpg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gbddxvqkpg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Year\">Year</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Counts\">Counts</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1966</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">18</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1963</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">16</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1975</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">16</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1965</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">15</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1991</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">14</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1962</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">14</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1960</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1978</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1981</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">11</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1961</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">11</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1958</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">11</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1976</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">11</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1989</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">10</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1972</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">10</td></tr>\n    <tr><td headers=\"Year\" class=\"gt_row gt_right\">1977</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">10</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"2\"><div data-qmd=\"***Source: GIC dataset***\"><div class='gt_from_md'><p><em><strong>Source: GIC dataset</strong></em></p>\n</div></div></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\nCoup |> \n  summarise(counts = n(),\n            .by = country) |> \n  arrange(desc(counts)) |> \n  head(15) |>\n  clean_names(case = \"title\") |> \n  gt() |> \n  cols_align(\n    align = \"right\",\n    columns = 2\n  ) |>\n  tab_options(\n    table.width = pct(95),\n    column_labels.font.weight = \"bold\") |>\n  tab_source_note(source_note = md(\"***Source: GIC dataset***\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"szgkbcdrtk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#szgkbcdrtk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#szgkbcdrtk thead, #szgkbcdrtk tbody, #szgkbcdrtk tfoot, #szgkbcdrtk tr, #szgkbcdrtk td, #szgkbcdrtk th {\n  border-style: none;\n}\n\n#szgkbcdrtk p {\n  margin: 0;\n  padding: 0;\n}\n\n#szgkbcdrtk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 95%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#szgkbcdrtk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#szgkbcdrtk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#szgkbcdrtk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#szgkbcdrtk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#szgkbcdrtk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#szgkbcdrtk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#szgkbcdrtk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#szgkbcdrtk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#szgkbcdrtk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#szgkbcdrtk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#szgkbcdrtk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#szgkbcdrtk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#szgkbcdrtk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#szgkbcdrtk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#szgkbcdrtk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#szgkbcdrtk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#szgkbcdrtk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#szgkbcdrtk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#szgkbcdrtk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#szgkbcdrtk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#szgkbcdrtk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#szgkbcdrtk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#szgkbcdrtk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#szgkbcdrtk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#szgkbcdrtk .gt_left {\n  text-align: left;\n}\n\n#szgkbcdrtk .gt_center {\n  text-align: center;\n}\n\n#szgkbcdrtk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#szgkbcdrtk .gt_font_normal {\n  font-weight: normal;\n}\n\n#szgkbcdrtk .gt_font_bold {\n  font-weight: bold;\n}\n\n#szgkbcdrtk .gt_font_italic {\n  font-style: italic;\n}\n\n#szgkbcdrtk .gt_super {\n  font-size: 65%;\n}\n\n#szgkbcdrtk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#szgkbcdrtk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#szgkbcdrtk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#szgkbcdrtk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#szgkbcdrtk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#szgkbcdrtk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#szgkbcdrtk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#szgkbcdrtk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#szgkbcdrtk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Country\">Country</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Counts\">Counts</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Bolivia</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">23</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Argentina</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">20</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Sudan</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">17</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Haiti</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">13</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Venezuela</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">13</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Iraq</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Syria</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Thailand</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Ecuador</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">11</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Burundi</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">11</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Guatemala</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">10</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Honduras</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">10</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Burkina Faso</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">10</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Sierra Leone</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">10</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Ghana</td>\n<td headers=\"Counts\" class=\"gt_row gt_right\">10</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"2\"><div data-qmd=\"***Source: GIC dataset***\"><div class='gt_from_md'><p><em><strong>Source: GIC dataset</strong></em></p>\n</div></div></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nCoups, defined as \"illegal and overt attempts by the military or other elites\nwithin the state apparatus to unseat the sitting executive\" [@powell2011, P.252],\noccur with varying frequency across countries, with some experiencing them more\noften than others. According to GIC dataset, Latin American countries such as\nBolivia witnessed 23 coups\nbetween 1950 and 1984, while Argentina experienced\n20 during a similar time\nframe. However, Mexico's authoritarian period from 1917 to 2000 saw no coups at\nall. In Africa, Sudan endured 17\ncoups between 1955 and 2023, whereas South Africa has not experienced any coup\nsince 1950. Similar patterns are observed in the Middle East and South Asia.\n\nThe varying frequency of coup attempts has captivated political scientists for\ndecades, leading to extensive research on the subject. As highlighted by\n@gassebner2016, despite approximately one hundred potential determinants of coups\nbeing suggested, no consensus has been reached. In an effort to address this\nissue, they have tested 66 factors proposed in previous literature using three\nmillion model permutations in an extreme bounds analysis (ibid.).\n\nExamining previous research, which has tested around 100 variables as potential\ndeterminants of coups, raises an important question beyond simply understanding\nwhy coups are more frequent in some countries than others. The critical question\nis: Can we establish a framework to help scholars focus on the most relevant\nfactors of coups, rather than sifting through over 100 variables without reaching\na consensus?\n\nReviewing previously proposed variables of coups, it is evident that all focus on\npre-coup conditions, with no consideration given to post-coup factors. This means\nmore attention is paid to factors observable before a coup, such as military\nforce or spending, economic performance, political stability, and previous coups.\n\n\n::: {#tbl-coups .cell tbl-cap='Top 10 countries with the most coup attempts'}\n\n```{.r .cell-code}\ncoups |>\n  # add one row which adds up the total\n  arrange(desc(`Coup attempted`)) |>\n  head(11) |> \n  add_row(\n    country = \"Total\",\n    `Coup attempted` = sum(coups[, 2]),\n    `Coup succeeded` = sum(coups[, 3])\n  ) |>\n  mutate(Success_rate = percent(`Coup succeeded` / `Coup attempted`, \n                                accuracy = 0.1\n                                )) |>   \n  clean_names(case = \"title\") |>\n  gt() |>\n  tab_options(\n    table.width = pct(90),\n    column_labels.font.weight = \"bold\",\n    table.layout = \"fixed\"\n              ) |> \n  # cols_width(1 ~ px(120),\n  #            2:4 ~ px(88)\n  # ) |>\n  cols_align(\n    align = \"center\",\n    columns = 2:3\n  ) |> \n  tab_source_note(source_note = md(\"*Source: GIC dataset*\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"khbtfdaimq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#khbtfdaimq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#khbtfdaimq thead, #khbtfdaimq tbody, #khbtfdaimq tfoot, #khbtfdaimq tr, #khbtfdaimq td, #khbtfdaimq th {\n  border-style: none;\n}\n\n#khbtfdaimq p {\n  margin: 0;\n  padding: 0;\n}\n\n#khbtfdaimq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 90%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#khbtfdaimq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#khbtfdaimq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#khbtfdaimq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#khbtfdaimq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#khbtfdaimq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#khbtfdaimq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#khbtfdaimq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#khbtfdaimq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#khbtfdaimq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#khbtfdaimq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#khbtfdaimq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#khbtfdaimq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#khbtfdaimq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#khbtfdaimq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#khbtfdaimq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#khbtfdaimq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#khbtfdaimq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#khbtfdaimq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#khbtfdaimq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#khbtfdaimq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#khbtfdaimq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#khbtfdaimq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#khbtfdaimq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#khbtfdaimq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#khbtfdaimq .gt_left {\n  text-align: left;\n}\n\n#khbtfdaimq .gt_center {\n  text-align: center;\n}\n\n#khbtfdaimq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#khbtfdaimq .gt_font_normal {\n  font-weight: normal;\n}\n\n#khbtfdaimq .gt_font_bold {\n  font-weight: bold;\n}\n\n#khbtfdaimq .gt_font_italic {\n  font-style: italic;\n}\n\n#khbtfdaimq .gt_super {\n  font-size: 65%;\n}\n\n#khbtfdaimq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#khbtfdaimq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#khbtfdaimq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#khbtfdaimq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#khbtfdaimq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#khbtfdaimq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#khbtfdaimq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#khbtfdaimq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#khbtfdaimq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Country\">Country</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Coup Attempted\">Coup Attempted</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Coup Succeeded\">Coup Succeeded</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Success Rate\">Success Rate</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Bolivia</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">23</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">11</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">47.8%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Argentina</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">20</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">7</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">35.0%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Sudan</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">17</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">6</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">35.3%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Haiti</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">13</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">9</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">69.2%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Venezuela</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">13</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">0</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">0.0%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Iraq</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">12</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">4</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">33.3%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Syria</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">12</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">8</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">66.7%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Thailand</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">12</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">8</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">66.7%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Ecuador</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">11</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">45.5%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Burundi</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">11</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">45.5%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Guatemala</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">10</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">5</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">50.0%</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"Coup Attempted\" class=\"gt_row gt_center\">491</td>\n<td headers=\"Coup Succeeded\" class=\"gt_row gt_center\">245</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">49.9%</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><div data-qmd=\"*Source: GIC dataset*\"><div class='gt_from_md'><p><em>Source: GIC dataset</em></p>\n</div></div></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nHowever, coups are high-stakes gambles with an all-or-nothing nature. Due to its\nillegality, the consequences of a failed coup can be severe, with perpetrators\nrisking imprisonment, exile, or even death. In some instances, repercussions\nextend to their families, which means coup plotters would not take the risk\nwithout some assurance of success.\n\nHistorical coup attempts and their success rates provide valuable hints about\ncoup plotters' decision-making processes. Despite the significant risks\nassociated with coups, as shown in @tbl-coups, there have been 491 coups\nworldwide since 1950. Importantly, about half of these coups have been\nsuccessful. At first glance, coups appear to be a high-success-rate political\nventure. However, compared to over 12,000 country-years since 1950, the\noccurrence of 491 coups is relatively rare, accounting for only about 4%\n(GIC).\n\nThe low occurrence rate and high success rate clearly indicate that the\ninitiation of coups is highly selective. In other words, the likelihood of a coup\noccurring depends greatly on its probability of success. However, the probability\nof success is not a factor that can be observed before a coup, at least not to\noutsiders and researchers, but coup plotters surely have more information on the\npossible outcome of coups.\n\nSince coup plotters meticulously assess potential outcomes before staging a coup,\ncoup researchers should also analyse what factors might affect the outcome of\ncoups. Otherwise, we ran the risk of selection bias. When considering the factors\nthat most affect the outcomes of coups, the current literature predominantly\nidentifies military power as the decisive factor in the success of coups.\nUltimately, military power is determined by the power structure within the\nregime.\n\nUnlike coup plotters, who have a clearer understanding of power structures and\ndynamics, including their supporters, followers, bystanders, and opponents,\nresearchers are not able to accurately observe this information. However, we can\nanalyse the most relevant factors which determine the balance of power and are\nobservable to us. This leads us to **regime type**, which reflects the\ndistribution of power within a government, encompassing who controls the\nmilitary, sets policy, and appoints officials. Since coup plotters consider the\nbalance of power within the regime before acting, this study argues that regime\ntype plays a crucial role in shaping coup attempts. Analysing which regime types\nare more susceptible to coups can offer valuable insights.\n\nWe employ a **double probit model with sample selection** to address the\nselection bias. This model allows us to analyze both the factors influencing coup\nsuccess and the factors related to the decision to initiate a coup attempt in the\nfirst place.\n\nThis study contributes to the literature in two key ways. First, it emphasizes\nthe importance of focusing on expected success rates as a driver of coup\nattempts, offering a more targeted approach compared to past studies. Second, it\nhighlights the significance of regime type as a factor influencing coup\nlikelihood, even when researchers lack perfect knowledge of a regime's internal\npower dynamics.\n\nThe subsequent section (Section 2) explores the dynamics of coup attempts and\ntheir outcomes. Section 3 delves into the research design, outlining the\nmethodology and variables used in the analysis. Section 4 presents and discusses\nthe empirical findings. Finally, Section 5 concludes the chapter by summarizing\nthe key insights and their implications.\n\n### Dynamics of coup attempts and outcomes\n\nCoup attempts are driven by a complex interplay of factors, including motivations\n(**disposition**) and the resources and opportunities available to succeed\n(**capability**).\n\n#### Motivations for coups\n\nThis section focuses on the motivations that compel challengers to undertake\ncoups. We can categorize coup motivations into three main types:\n\n**Personal Ambition:** Personal ambition is a significant motivator for the\nmajority of coup plotters, driven by the allure of absolute power, prestige, and\nwealth. The prospect of seizing absolute power provides an unparalleled\nopportunity to shape national policies, control resources, and make significant\ndecisions without constraints. The pursuit of prestige and recognition, along\nwith the potential for immense economic gain and wealth, further incentivizes\nindividuals. Additionally, the desire to leave a lasting legacy and make a\nhistorical impact can compel individuals to undertake the risky venture of\nstaging a coup.\n\n**Purported National Interest:** Sometimes coups are justified as necessary\ninterventions to address national crises, uphold the constitution, or facilitate\na transition to democracy. While the motivations behind such claims require\nscrutiny, genuine examples do exist. For instance, the 2010 coup in Niger ousted\nPresident Tandja, who attempted an unconstitutional third term by dissolving the\nopposing court and calling a self-serving referendum [@ginsburg2019].\n\n**Self-Preservation:** In some cases, coups serve as pre-emptive strikes against\nperceived threats. Coup leaders might not necessarily seek power, but rather fear\nelimination or political persecution by the incumbent regime. An example is Idi\nAmin's 1971 coup against Ugandan President Obote, who was attempting to remove\nAmin from his military command position [@sudduth2017].\n\nThese motivations are often most prevalent in autocratic regimes, where\njustifications under the guise of national interest or self-preservation can be\nused to mask personal agendas. Stable democracies rarely face the same level of\nconstitutional crises or political persecution that might necessitate a coup.\nHowever, new established democracies can be vulnerable to instability, economic\ndownturns, and democratic backsliding, creating opportunities for coup plotters\nto exploit these weaknesses and justify their actions.\n\nDespite the potential motivations outlined above, coups remain relatively\nuncommon, occurring in only about 4% of country-years since 1950. The main reason\nis that coup perpetrators face inherent disadvantages compared to incumbent\nleaders, highlighting the importance of capability. Even the most motivated\nplotters need the resources and opportunities to succeed. The next section will\nexplore the concept of capability in greater detail.\n\n#### Capability for coups\n\nFor coup plotters, the decision to act hinges not only on their motivations but\nalso on a calculated assessment of their chances of success. Several factors can\ninfluence this threshold:\n\n-   **Military Strength**: A clear advantage in military capabilities compared to\n    the incumbent regime significantly increases the odds of a successful coup.\n\n-   **Internal Divisions within the Regime**: Existing fractures within the\n    government's power structure can present opportunities for coup plotters to\n    exploit weaknesses and gain support from disgruntled factions.\n\n-   **Public Support**: Widespread discontent with the incumbent regime,\n    especially within the military or key sectors of society, can create an\n    environment ripe for a successful coup.\n\n-   **Foreign Backing**: External support from powerful nations can provide\n    resources, legitimacy, and even direct military intervention to tip the\n    scales in favour of the coup plotters.\n\nThe high success rate of coups since 1950, as shown in @tbl-coups, might suggest\nthat coups are not particularly difficult to succeed. However, it is important to\nconsider selection bias. We only observe attempted coups, not the numerous\ndispositions and conspiracies that never came to light. Analysing launched coup\ndata alone can be misleading.\n\nTo gain a more comprehensive understanding of coup attempts and their likelihood,\nwe need to move beyond historical data and employ a theoretical framework that\naccounts for selection bias. This framework will allow us to analyze the factors\ninfluencing both the success of coups and the decision to attempt a coup in the\nfirst place. The next section will delve into such a framework and its\nimplications for our understanding of coup attempts.\n\n#### Framework of coup success\n\nAn oft-cited framework [@gassebner2016; @aidt2019] provides a structured approach\nto assess the disposition and capability of coup attempts by evaluating the\nanticipated benefits for coup plotters. The expected pay-off of coups can be\nrepresented by the equation:\n\n$$\n\\begin{aligned}\nE(U) = p \\times B + (1 - p) \\times (-C)\n\\end{aligned}\n$$ {#eq-eq1}\n\nHere, $\\mathbf B$ represents the return of a successful coup, $\\mathbf C$\nsignifies the cost of a failed coup, and $p$ represents the probability of coup\nsuccess. The condition for staging a coup is when the expected benefit is\npositive, meaning that the expected pay-off is greater than 0. Rearranging the\nequation, we get:\n\n$$\n\\begin{aligned}\np \\times B > (1 - p) \\times C\n\\end{aligned}\n$$ {#eq-eq2}\n\n@eq-eq2 implies that for @eq-eq1 to hold, the expected benefits earned from\nsuccessful coups must outweigh the expected cost of failed coups.\n\nWhile seemingly clear, the equation faces practical challenges. Quantifying\n$\\mathbf B$ (the value of a successful coup) and $\\mathbf C$ (the cost of\nfailure) is difficult. The loss of life, freedom, or loved ones after a failed\ncoup, as well as the value of assuming leadership after a successful coup, are\nintangible concepts that defy precise measurement. As evidenced by the 1979 coup\nin Ghana[^4], the fate of the coup leader(s) hangs in the balance; they are high\nlikely to be killed if the coup fails, or to execute others if the coup succeeds.\n\nHowever, these challenges do not render the framework useless. Firstly, its core\nlogic remains valuable, offering insights into how coup plotters might assess the\nreturn and cost of their actions. Secondly, given the significant and elusive\nnature of precise values for $\\mathbf B$ and $\\mathbf C$, they can be treated as\nroughly equal. Consequently, there is no need to fret over how to measure and\ncompare these values precisely. Instead, we can shift our focus from $\\mathbf B$\nand $\\mathbf C$, to the probability of success ($p$), simplifying @eq-eq2 to:\n\n$$\n\\begin{aligned}\np > (1-p)\n\\end{aligned}\n$$ {#eq-eq3}\n\n@eq-eq3 suggests that, to hold @eq-eq2 true, a success probability greater than\n$50\\%$ is necessary. Interestingly, empirical data on coups since 1950 somewhat\nsupports this notion. As shown in @tbl-coups, the overall success rate is\n$49.9\\%$. While this falls short of the $50\\%$ threshold, it's important to\nconsider two factors. Firstly, this is an average rate, not necessarily\nreflective of the probabilities assessed by coup plotters beforehand. Secondly,\noutliers such as irrational actors and coups driven by self-preservation may not\nprioritize success probabilities. Taking these points into account, we can\npropose our first hypothesis:\n\n> ***H1: The fundamental determinant of a coup attempt is the perceived chance of\n> success. Coup plotters likely require a success threshold of at least 50%.***\n\nThis leads us to the next crucial question: What factors determine coup success,\ninfluencing the very decision to attempt one? We will discuss it in the next\nsection.\n\n#### Regime types and power dynamics\n\nThe high success rate in historical data is merely a post-event statistical\ndescription, not indicative of the probability of any specific coup. Importantly,\ncoup plotters do not rely on past success rates as their guide; instead, they\nassess their chances based on their unique context.\n\nMilitary strength undeniably plays a critical role in coup attempts. Control of\nthe armed forces offers a significant advantage, explaining why military coups\ndominate discussions on the topic. Much of the literature treats \"coup\" and\n\"military coup\" interchangeably, with scholars like @powell2011 finding that half\nof 14 studies attribute coups solely to the military. Consequently, significant\nfocus, from both researchers and policy-makers, centres on the balance of power\nbetween civilian and military authorities, or among military factions themselves.\nStrategies like \"keeping the military content\" [@aidt2019] or \"providing them\nwith resources\" [@huntington1991democratization] aim to reduce military\nintervention. Empirical research informs coup-proofing strategies that either\ndecrease the military's desire for coups or raise barriers to success\n[@leon2013a; @powell2018].\n\nHowever, while military power is decisive, it complicates the analysis. As\n@tbl-regimes demonstrates, military regimes, despite concentrated military\ncontrol, exhibit surprising instability, experiencing the most frequent coup\nattempts. This highlights a crucial issue: the intra-military component. Treating\nthe military as a monolithic entity ignores its complex internal dynamics\n[@singh2016]. Any military comprises diverse groups with their own hierarchies,\nfostering suspicion, competition, and vigilance rather than unity. The\nclandestine nature of coups necessitates small, secretive groups. Plotters are\nunsure of other factions' stances and fear their opposition or intervention, as\nexemplified by the swiftly thwarted 2021 Niger coup[^5]. The success of a coup\nhinges heavily on other military factions' reactions [@geddes1999].\n\nMoreover, military force is not the only factor shaping the balance of power.\nInternal divisions within the ruling elites, public support, and foreign backing\nalso play important roles. Since the balance of power is not a clearly observable\nvariable, especially difficult to measure for outsiders and academic scholars, we\ncan shift our focus from who controls power in a specific context to what factors\nshape the balance of power. This leads us to regime type, as the classification\nof regime type is based mainly on the power structure. For example,\n\"...definition of regimes emphasizes the rules that identify the group from which\nleaders can come and determine who influences leadership choice and policy\"\n[@geddes2014, p. 314]. We will leverage this framework to categorize autocracies\nbased on leadership origin and decision-making, classifying regimes into three\nmain categories: military, personalist, and dominant-party.\n\n-   **Military Regimes:** Characterized by the dominance of a junta—a group of\n    military officers who control the regime's power structure, including\n    leadership selection and policy formulation. Examples include the Brazilian\n    regime (1964-1985), the Argentine regime (1976-1983), and the Salvadoran\n    regime (1948-1984) [@geddes1999].\n\n-   **Personalist Regimes:** Power resides with a single, charismatic leader who\n    controls policy, the military, and succession. Regimes like Rafael Trujillo's\n    in the Dominican Republic (1930-1961), Idi Amin's in Uganda (1971-1979), and\n    Jean-Bédel Bokassa's in the Central African Republic (1966-1979) exemplify\n    personalist rule (ibid.).\n\n-   **Dominant-Party Regimes:** Power rests within a well-organized ruling party,\n    with leaders acting as its representatives. The party structure and ideology\n    foster internal cohesion and a long-term vision. Examples include the Partido\n    Revolucionario Institucional (PRI) in Mexico, the Revolutionary Party of\n    Tanzania (CCM), and Leninist parties in various Eastern European countries\n    (ibid.).\n\nThe critical distinction between regime types lies in the unique power balance\nestablished during their seizure of power, often through irregular and violent\nmeans, frequently involving military confrontations. This power struggle\ntypically results in the emergence of the most competent group—be it a military\njunta, a political party, or a strongman—as the core leadership. Furthermore, the\nearly stages of new regimes are often marked by internal purges to consolidate\npower and eliminate potential rivals [@sudduth2017; @roessler2011].\n\nFollowing these external challenges and internal purges, new power dynamics\nemerge in three primary forms: dominant-party regimes, personalist regimes, and\nmilitary regimes. These contrasting power dynamics significantly influence a\nregime's susceptibility to coups. Dominant-party regimes, characterized by a\nwell-organized party with clear ideology, hierarchy, and discipline, exhibit the\ngreatest resilience against coups due to their institutionalized structures and\nunified leadership. Personalist regimes, where power centers around a single\nstrong leader, are relatively stable during the leader's tenure. However, they\nface a higher risk of coups, particularly due to the lack of clear succession\nplans and vulnerabilities associated with the leader's personal weaknesses,\nhealth issues, and finite lifespan. Military regimes, characterized by power\nstruggles within a junta, are the most vulnerable to coups. The absence of a\nclear final authority in military regimes often leads to internal conflicts, and\nthe presence of multiple military factions increases the likelihood of resolving\ndisputes through force, making these regimes the least stable. @tbl-regimes1\nsummarises the key characteristics of the three main regime types.\n\nThese contrasting power dynamics significantly influence a regime's\nsusceptibility to coups. As @tbl-regimes confirms, military regimes, despite\nrepresenting only 5.6% of country-years, experience a disproportionate share of\ncoups, accounting for over 22% of all occurrences. Personalist regimes face a\nsimilarly high coup risk, constituting 23% of coups while representing only 13%\nof country-years. Conversely, dominant-party regimes, with their\ninstitutionalized structures and unified leadership, exhibit the greatest\nresilience. They represent 22.6% of country-years but account for only 16.7% of\ncoups. The column \"Coup Likelihood\" clearly illustrates the varying risks:\nmilitary regimes have the highest likelihood at 17.2%, followed by personalist\nregimes at 7.7%, and dominant-party regimes at 3.2% (excluding *Other* regime\ntypes).\n\n> ***H2: Due to their balance of power dynamics, military regimes are more prone\n> to coups, followed by personalist regimes, while dominant-party regimes are the\n> least likely to experience coups among the three.***\n\n\\newpage\n\n\\blandscape\n\n\n::: {#tbl-regimes1 .cell tbl-cap='Main features of different types of regimes'}\n\n```{.r .cell-code}\nread.csv(here(\"data/regimes_comparison.csv\")) |> \n  clean_names(case = \"title\") |> \n  gt() |> \n  tab_options(column_labels.font.weight = \"bold\",\n              table.width = pct(100),\n              table.align = \"center\",\n              page.orientation = \"landscape\"\n              ) |>\n  cols_width(\n    1:6 ~ px(100)\n  ) |>\n  tab_source_note(source_note = md(\"*Source: GWF & Author*\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fcloqancvu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fcloqancvu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fcloqancvu thead, #fcloqancvu tbody, #fcloqancvu tfoot, #fcloqancvu tr, #fcloqancvu td, #fcloqancvu th {\n  border-style: none;\n}\n\n#fcloqancvu p {\n  margin: 0;\n  padding: 0;\n}\n\n#fcloqancvu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fcloqancvu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fcloqancvu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fcloqancvu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fcloqancvu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fcloqancvu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fcloqancvu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fcloqancvu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fcloqancvu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fcloqancvu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fcloqancvu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fcloqancvu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fcloqancvu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fcloqancvu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fcloqancvu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fcloqancvu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fcloqancvu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fcloqancvu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fcloqancvu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fcloqancvu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fcloqancvu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fcloqancvu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fcloqancvu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fcloqancvu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fcloqancvu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fcloqancvu .gt_left {\n  text-align: left;\n}\n\n#fcloqancvu .gt_center {\n  text-align: center;\n}\n\n#fcloqancvu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fcloqancvu .gt_font_normal {\n  font-weight: normal;\n}\n\n#fcloqancvu .gt_font_bold {\n  font-weight: bold;\n}\n\n#fcloqancvu .gt_font_italic {\n  font-style: italic;\n}\n\n#fcloqancvu .gt_super {\n  font-size: 65%;\n}\n\n#fcloqancvu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fcloqancvu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fcloqancvu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fcloqancvu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fcloqancvu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fcloqancvu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fcloqancvu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fcloqancvu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fcloqancvu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout: fixed;; width: 100%\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Regime Type\">Regime Type</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Power Concentration\">Power Concentration</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Succession\">Succession</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Military Alignment\">Military Alignment</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Stability\">Stability</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Examples\">Examples</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Regime Type\" class=\"gt_row gt_left\">Military</td>\n<td headers=\"Power Concentration\" class=\"gt_row gt_left\">Junta</td>\n<td headers=\"Succession\" class=\"gt_row gt_left\">Unclear</td>\n<td headers=\"Military Alignment\" class=\"gt_row gt_left\">May have significant influence</td>\n<td headers=\"Stability\" class=\"gt_row gt_left\">Low</td>\n<td headers=\"Examples\" class=\"gt_row gt_left\">Brazil (1964-1985), Argentina (1976-1983)</td></tr>\n    <tr><td headers=\"Regime Type\" class=\"gt_row gt_left\">Personalist</td>\n<td headers=\"Power Concentration\" class=\"gt_row gt_left\">Single Leader</td>\n<td headers=\"Succession\" class=\"gt_row gt_left\">Unclear or dependent on leader's will</td>\n<td headers=\"Military Alignment\" class=\"gt_row gt_left\">Subordinated to leader</td>\n<td headers=\"Stability\" class=\"gt_row gt_left\">Moderate (initially), Low (long-term)</td>\n<td headers=\"Examples\" class=\"gt_row gt_left\">Dominican Republic (Trujillo, 1930-1961)</td></tr>\n    <tr><td headers=\"Regime Type\" class=\"gt_row gt_left\">Dominant-Party</td>\n<td headers=\"Power Concentration\" class=\"gt_row gt_left\">Party Leadership</td>\n<td headers=\"Succession\" class=\"gt_row gt_left\">Institutionalized</td>\n<td headers=\"Military Alignment\" class=\"gt_row gt_left\">Aligned with the party</td>\n<td headers=\"Stability\" class=\"gt_row gt_left\">High</td>\n<td headers=\"Examples\" class=\"gt_row gt_left\">Mexico (PRI), China (CPC)</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"6\"><div data-qmd=\"*Source: GWF & Author*\"><div class='gt_from_md'><p><em>Source: GWF &amp; Author</em></p>\n</div></div></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\\newpage\n\n\n::: {#tbl-regimes .cell tbl-cap='Regime types and coups since 1950'}\n\n```{.r .cell-code}\nregimes <- REIGN |>\n  distinct(reign_cowcode, year, .keep_all = T) |>\n  mutate(\n    regime_type = case_when(\n      gwf_regimetype %in% c(\n        \"party-based\",\n        \"party-personal\",\n        \"party-military\",\n        \"party-personal-military\",\n        \"oligarchy\"\n      ) ~ \"dominant-party\",\n      gwf_regimetype == \"personal\" ~ \"personal\",\n      gwf_regimetype %in% c(\"military\", \"military personal\", \"indirect military\") ~ \"military\",\n      gwf_regimetype == \"monarchy\" ~ \"monarchy\",\n      gwf_regimetype %in% c(\"presidential\", \"parliamentary\") ~ \"democracy\",\n      TRUE ~ \"other\"\n    )\n  ) |>\n  filter(year > 1949)\n\nregime_total <- regimes |>\n  tabyl(regime_type) |> \n  arrange(-n) |> \n  adorn_totals(\"row\") |> \n  mutate(country_year =n,\n         share = percent(percent),\n         .keep = \"unused\") \n  \n\ncoup1 <- Coup |>\n  select(country, ccode, year, coup)\n\ncoup_by_regime <- regimes |>\n  select(ccode = reign_cowcode, extended_country_name, year, regime_type) |>\n  full_join(coup1, by = join_by(ccode, year)) |>\n  mutate(regime = na.locf(regime_type, .by = ccode)) |>\n  filter(!is.na(coup)) |>\n  tabyl(regime) |> \n  adorn_totals(\"row\") |> \n  mutate(num_of_coups = n,\n         percent_of_coups = percent(percent,accuracy = 0.1),\n         .keep = \"unused\") \n\ncoup_by_succeed <- regimes |>\n  select(ccode = reign_cowcode, extended_country_name, year, regime_type) |>\n  full_join(coup1, by = join_by(ccode, year)) |>\n  mutate(regime = na.locf(regime_type, .by = ccode)) |>\n  filter(!is.na(coup),\n         coup == 2) |>\n  tabyl(regime) |> \n  adorn_totals(\"row\") |> \n  select(regime, succeeded_coup = n) \n\ncoup_regimes <-  coup_by_regime |> \n  left_join(coup_by_succeed) |> \n  mutate(success_rate = percent(succeeded_coup / num_of_coups, accuracy = 0.1))\n\nregime_total |>\n  left_join(coup_regimes, join_by(regime_type == regime)) |>\n  mutate(regime_type = str_to_title(regime_type),\n         coup_likelihood = percent(num_of_coups / country_year, accuracy = 0.1)) |>\n  select(-succeeded_coup) |> \n  clean_names(case = \"title\") |>\n  gt() |>\n  tab_options(column_labels.font.weight = \"bold\",\n              table.width = pct(100),\n              table.align = \"center\") |>\n  tab_source_note(source_note = md(\"*Source: REIGN and GIC Datasets*\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nrjqlnaazt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nrjqlnaazt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nrjqlnaazt thead, #nrjqlnaazt tbody, #nrjqlnaazt tfoot, #nrjqlnaazt tr, #nrjqlnaazt td, #nrjqlnaazt th {\n  border-style: none;\n}\n\n#nrjqlnaazt p {\n  margin: 0;\n  padding: 0;\n}\n\n#nrjqlnaazt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nrjqlnaazt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nrjqlnaazt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nrjqlnaazt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nrjqlnaazt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nrjqlnaazt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nrjqlnaazt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nrjqlnaazt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nrjqlnaazt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nrjqlnaazt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nrjqlnaazt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nrjqlnaazt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nrjqlnaazt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nrjqlnaazt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nrjqlnaazt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrjqlnaazt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nrjqlnaazt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nrjqlnaazt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nrjqlnaazt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrjqlnaazt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nrjqlnaazt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrjqlnaazt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nrjqlnaazt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrjqlnaazt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nrjqlnaazt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrjqlnaazt .gt_left {\n  text-align: left;\n}\n\n#nrjqlnaazt .gt_center {\n  text-align: center;\n}\n\n#nrjqlnaazt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nrjqlnaazt .gt_font_normal {\n  font-weight: normal;\n}\n\n#nrjqlnaazt .gt_font_bold {\n  font-weight: bold;\n}\n\n#nrjqlnaazt .gt_font_italic {\n  font-style: italic;\n}\n\n#nrjqlnaazt .gt_super {\n  font-size: 65%;\n}\n\n#nrjqlnaazt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nrjqlnaazt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nrjqlnaazt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nrjqlnaazt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nrjqlnaazt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nrjqlnaazt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nrjqlnaazt .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nrjqlnaazt .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nrjqlnaazt div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Regime Type\">Regime Type</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Country Year\">Country Year</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Share\">Share</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Num of Coups\">Num of Coups</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Percent of Coups\">Percent of Coups</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Success Rate\">Success Rate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Coup Likelihood\">Coup Likelihood</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Regime Type\" class=\"gt_row gt_left\">Democracy</td>\n<td headers=\"Country Year\" class=\"gt_row gt_right\">5303</td>\n<td headers=\"Share\" class=\"gt_row gt_right\">46.7%</td>\n<td headers=\"Num of Coups\" class=\"gt_row gt_right\">122</td>\n<td headers=\"Percent of Coups\" class=\"gt_row gt_right\">24.8%</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">51.6%</td>\n<td headers=\"Coup Likelihood\" class=\"gt_row gt_right\">2.3%</td></tr>\n    <tr><td headers=\"Regime Type\" class=\"gt_row gt_left\">Dominant-Party</td>\n<td headers=\"Country Year\" class=\"gt_row gt_right\">2569</td>\n<td headers=\"Share\" class=\"gt_row gt_right\">22.6%</td>\n<td headers=\"Num of Coups\" class=\"gt_row gt_right\">82</td>\n<td headers=\"Percent of Coups\" class=\"gt_row gt_right\">16.7%</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">53.7%</td>\n<td headers=\"Coup Likelihood\" class=\"gt_row gt_right\">3.2%</td></tr>\n    <tr><td headers=\"Regime Type\" class=\"gt_row gt_left\">Personal</td>\n<td headers=\"Country Year\" class=\"gt_row gt_right\">1477</td>\n<td headers=\"Share\" class=\"gt_row gt_right\">13.0%</td>\n<td headers=\"Num of Coups\" class=\"gt_row gt_right\">113</td>\n<td headers=\"Percent of Coups\" class=\"gt_row gt_right\">23.0%</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">44.2%</td>\n<td headers=\"Coup Likelihood\" class=\"gt_row gt_right\">7.7%</td></tr>\n    <tr><td headers=\"Regime Type\" class=\"gt_row gt_left\">Monarchy</td>\n<td headers=\"Country Year\" class=\"gt_row gt_right\">1056</td>\n<td headers=\"Share\" class=\"gt_row gt_right\">9.3%</td>\n<td headers=\"Num of Coups\" class=\"gt_row gt_right\">25</td>\n<td headers=\"Percent of Coups\" class=\"gt_row gt_right\">5.1%</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">56.0%</td>\n<td headers=\"Coup Likelihood\" class=\"gt_row gt_right\">2.4%</td></tr>\n    <tr><td headers=\"Regime Type\" class=\"gt_row gt_left\">Military</td>\n<td headers=\"Country Year\" class=\"gt_row gt_right\">638</td>\n<td headers=\"Share\" class=\"gt_row gt_right\">5.6%</td>\n<td headers=\"Num of Coups\" class=\"gt_row gt_right\">110</td>\n<td headers=\"Percent of Coups\" class=\"gt_row gt_right\">22.4%</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">48.2%</td>\n<td headers=\"Coup Likelihood\" class=\"gt_row gt_right\">17.2%</td></tr>\n    <tr><td headers=\"Regime Type\" class=\"gt_row gt_left\">Other</td>\n<td headers=\"Country Year\" class=\"gt_row gt_right\">322</td>\n<td headers=\"Share\" class=\"gt_row gt_right\">2.8%</td>\n<td headers=\"Num of Coups\" class=\"gt_row gt_right\">39</td>\n<td headers=\"Percent of Coups\" class=\"gt_row gt_right\">7.9%</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">53.8%</td>\n<td headers=\"Coup Likelihood\" class=\"gt_row gt_right\">12.1%</td></tr>\n    <tr><td headers=\"Regime Type\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"Country Year\" class=\"gt_row gt_right\">11365</td>\n<td headers=\"Share\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"Num of Coups\" class=\"gt_row gt_right\">491</td>\n<td headers=\"Percent of Coups\" class=\"gt_row gt_right\">100.0%</td>\n<td headers=\"Success Rate\" class=\"gt_row gt_right\">49.9%</td>\n<td headers=\"Coup Likelihood\" class=\"gt_row gt_right\">4.3%</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"7\"><div data-qmd=\"*Source: REIGN and GIC Datasets*\"><div class='gt_from_md'><p><em>Source: REIGN and GIC Datasets</em></p>\n</div></div></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\\elandscape\n\n### Research Design\n\n#### Double probit with sample selection model\n\nThis study employs a sophisticated statistical approach to account for the\nselective nature of coup attempts. While coup attempt rates vary across regimes\n(as discussed previously), success rates tend to be surprisingly consistent,\nhovering around 50% (as shown in @tbl-regimes). This suggests that coup attempts\nare not random acts, but rather strategically planned and undertaken only when\nthe odds of success appear favourable. A standard statistical model would not\naccount for this selectivity, potentially leading to biased results.\n\nTo address this issue, we utilize a two-stage sample selection model, similar to\nthe approach used by @powell2012. This model has two parts:\n\n-   **Selection Equation (Stage 1):** This stage analyzes the factors influencing\n    whether a coup attempt occurs in a particular regime. The primary explanatory\n    variable here is regime type, as previously discussed. Additional control\n    variables may also be included, denoted by $\\mathbf{XB}$.\n\n-   **Outcome Equation (Stage 2):** This stage focuses on the probability of\n    success for those coup attempts that actually take place.\n\nThe primary explanatory variables are regime types, as previously discussed.\nControl variables are included in $\\mathbf{XB}$. The selection equation (first\nstage) models the probability that a coup attempt occurs and can be expressed as\nfollows:\n\n$$\n\\begin{aligned}\ny_1^*=\\alpha_0 + \\alpha_1 Regime_i + \\mathbf {XA} + \\mu_{1i}\n\\end{aligned}\n$$ {#eq-eq4}\n\nHere, ${y_1}^*$ is an unobserved variable, which may be known to coup plotters.\n$Regime_i$ is a categorical variable (*military*, *personalist*, or\n*dominant-party*). $\\mathbf{XB}$ captures other control variables, such as the\neconomic crisis index, previous coups, military expenditure, etc.\n\nThe observed binary outcome $\\mathbf{y_1}$ is:\n\n$$\n\\begin{aligned}\ny_1 = \n\\begin{cases} \n1 &\\text{if $y_1^*>0$ (coup attempt occurs)} \\\\\n0 &\\text{if $y_1^*\\le0$ (no coup attempt)}\n\\end{cases}\n\\end{aligned}\n$$\\\nIn the first stage, if $y_1^*\\le0$, no coup attempt occurs in a given\ncountry-year, indicating that the unobserved variable does not reach the\nthreshold. If $y_1^*>0$, at least one coup attempt is made in a country-year,\nindicating that the unobserved variable surpasses the threshold. The probability\nis expressed as:\n\n$$\n\\begin{aligned}\nProb(y_1 =1)&=Prob(y_{1}^*>0) \\\\\n&=\\Phi(\\alpha_0 + \\alpha_1 Regime_i + \\mathbf{XA})\n\\end{aligned}\n$$ {#eq-eq4a}\n\nSimilarly, the outcome equation (second stage) models the probability that a coup\nattempt is successful, given that it occurs:\n\n$$\n\\begin{aligned}\ny_2^*=\\beta_0 + \\beta_1 Regime_i + \\mathbf {XB} + \\mu_{2i}\n\\end{aligned}\n$$ {#eq-eq5}\n\nThe observed outcome $y_2$ is:\n\n$$\n\\begin{aligned}\ny_2 = \n\\begin{cases} \n1 &\\text{if $y_2^*>0$ (coup succeeds)} \\\\\n0 &\\text{if $y_2^*\\le0$ (coup fails)}\n\\end{cases}\n\\end{aligned}\n$$\n\nThe probability equations is:\n\n$$\n\\begin{aligned}\nProb(y_2=1|y_1 =1)=\\Phi(\\beta_0 + \\beta_1 Regime_i + \\mathbf{XB})\n\\end{aligned}\n$$ {#eq-eq5a}\n\n#### Variables\n\n-   Dependent variable\n\nOur analysis utilizes data on coup attempts and outcomes from @powell2011. A\nsuccessful coup is defined as one where the incumbent leader is removed from\npower for more than seven days. The dataset covers the period from 1950 to 2023\nand includes information on 491 coup attempts, with roughly half (245) being\nsuccessful. Descriptive statistics for these coup attempts and regime types can\nbe found in @tbl-coups and @tbl-regimes.\n\n-   Key Independent Variable: Regime Type\n\nThe core variable of interest is regime type, categorized following the\nclassification system of @geddes2014 (GWF). We focus on military, personalist,\nand dominant-party regimes, with democracies and monarchies included for\ncomparison. Descriptive statistics for regime types are presented in\n@tbl-regimes.\n\n-   Control variables\n\nOur control variables are chosen based on the research of @gassebner2016. They\nanalyzed 66 factors potentially influencing coups and found that slow economic\ngrowth, prior coup attempts, and other forms of political violence are\nparticularly significant factors. Therefore, we include economic performance,\npolitical violence, and the number of previous coups as our main control\nvariables.\n\n**Economic Performance:** We measure economic performance using the current-trend\n($CT$) ratio developed by @krishnarajan2019. This ratio compares a country's\ncurrent GDP per capita to the average GDP per capita over the previous five\nyears. A higher $CT$ ratio indicates stronger economic performance. We use GDP\nper capita data (in constant 2017 international 1000 dollars, PPP) from the V-Dem\ndataset by @fariss2022, lagged by one year to reflect the prior year's economic\nimpact. For a country $i$ at year $t$, the $CT$ ratio is calculated as follows:\n$$\n\\begin{aligned}\nCT_{i,t} = {GDP/cap_{i,t} \\over {1 \\over 5} {\\sum_{k=1}^5GDP/cap_{i,t-k}}}\n\\end{aligned}\n$$\n\n**Political Violence:** We capture overall regime stability by including a\nviolence index that encompasses all types of internal and interstate wars and\nviolence. This data comes from the Major Episodes of Political Violence dataset\nby Marshall [@marshall2005current].\n\n**Previous coups:** The number of previous coups in a country is included in the\nfirst-stage (selection) model to assess its influence on the likelihood of a coup\nattempt. However, it is excluded from the second-stage model (outcome) because\nthe number of past coups may not directly impact the outcome of a specific coup\nattempt. Recognizing that previous coups from a long time ago might not\nsignificantly affect the current situation, I ran another regression using the\ntime distance since the last coup instead of the number of previous coups for\ncomparison. This approach accounts for the diminishing impact of past events over\ntime, providing a potentially more accurate assessment of how historical coup\nactivity influences the likelihood of current coup attempts.\n\n### Results and Discussion\n\n::: {.content-visible when-format=\"html\"}\n\n::: {#tbl-model .cell tbl-cap='Sample Selection Model of Regime Type and Coup Success, 1950-2019'}\n\n```{.r .cell-code}\ndownload.file(\"https://raw.githubusercontent.com/reddylee/Datasets/main/political_violence.csv\", \"data/political_violence.csv\")\npolitical_violence <- fread(here(\"data/political_violence.csv\")) |> \n  dplyr::select(ccode, year, violence = actotal)\n\ngdp <- vdem |> \n  dplyr::select(ccode = COWcode, year, gdppc = e_gdppc) |> \n  filter(year > 1940) |> \n  mutate(ct = gdppc / lag(rollapply(gdppc, width = 5, FUN = mean,\n                               align = 'right', fill = NA)),\n         .by = c(ccode)) \n\ndownload.file(\"https://www.uky.edu/~clthyn2/coup_data/powell_thyne_ccode_year.txt\", \"data/coup_all.csv\")\ncoup_all <- fread(here(\"data/coup_all.csv\")) |> \n  mutate(coup = case_when(\n    coup1 == 0 ~ 0,\n    coup1 == 2 | coup2 == 2 | coup3 == 2 | coup4 == 2 ~ 2,\n    TRUE ~ 1\n  )) |>\n  group_by(ccode) %>%\n  arrange(year) %>%\n  mutate(pre_coups = lag(cumsum(coup %in% c(1, 2)), default = 0),\n         last_coup_year = lag(case_when(coup %in% c(1, 2)  ~ year,\n                                        TRUE ~ NA_integer_)),\n         last_coup_year = case_when(year == min(year) ~ year,\n                                    TRUE ~ last_coup_year)) |> \n  fill(last_coup_year, .direction = \"down\") |>\n  mutate(time_since_last_coup = year - last_coup_year,\n         coup_dummy = case_when(pre_coups == 0 ~ 0,\n                                TRUE ~ 1)) |>\n  dplyr::select(ccode, year, coup, pre_coups, time_since_last_coup, coup_dummy) \n\nreg_data <- regimes |> \n  dplyr::select(country = extended_country_name,\n         ccode = reign_cowcode, year, regime_type) |>\n  left_join(coup_all, by = join_by(ccode, year)) |> \n  left_join(political_violence, by = join_by(ccode, year)) |>\n  left_join(gdp, by = join_by(ccode, year)) |> \n  filter(!is.na(gdppc)) |> \n  mutate(violence = na.locf(violence, .by = ccode)) \n\nmodel_1 <- reg_data |>\n  filter(regime_type != \"other\") |>\n  mutate(regime = fct_relevel(regime_type, \"dominant-party\"),\n         ect = (ct-1)*100) |>\n  selection(coup > 0 ~ regime + ect + gdppc + violence + coup_dummy*time_since_last_coup,\n            coup > 1 ~ regime + ect + gdppc + violence,\n            data = _) \n\nmodel_1_selection <- model_1\nmodel_1_selection$param$index$betaO <- model_1$param$index$betaS\nmodel_1_selection$param$index$betaS <- model_1$param$index$betaO\n\nmodel_2 <- reg_data |>\n  filter(regime_type != \"other\") |>\n  mutate(regime = fct_relevel(regime_type, \"dominant-party\"),\n         ect = (ct-1)*100,\n         Coup = coup) |>\n  select(Coup, regime, ect, gdppc, violence, coup_dummy = pre_coups) |> \n  selection(Coup > 0 ~ regime + ect + gdppc + violence + coup_dummy,\n            Coup > 1 ~ regime + ect + gdppc + violence,\n            #method = \"2step\",\n            data = _) \n\nmodel_2_selection <- model_2\nmodel_2_selection$param$index$betaO <- model_2$param$index$betaS\nmodel_2_selection$param$index$betaS <- model_2$param$index$betaO\n\nstargazer(model_2_selection, model_2, model_1_selection, model_1,\n          type = \"html\",\n          header = F,\n          dep.var.caption = \"\",\n          dep.var.labels = c(\"Model 1\", \"Model 2\"),\n          #dep.var.labels.include = T,\n          #multicolumn = T,\n          #title = \"Sample Selection Model of Regime Types and Coups, 1950-2019\",\n          column.labels = c(\"Coup Attempts\", \"Coup Outcome\",\"Coup Attempts\", \"Coup Outcome\"),\n          intercept.bottom = F,\n          #label = \"results\",\n          covariate.labels = c(\"Constant\", \"Regime: Democracy\", \"\\\\hspace{1.6cm}Military\", \"\\\\hspace{1.6cm}Monarchy\", \"\\\\hspace{1.6cm}Personalist\", \"Economic trend\", \"GDP per capita\", \"Political violence\", \"Previous coups (P)\", \"Yrs since coup (Y)\", \"Interaction term: P * Y\"),\n          summary.logical = F,\n          column.sep.width = \"7pt\",\n          font.size = \"small\"\n          )\n```\n\n\n<table style=\"text-align:center\"><tr><td colspan=\"5\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"></td><td colspan=\"2\">Model 1</td><td colspan=\"2\">Model 2</td></tr>\n<tr><td style=\"text-align:left\"></td><td>Coup Attempts</td><td>Coup Outcome</td><td>Coup Attempts</td><td>Coup Outcome</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(1)</td><td>(2)</td><td>(3)</td><td>(4)</td></tr>\n<tr><td colspan=\"5\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Constant</td><td>-1.774<sup>***</sup></td><td>-1.803<sup>***</sup></td><td>-1.663<sup>***</sup></td><td>-0.653</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.058)</td><td>(0.360)</td><td>(0.088)</td><td>(0.518)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Regime: Democracy</td><td>0.056</td><td>0.068</td><td>0.043</td><td>0.042</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.072)</td><td>(0.121)</td><td>(0.075)</td><td>(0.192)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">1.6cmMilitary</td><td>0.687<sup>***</sup></td><td>0.596<sup>***</sup></td><td>0.345<sup>***</sup></td><td>0.247</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.084)</td><td>(0.170)</td><td>(0.091)</td><td>(0.229)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">1.6cmMonarchy</td><td>0.282<sup>**</sup></td><td>0.178</td><td>0.234<sup>*</sup></td><td>0.088</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.118)</td><td>(0.201)</td><td>(0.123)</td><td>(0.310)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">1.6cmPersonalist</td><td>0.319<sup>***</sup></td><td>0.128</td><td>0.134<sup>*</sup></td><td>-0.145</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.075)</td><td>(0.170)</td><td>(0.080)</td><td>(0.205)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Economic trend</td><td>-0.015<sup>***</sup></td><td>-0.004</td><td>-0.014<sup>***</sup></td><td>0.009</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.002)</td><td>(0.007)</td><td>(0.002)</td><td>(0.008)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">GDP per capita</td><td>-0.028<sup>***</sup></td><td>-0.028<sup>***</sup></td><td>-0.016<sup>***</sup></td><td>-0.016</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.003)</td><td>(0.006)</td><td>(0.003)</td><td>(0.010)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Political violence</td><td>0.033<sup>**</sup></td><td>0.033<sup>*</sup></td><td>0.038<sup>***</sup></td><td>0.025</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.013)</td><td>(0.020)</td><td>(0.013)</td><td>(0.031)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Previous coups (P)</td><td>0.030<sup>***</sup></td><td></td><td>0.447<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.010)</td><td></td><td>(0.086)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Yrs since coup (Y)</td><td></td><td></td><td>-0.018<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td>(0.004)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Interaction term: P * Y</td><td></td><td></td><td>-0.013<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td>(0.005)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td colspan=\"5\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Observations</td><td>9,606</td><td>9,606</td><td>9,606</td><td>9,606</td></tr>\n<tr><td style=\"text-align:left\">Log Likelihood</td><td>-1,663.646</td><td>-1,663.646</td><td>-1,598.603</td><td>-1,598.603</td></tr>\n<tr><td style=\"text-align:left\">rho</td><td>0.898<sup>***</sup> (0.158)</td><td>0.898<sup>***</sup> (0.158)</td><td>0.386<sup>*</sup> (0.234)</td><td>0.386<sup>*</sup> (0.234)</td></tr>\n<tr><td colspan=\"5\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"><em>Note:</em></td><td colspan=\"4\" style=\"text-align:right\"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>\n</table>\n:::\n\n\nThe double probit model with sample selection, estimated using the\nsampleSelection package [@sampleSelection-2] in R, provides valuable insights\ninto the factors influencing coup attempts and their outcomes across different\nregime types from 1950 to 2019 (@tbl-model). We present two models that differ\nslightly in their treatment of previous coups: Model 1 incorporates the number of\nprevious coups, while Model 2 utilizes the time elapsed since the last coup.\n:::\n\n::: {.content-visible unless-format=\"html\"}\n\n\n```{.r .cell-code}\ndownload.file(\"https://raw.githubusercontent.com/reddylee/Datasets/main/political_violence.csv\", \"data/political_violence.csv\")\npolitical_violence <- fread(here(\"data/political_violence.csv\")) |> \n  dplyr::select(ccode, year, violence = actotal)\n\ngdp <- vdem |> \n  dplyr::select(ccode = COWcode, year, gdppc = e_gdppc) |> \n  filter(year > 1940) |> \n  mutate(ct = gdppc / lag(rollapply(gdppc, width = 5, FUN = mean,\n                               align = 'right', fill = NA)),\n         .by = c(ccode)) \n\ndownload.file(\"https://www.uky.edu/~clthyn2/coup_data/powell_thyne_ccode_year.txt\", \"data/coup_all.csv\")\ncoup_all <- fread(here(\"data/coup_all.csv\")) |> \n  mutate(coup = case_when(\n    coup1 == 0 ~ 0,\n    coup1 == 2 | coup2 == 2 | coup3 == 2 | coup4 == 2 ~ 2,\n    TRUE ~ 1\n  )) |>\n  group_by(ccode) %>%\n  arrange(year) %>%\n  mutate(pre_coups = lag(cumsum(coup %in% c(1, 2)), default = 0),\n         last_coup_year = lag(case_when(coup %in% c(1, 2)  ~ year,\n                                        TRUE ~ NA_integer_)),\n         last_coup_year = case_when(year == min(year) ~ year,\n                                    TRUE ~ last_coup_year)) |> \n  fill(last_coup_year, .direction = \"down\") |>\n  mutate(time_since_last_coup = year - last_coup_year,\n         coup_dummy = case_when(pre_coups == 0 ~ 0,\n                                TRUE ~ 1)) |>\n  dplyr::select(ccode, year, coup, pre_coups, time_since_last_coup, coup_dummy) \n\nreg_data <- regimes |> \n  dplyr::select(country = extended_country_name,\n         ccode = reign_cowcode, year, regime_type) |>\n  left_join(coup_all, by = join_by(ccode, year)) |> \n  left_join(political_violence, by = join_by(ccode, year)) |>\n  left_join(gdp, by = join_by(ccode, year)) |> \n  filter(!is.na(gdppc)) |> \n  mutate(violence = na.locf(violence, .by = ccode)) \n\nmodel_1 <- reg_data |>\n  filter(regime_type != \"other\") |>\n  mutate(regime = fct_relevel(regime_type, \"dominant-party\"),\n         ect = (ct-1)*100) |>\n  selection(coup > 0 ~ regime + ect + gdppc + violence + coup_dummy*time_since_last_coup,\n            coup > 1 ~ regime + ect + gdppc + violence,\n            data = _) \n\nmodel_1_selection <- model_1\nmodel_1_selection$param$index$betaO <- model_1$param$index$betaS\nmodel_1_selection$param$index$betaS <- model_1$param$index$betaO\n\nmodel_2 <- reg_data |>\n  filter(regime_type != \"other\") |>\n  mutate(regime = fct_relevel(regime_type, \"dominant-party\"),\n         ect = (ct-1)*100,\n         Coup = coup) |>\n  select(Coup, regime, ect, gdppc, violence, coup_dummy = pre_coups) |> \n  selection(Coup > 0 ~ regime + ect + gdppc + violence + coup_dummy,\n            Coup > 1 ~ regime + ect + gdppc + violence,\n            #method = \"2step\",\n            data = _) \n\nmodel_2_selection <- model_2\nmodel_2_selection$param$index$betaO <- model_2$param$index$betaS\nmodel_2_selection$param$index$betaS <- model_2$param$index$betaO\n\nstargazer(model_2_selection, model_2, model_1_selection, model_1,\n          #type = \"html\",\n          header = F,\n          dep.var.caption = \"\",\n          dep.var.labels = c(\"Model 1\", \"Model 2\"),\n          #dep.var.labels.include = T,\n          #multicolumn = T,\n          title = \"Sample Selection Model of Regime Types and Coups, 1950-2019\",\n          column.labels = c(\"Coup Attempts\", \"Coup Outcome\",\"Coup Attempts\", \"Coup Outcome\"),\n          intercept.bottom = F,\n          label = \"results\",\n          covariate.labels = c(\"Constant\", \"Regime: Democracy\", \"\\\\hspace{1.6cm}Military\", \"\\\\hspace{1.6cm}Monarchy\", \"\\\\hspace{1.6cm}Personalist\", \"Economic trend\", \"GDP per capita\", \"Political violence\", \"Previous coups (P)\", \"Yrs since coup (Y)\", \"Interaction term: P * Y\"),\n          summary.logical = F,\n          column.sep.width = \"7pt\",\n          font.size = \"small\"\n          )\n```\n\n\n\\begin{table}[!htbp] \\centering \n  \\caption{Sample Selection Model of Regime Types and Coups, 1950-2019} \n  \\label{results} \n\\small \n\\begin{tabular}{@{\\extracolsep{7pt}}lcccc} \n\\\\[-1.8ex]\\hline \n\\hline \\\\[-1.8ex] \n\\\\[-1.8ex] & \\multicolumn{2}{c}{Model 1} & \\multicolumn{2}{c}{Model 2} \\\\ \n & Coup Attempts & Coup Outcome & Coup Attempts & Coup Outcome \\\\ \n\\\\[-1.8ex] & (1) & (2) & (3) & (4)\\\\ \n\\hline \\\\[-1.8ex] \n Constant & $-$1.774$^{***}$ & $-$1.803$^{***}$ & $-$1.663$^{***}$ & $-$0.653 \\\\ \n  & (0.058) & (0.360) & (0.088) & (0.518) \\\\ \n  & & & & \\\\ \n Regime: Democracy & 0.056 & 0.068 & 0.043 & 0.042 \\\\ \n  & (0.072) & (0.121) & (0.075) & (0.192) \\\\ \n  & & & & \\\\ \n \\hspace{1.6cm}Military & 0.687$^{***}$ & 0.596$^{***}$ & 0.345$^{***}$ & 0.247 \\\\ \n  & (0.084) & (0.170) & (0.091) & (0.229) \\\\ \n  & & & & \\\\ \n \\hspace{1.6cm}Monarchy & 0.282$^{**}$ & 0.178 & 0.234$^{*}$ & 0.088 \\\\ \n  & (0.118) & (0.201) & (0.123) & (0.310) \\\\ \n  & & & & \\\\ \n \\hspace{1.6cm}Personalist & 0.319$^{***}$ & 0.128 & 0.134$^{*}$ & $-$0.145 \\\\ \n  & (0.075) & (0.170) & (0.080) & (0.205) \\\\ \n  & & & & \\\\ \n Economic trend & $-$0.015$^{***}$ & $-$0.004 & $-$0.014$^{***}$ & 0.009 \\\\ \n  & (0.002) & (0.007) & (0.002) & (0.008) \\\\ \n  & & & & \\\\ \n GDP per capita & $-$0.028$^{***}$ & $-$0.028$^{***}$ & $-$0.016$^{***}$ & $-$0.016 \\\\ \n  & (0.003) & (0.006) & (0.003) & (0.010) \\\\ \n  & & & & \\\\ \n Political violence & 0.033$^{**}$ & 0.033$^{*}$ & 0.038$^{***}$ & 0.025 \\\\ \n  & (0.013) & (0.020) & (0.013) & (0.031) \\\\ \n  & & & & \\\\ \n Previous coups (P) & 0.030$^{***}$ &  & 0.447$^{***}$ &  \\\\ \n  & (0.010) &  & (0.086) &  \\\\ \n  & & & & \\\\ \n Yrs since coup (Y) &  &  & $-$0.018$^{***}$ &  \\\\ \n  &  &  & (0.004) &  \\\\ \n  & & & & \\\\ \n Interaction term: P * Y &  &  & $-$0.013$^{***}$ &  \\\\ \n  &  &  & (0.005) &  \\\\ \n  & & & & \\\\ \n\\hline \\\\[-1.8ex] \nObservations & 9,606 & 9,606 & 9,606 & 9,606 \\\\ \nLog Likelihood & $-$1,663.646 & $-$1,663.646 & $-$1,598.603 & $-$1,598.603 \\\\ \n$\\rho$ & 0.898$^{***}$  (0.158) & 0.898$^{***}$  (0.158) & 0.386$^{*}$  (0.234) & 0.386$^{*}$  (0.234) \\\\ \n\\hline \n\\hline \\\\[-1.8ex] \n\\textit{Note:}  & \\multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\\\ \n\\end{tabular} \n\\end{table} \n\n\nThe double `probit` model with sample selection, estimated using the\n`sampleSelection` package [@sampleSelection-2] in R, provides valuable insights\ninto the factors influencing coup attempts and their outcomes across different\nregime types from 1950 to 2019 (Table \\ref{results}). We present two models that\ndiffer slightly in their treatment of previous coups: Model 1 incorporates the\nnumber of previous coups, while Model 2 utilizes the time elapsed since the last\ncoup.\n:::\n\n\\newpage\n\n#### The Selection Model: Coup Attempts\n\n\n::: {#tbl-mfx1 .cell tbl-cap='Average marginal effects of coup attempts (Selection of Model 1)'}\n\n```{.r .cell-code}\navg_comparisons(model_2) |> \n  select(1:3) |> \n  select(1:2, ame = estimate) |>\n  cbind(avg_comparisons(model_2, comparison = \"ratio\") |> select(3)) |> \n  mutate('ratio(%)' = round((estimate - 1) * 100, 2),\n         ame = round(ame, 3)) |> \n  select(-estimate) |>\n  mutate(term = case_when(term == \"coup_dummy\" ~ \"Previous coups\",\n                          term == \"ect\" ~ \"Economic trend\",\n                          term == \"gdppc\" ~ \"GDP per capita\",\n                          term == \"violence\" ~ \"Political violence\",\n                          str_detect(contrast, \"democracy\") ~ \"Regime: Democracy\",\n                          str_detect(contrast, \"military\") ~ \"Military\",\n                          str_detect(contrast, \"monarchy\") ~ \"Monarchy\",\n                          str_detect(contrast, \"personal\") ~ \"Personal\",\n                          TRUE ~ term\n                          )) |> \n  mutate(term = factor(term, levels = c(\n  \"Regime: Democracy\",\n  \"Military\",\n  \"Monarchy\",\n  \"Personal\",\n  \"Economic trend\",\n  \"GDP per capita\",\n  \"Political violence\",\n  \"Previous coups\"\n)),\ncontrast = str_replace(\n    contrast, \n    \"mean\\\\((.+?)\\\\) - mean\\\\((.+?)\\\\)\", \n    \"mean(\\\\1 - \\\\2)\"\n  )) |> \n  arrange(term) |> \n  clean_names(case = \"title\") |>\n  rename(AME = Ame) |> \n  gt() |> \n  cols_align(align = \"left\", columns = Term) |> \n  tab_style(\n    style = cell_text(indent = px(63)),\n    locations = cells_body(\n      columns = Term,\n      rows = 2:4\n    )\n  ) |> \n  tab_options(\n    table.width = pct(95),\n    # table.font.size = px(14),\n    column_labels.font.weight = \"bold\"\n    ) |> \n  fmt_number(\n    decimals = 3          # specify the number of decimal places\n  ) |> \n  tab_footnote(\n    footnote = \"AME: Average Marginal Effect\",\n    locations = cells_column_labels(columns = AME)\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hlklmanpob\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hlklmanpob table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hlklmanpob thead, #hlklmanpob tbody, #hlklmanpob tfoot, #hlklmanpob tr, #hlklmanpob td, #hlklmanpob th {\n  border-style: none;\n}\n\n#hlklmanpob p {\n  margin: 0;\n  padding: 0;\n}\n\n#hlklmanpob .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 95%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hlklmanpob .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hlklmanpob .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hlklmanpob .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hlklmanpob .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hlklmanpob .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hlklmanpob .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hlklmanpob .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hlklmanpob .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hlklmanpob .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hlklmanpob .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hlklmanpob .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hlklmanpob .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hlklmanpob .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hlklmanpob .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hlklmanpob .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hlklmanpob .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hlklmanpob .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hlklmanpob .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hlklmanpob .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hlklmanpob .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hlklmanpob .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hlklmanpob .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hlklmanpob .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hlklmanpob .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hlklmanpob .gt_left {\n  text-align: left;\n}\n\n#hlklmanpob .gt_center {\n  text-align: center;\n}\n\n#hlklmanpob .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hlklmanpob .gt_font_normal {\n  font-weight: normal;\n}\n\n#hlklmanpob .gt_font_bold {\n  font-weight: bold;\n}\n\n#hlklmanpob .gt_font_italic {\n  font-style: italic;\n}\n\n#hlklmanpob .gt_super {\n  font-size: 65%;\n}\n\n#hlklmanpob .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hlklmanpob .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hlklmanpob .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hlklmanpob .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hlklmanpob .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hlklmanpob .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hlklmanpob .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hlklmanpob .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hlklmanpob div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Term\">Term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Contrast\">Contrast</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"AME&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\">AME<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Ratio Percent\">Ratio Percent</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">Regime: Democracy</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(democracy - dominant-party)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.003</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">13.030</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\" style=\"text-indent: 63px;\">Military</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(military - dominant-party)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.070</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">277.730</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\" style=\"text-indent: 63px;\">Monarchy</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(monarchy - dominant-party)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.020</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">80.620</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\" style=\"text-indent: 63px;\">Personal</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(personal - dominant-party)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.024</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">93.980</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">Economic trend</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(+1)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">−0.001</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">−2.850</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">GDP per capita</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(+1)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">−0.002</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">−5.400</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">Political violence</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(+1)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.003</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">6.550</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">Previous coups</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(+1)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.002</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">5.930</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span> AME: Average Marginal Effect</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n#avg_predictions(model_2, variables = \"regime\")\n# slopes(model_2, newdata = \"mean\")\n# predictions(model_2, newdata = \"mean\") |>\n#   view()\n```\n:::\n\n\nIn the selection model (Column 1), military and personalist regimes exhibit\nsignificant positive coefficients at the 1% level, indicating a higher likelihood\nof experiencing coup attempts compared to dominant-party regimes. Control\nvariables also exhibit effects in expected directions. Stronger economic\nperformance, indicated by higher economic growth trends and GDP per capita\nlevels, correlates with a lower risk of coup attempts. This suggests that better\neconomic conditions and relatively higher living standards reduce incentives for\ncoups. Political violence shows a positive and significant effect on coup\nattempts, indicating that higher levels of instability increase the likelihood of\ncoups. The positive coefficient for the number of previous coups suggests a\n\"copycat\" effect from earlier incidents.\n\nWhile interpreting `probit` model results directly is not intuitive, @tbl-mfx1,\ngenerated using `marginaleffects` package [@marginaleffects], helps clarify the\nregime effects. The Average Marginal Effect (AME) column shows changes in\nprobability when a variable increases by one unit (for numeric variables) or\ncompared to a reference category (for categorical variables). For instance, the\nmilitary regime's marginal effect of 0.07 indicates that the probability of coup\nattempts in military regimes is 7 percentage points (pp) higher than in\ndominant-party regimes, ceteris paribus. For GDP per capita, the marginal effect\nof -0.002 suggests that a \\$1000 increase reduces the probability of coup\nattempts by 0.2 pp under average conditions.\n\nThe Ratio column displays the relative change in percent. While a 7 pp increase\nmight seem modest, it is substantial in context. Given that the average\nprobability of a coup attempt in dominant-party regimes is approximately 2.53%,\nthe 7 pp increase means military regimes are about 277.7% more likely to\nencounter coups than dominant-party regimes—a significant change. Similarly,\npersonalist regimes show a 2.4 pp higher probability, about 94% more likely\ncompared to dominant-party regimes. Monarchies display a positive effect similar\nto personalist regimes, reflecting that monarchies are essentially a subset of\npersonalist regimes with royal titles.\n\nControl variables, however, show weak effects in predicting coup attempts. None\nof their marginal effects reach 1 pp in probability, and all are less than 7% in\nratio. Given that the actual probability of a coup attempt is only 2% to 3%,\nthese small increases or decreases can be considered negligible.\n\nThese results align with our theoretical expectations regarding internal power\nstruggles within military juntas and succession vulnerabilities in personalist\nregimes, underscoring the importance of regime structure in understanding coup\nlikelihood.\n\nModel 2 employs years since the last coup instead of the number of previous\ncoups. Due to most countries not experiencing coups, an interaction term between\nprevious coups (as a binary variable indicating presence or absence of coups) and\nyears since the last coup is used. Generally, Model 2 shows results in the same\ndirection as Model 1, albeit with relatively lower coefficients (@tbl-mfx2).\n\n\n::: {#tbl-mfx2 .cell tbl-cap='Average marginal effects of coup attempts (Selection of Model 2)'}\n\n```{.r .cell-code}\navg_comparisons(model_1) |> \n  select(1:3) |> \n  select(1:2, ame = estimate) |>\n  cbind(avg_comparisons(model_1, comparison = \"ratio\") |> select(3)) |> \n  mutate('ratio(%)' = round((estimate - 1) * 100, 2),\n         ame = round(ame, 3)) |> \n  select(-estimate) |>\n  mutate(term = case_when(term == \"coup_dummy\" ~ \"Previous coups (P)\",\n                          term == \"time_since_last_coup\" ~ \"Yrs since coup (P)\" ,\n                          term == \"coup_dummy*time_since_last_coup\" ~ \"Interaction term: P * Y\",\n                          term == \"ect\" ~ \"Economic trend\",\n                          term == \"gdppc\" ~ \"GDP per capita\",\n                          term == \"violence\" ~ \"Political violence\",\n                          str_detect(contrast, \"democracy\") ~ \"Regime: Democracy\",\n                          str_detect(contrast, \"military\") ~ \"Military\",\n                          str_detect(contrast, \"monarchy\") ~ \"Monarchy\",\n                          str_detect(contrast, \"personal\") ~ \"Personal\",\n                          TRUE ~ term\n                          )) |> \n  mutate(term = factor(term, levels = c(\n  \"Regime: Democracy\",\n  \"Military\",\n  \"Monarchy\",\n  \"Personal\",\n  \"Economic trend\",\n  \"GDP per capita\",\n  \"Political violence\",\n  \"Previous coups (P)\",\n  \"Yrs since coup (Y)\",\n   \"Interaction term: P * Y\"\n)),\ncontrast = str_replace(\n    contrast, \n    \"mean\\\\((.+?)\\\\) - mean\\\\((.+?)\\\\)\", \n    \"mean(\\\\1 - \\\\2)\"\n  )) |> \n  arrange(term) |> \n  clean_names(case = \"title\") |>\n  rename(AME = Ame) |> \n  gt() |> \n  cols_align(align = \"left\", columns = Term) |> \n  tab_style(\n    style = cell_text(indent = px(63)),\n    locations = cells_body(\n      columns = Term,\n      rows = 2:4\n    )\n  ) |> \n  tab_options(\n    table.width = pct(95),\n    # table.font.size = px(14),\n    column_labels.font.weight = \"bold\"\n    ) |> \n  fmt_number(\n    decimals = 3          # specify the number of decimal places\n  ) |> \n  tab_footnote(\n    footnote = \"AME: Average Marginal Effect\",\n    locations = cells_column_labels(columns = AME)\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yzfxmnaiwk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yzfxmnaiwk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yzfxmnaiwk thead, #yzfxmnaiwk tbody, #yzfxmnaiwk tfoot, #yzfxmnaiwk tr, #yzfxmnaiwk td, #yzfxmnaiwk th {\n  border-style: none;\n}\n\n#yzfxmnaiwk p {\n  margin: 0;\n  padding: 0;\n}\n\n#yzfxmnaiwk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 95%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yzfxmnaiwk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yzfxmnaiwk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yzfxmnaiwk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yzfxmnaiwk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yzfxmnaiwk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yzfxmnaiwk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yzfxmnaiwk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yzfxmnaiwk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yzfxmnaiwk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yzfxmnaiwk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yzfxmnaiwk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yzfxmnaiwk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yzfxmnaiwk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yzfxmnaiwk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzfxmnaiwk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yzfxmnaiwk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yzfxmnaiwk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yzfxmnaiwk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzfxmnaiwk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yzfxmnaiwk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzfxmnaiwk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yzfxmnaiwk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzfxmnaiwk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yzfxmnaiwk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzfxmnaiwk .gt_left {\n  text-align: left;\n}\n\n#yzfxmnaiwk .gt_center {\n  text-align: center;\n}\n\n#yzfxmnaiwk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yzfxmnaiwk .gt_font_normal {\n  font-weight: normal;\n}\n\n#yzfxmnaiwk .gt_font_bold {\n  font-weight: bold;\n}\n\n#yzfxmnaiwk .gt_font_italic {\n  font-style: italic;\n}\n\n#yzfxmnaiwk .gt_super {\n  font-size: 65%;\n}\n\n#yzfxmnaiwk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yzfxmnaiwk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yzfxmnaiwk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yzfxmnaiwk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yzfxmnaiwk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yzfxmnaiwk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yzfxmnaiwk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yzfxmnaiwk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yzfxmnaiwk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Term\">Term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Contrast\">Contrast</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"AME&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\">AME<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Ratio Percent\">Ratio Percent</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">Regime: Democracy</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(democracy - dominant-party)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.003</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">8.930</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\" style=\"text-indent: 63px;\">Military</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(military - dominant-party)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.028</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">91.650</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\" style=\"text-indent: 63px;\">Monarchy</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(monarchy - dominant-party)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.018</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">57.040</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\" style=\"text-indent: 63px;\">Personal</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(personal - dominant-party)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.009</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">30.090</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">Economic trend</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(+1)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">−0.001</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">−2.530</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">GDP per capita</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(+1)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">−0.001</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">−2.890</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">Political violence</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(+1)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.003</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">7.330</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">Previous coups (P)</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(1 - 0)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">0.023</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">91.990</td></tr>\n    <tr><td headers=\"Term\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"Contrast\" class=\"gt_row gt_left\">mean(+1)</td>\n<td headers=\"AME\" class=\"gt_row gt_right\">−0.002</td>\n<td headers=\"Ratio Percent\" class=\"gt_row gt_right\">−5.050</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span> AME: Average Marginal Effect</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n#### The Outcome Model: Coup Success\n\nThe outcome model (Columns 2 and 4 in Table \\ref{results}) reveals determinants\nof coup success. Military regimes demonstrate a higher probability of coup\nsuccess compared to dominant-party regimes, aligning with expectations that\nmilitary regimes face higher coup risks due to their increased chances of\nsuccess. Personalist and monarchical regimes show slight positive effects on coup\nsuccess, but these effects are not statistically significant.\n\nControl variables exhibit different patterns in the outcome model compared to the\nselection model. Both GDP per capita and political violence maintain a weak\ninfluence, similar to their effects in the selection model. However, the economic\ntrend shows a less significant negative effect on coup success.\n\nThese results indicate that regime type remains a significant determinant of both\ncoup attempts and successes, even after controlling for other factors, strongly\nsupporting the proposed theoretical framework.\n\n\n\n\n\n#### Discussion\n\nThe $\\rho$ values of 0.898 in Model 1 and 0.386 in Model 2, significant at 1% and\n10% levels respectively, are crucial parameters in the sample selection model.\nThese values represent the correlation between the error terms of the selection\nequation (coup attempts) and the outcome equation (coup outcomes). A high and\nsignificant $\\rho$ suggests that unobserved factors influencing the likelihood of\na coup attempt are strongly correlated with those influencing the likelihood of a\nsuccessful coup. Practically, this indicates that the selection model is\nappropriate and that accounting for selection bias (i.e., the fact that only\ncoups with high chances of success will be attempted) is critical for obtaining\nunbiased estimates. The high $\\rho$ value indicates that the same underlying\nconditions that lead to a coup attempt also affect its success, underscoring the\nimportance of considering both stages in the analysis.\n\nThe results strongly support the choice of the sample selection model.\nSignificant coefficients with theoretically consistent directions suggest the\nmodel effectively captures key aspects of coup dynamics. Regimes with weaker\ninstitutional structures are more vulnerable to coup attempts, while better\neconomic conditions make coups less likely overall. The model effectively\naddresses the non-random nature of coup attempts by treating selection and\noutcome as separate processes.\n\nThe observed disparity between coup attempt rates and success rates across\nregimes points towards selection bias, further validating the use of the sample\nselection model. This model acknowledges that coups are not random events, but\nrather strategic actions undertaken when the odds appear favourable.\n\nIn summary, the double `probit` model with sample selection proves to be a\nwell-suited approach for this research. It provides robust insights into the\nfactors influencing both the likelihood of coup attempts and their success rates\nacross different regime types. The findings highlight the crucial role of regime\nstructure and the selective nature of coup attempts, supporting the theoretical\nframework and empirical strategy employed in this study.\n\n#### Implications\n\nThe finding that regime type plays a crucial role in determining coup attempts,\nwhile not surprising, has received relatively little attention as a primary\nresearch focus. However, even if this result is acknowledged more widely by\nacademics or politicians, it is unlikely to be implemented as a coup-proofing\nstrategy.\n\nFirstly, regime type is not a policy that can be easily altered. It is largely\nestablished during the formation of the regime, resulting from power struggles\nwithin the ruling group. As previously discussed, there are specific reasons why\none regime type is chosen over another. Regimes established through irregular\nmeans are unlikely to transition to a more stable regime type peacefully and\nsmoothly.\n\nSecondly, even if a particular regime type is more effective at preventing coups,\nthis may hold little significance for those in power. Autocratic leaders often\nprioritize personal power and survival over long-term regime stability, as more\nstable systems may not benefit them personally. Democratic norms and constraints\nmay be seen as obstacles to their goals rather than as safeguards against\ninstability.\n\nWhile this conclusion might seem discouraging, it is not entirely pessimistic.\nThe power game involves not only the top leaders but also the majority of other\nelites. While top leaders may prioritize personal gains, other elites, including\nthe military, economic elites, and civil society, have a vested interest in a\nstable political environment. Therefore, it is possible to reach a consensus for\na political system that is less susceptible to coups, potentially benefiting a\nbroader spectrum of society.\n\n### Conclusion\n\nMotivated by the lack of consensus despite numerous empirical studies on the\ndeterminants of coups, this study introduces a novel approach that prioritizes\ndeterminants based on their impact on coup success. By analysing coup success\nrates, the study hypothesizes that the expected outcomes of coups are critical\ndeterminants of their occurrence. Utilizing a double `probit` model with sample\nselection, I investigate and confirm the relationship between regime types and\ncoup attempts.\n\nThe findings suggest that regime type plays a significant role in the likelihood\nof coup attempts. Military and personalist regimes, characterized by weaker\ninstitutional frameworks and higher vulnerability during power transitions, are\nmore susceptible to coups. This underscores the importance of supporting\ninitiatives that strengthen constitutional institutions within these regimes.\n\nThe research also finds that stronger economic performance is associated with a\nlower risk of coups, suggesting that policies promoting economic development can\nbe effective in reducing coup risk.\n\nThe study shows that the most efficient coup-proofing strategies involve the\nestablishment of strong institutions. In contrast, purges, random shifting of\nmilitary officers, or increased military expenditures are less effective.\nHowever, few autocratic leaders, particularly dictators or military juntas, are\nwilling to institutionalize their regimes, as such reforms may constrain their\npower or shorten their terms. While institutions benefit the regime, they do not\nnecessarily benefit the leaders themselves.\n\nFuture research could explore specific institutional reforms that are most\neffective in improving stability across different regimes.\n\n## Autocoups: Conceptual Clarification and Analysis of Power Extensions by Incumbent Leaders\n\n## Power Acquisition and Leadership Survival: A Comparative Analysis of Coup-Entry and Autocoup Leaders\n\n## Conclusion\n\n### Main Findings\n\nThis study delves into the dynamics and implications of irregular power\ntransitions, focusing on coups and autocoups. The findings illuminate the complex\ninterplay between incumbents and challengers fighting for power.\n\nFirstly, our analysis reveals that the expected success rate of a coup attempt\nsignificantly influences its likelihood. This success rate is heavily influenced\nby the balance of power between the incumbent regime and challengers, which is\nlargely determined by regime type. We find that military regimes, although with\nmore control over their own military forces, face a higher risk of coups compared\nto dominant-party regimes.\n\nSecondly, the study introduces a redefined concept: the autocoup. Defined as an\nincumbent leader's refusal to relinquish power as mandated, this research\ndistinguishes autocoups from broader terms like self-coups. Based on this\ndefinition, we present the first publicly available dataset of autocoup events\nfrom 1945 to 2022, encompassing 110 attempts and 87 successful autocoups. Case\nstudies and empirical analyses demonstrate the dataset's utility for quantitative\nresearch, providing a robust foundation for further analysis on autocoups.\n\nThirdly, employing survival analysis techniques, the study finds clear\ndifferences in leader longevity between those who come to power through coups and\nthose who extend their rule through autocoups. The results indicate that\ncoup-installed leaders face a significantly higher risk of removal compared to\nautocoup leaders who manipulate the system to extend their rule.\n\n### Policy Implications\n\nThe findings of this study offer valuable insights for policy-makers concerned\nwith promoting and protecting global democracy, which has faced increasing\nchallenges despite a general post-WWII trend towards democratization. Notably,\nthe \"third wave\" of democratization [@huntington1991democratization] witnessed a\nsurge in democratic transitions in the late 20th century. Since the Cold War's\nend, democratic nations have outnumbered non-democratic ones (@fig-democracy)\nwith the gap widening.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nREIGN |>\n  filter(year > 1945 & year < 2021) |> \n  mutate(democracy = case_when(\n    gwf_regimetype %in% c(\"parliamentary\", \"presidential\") ~ \"Democracy\",\n    .default = \"Non-democracy\")) |> \n  summarise(Count = n(), \n            .by = c(year, democracy)) |> \n  #view()\n  ggplot(aes(year, Count, color = democracy)) +\n  geom_point() +\n  labs(color = 'Regime type',\n       x = \"Years: 1945 ~ 2020\",\n       y = \"No. of Countries\") +\n  theme(legend.position = \"top\") +\n  annotate(\"text\",\n    label = \"Data source: REIGN (Regime data)\",\n    x = 2010,\n    y = 30,\n    fontface = \"italic\",\n    size = 3\n    )\n```\n\n::: {.cell-output-display}\n![Comparison of the number of democratic and non-democratic countries (1945-2020)](coups_and_autocoups_files/figure-html/fig-democracy-1.png){#fig-democracy fig-align='center' width=672}\n:::\n:::\n\n\nHowever, a \"democratic recession\" has emerged in recent years [@diamond2008].\nFreedom House reports an 18th consecutive year of global freedom decline in 2023\n[@freedomhouse2024freedom]. While few countries have completely regressed to\nautocracy, the average global democracy level has fallen back to pre-2000 levels.\nNotably, democratic backsliding often occurs within regimes, with democracies\nbecoming less liberal and autocracies becoming less competitive [@mechkova2017].\n\nThis research highlights irregular power transitions as a significant factor in\ndemocratic backsliding within regimes. These transitions, often coups or\nautocoups, violate democratic norms and disrupt the path towards stable\ndemocracies. Leaders who gain power through irregular means often resort to\nundemocratic tactics to maintain control, creating a vicious cycle of eroding\ndemocratic institutions.\n\nOur findings suggest that the shorter lifespans and potentially severe\nconsequences associated with coups may deter potential coup leaders. Conversely,\nautocoups appear to be a more tempting option for power-hungry leaders due to\ntheir higher success rates, seemingly moderate consequences, and extended leader\ntenure after the autocoup. This trend may explain the decline in classic coups\nsince the 1990s alongside the rise of autocoups [@bermeo2016].\n\n### Limitations and directions for future research\n\nThis study offers a novel framework for analysing irregular power transitions,\nbut some limitations require further exploration:\n\n-   **Data refinement:** Defining and classifying autocoups is a new approach.\n    Future research should validate this classification system through additional\n    studies and expert evaluations.\n\n-   **Data harmonization:** The current analysis faces challenges due to\n    mismatched units (country-year vs. leader) between coup and autocoup\n    datasets. Future efforts should explore data harmonization techniques for\n    more robust comparisons.\n\n-   **Democratic backsliding:** While this study establishes a connection between\n    irregular power transitions and democratic backsliding, further empirical\n    evidence is needed to solidify this link.\n\nSeveral avenues exist for future research:\n\n-   **Terminology and data collection:** Refining the \"autocoup\" concept and\n    achieving wider recognition will facilitate more accurate and comprehensive\n    data collection.\n\n-   **Dataset expansion:** Expanding the autocoup dataset with more cases and\n    integrating it with data on other irregular leadership transitions can\n    provide a more holistic view of political survival after these events.\n\n-   **Power dynamics and long-term impacts:** Utilizing this dataset, future\n    studies can delve deeper into power dynamics at play and explore the\n    long-term consequences of irregular transitions on political systems,\n    particularly regarding democratic backsliding, breakdown, and personalization\n    of power.\n\nIn conclusion, this study sheds light on the dynamics of irregular power\ntransitions, specifically focusing on coups and autocoups. By redefining\nautocoups, classifying the dataset, analysing determinants, and comparing leader\nlongevity, we establish a framework for understanding irregular transitions and\nleader survival. This work contributes to a deeper understanding of democratic\nresilience and political stability. Future research can build upon this\nfoundation by conducting further empirical analyses based on the novel autocoup\ndataset and continuing to refine the framework.\n\n\n\n\n\n[^1]: According to the Archigos dataset, \"Removed by Military, without Foreign\n    Support\" and \"Removed by Other Government Actors, without Foreign Support\" in\n    the variable `exitcode` are classified as coups.\n\n[^2]: According to the Archigos dataset, \"Removed by Military, without Foreign\n    Support\" and \"Removed by Other Government Actors, without Foreign Support\" in\n    the variable `exitcode` are classified as coups.\n\n[^3]: The definitions and concepts of power expansion and power extension can be\n    vague. In this study, we define power expansion as an incumbent acquiring\n    additional authority from other state apparatuses, whereas power extension\n    refers to an incumbent prolonging their tenure beyond the designated term in\n    office.\n\n[^4]: According to the Archigos dataset, \"Removed by Military, without Foreign\n    Support\" and \"Removed by Other Government Actors, without Foreign Support\" in\n    the variable `exitcode` are classified as coups.\n\n[^5]: The definitions and concepts of power expansion and power extension can be\n    vague. In this study, we define power expansion as an incumbent acquiring\n    additional authority from other state apparatuses, whereas power extension\n    refers to an incumbent prolonging their tenure beyond the designated term in\n    office.\n",
    "supporting": [
      "coups_and_autocoups_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}