{
  "hash": "935326c23f9461be0e30bdd751255fba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Leadership Transitions and Survival:\\n Coups, Autocoups, and Power Dynamics\"\n\nauthor:\n  - name: Zhu Qi\n    affiliations: University of Essex\n    email: qz21485@essex.ac.uk\n  \nformat:\n  aps-html: default\n  aps-pdf: \n    documentclass: report\n    keep-tex: true\n    colorlinks: true\n    urlcolor: blue\n    link-citations: true\n    linkcolor: blue\n    fig-asp: 0.618\n    number-sections: true\n    shift-heading-level-by: -1\n    toc: true\n    toc-title: Contents\n    lof: true\n    lot: true\n    crossref: \n      lof-title: Figures\n      lot-title: Tables\n    linestretch: 1.618\n    indent: true\n    fontsize: 12pt\n    mainfont: \"Times New Roman\"\n    sansfont: \"Arial\"\n    monofont: \"Courier New\"\n    #latex-engine: pdflatex\n    pdf-engine: xelatex\n    geometry:\n      # - showframe\n      - top = 3cm\n      - bottom = 3cm\n      - left = 3cm\n      - right = 2.7cm\n    header-includes:\n      - \\usepackage{sectsty}\n      - \\chapterfont{\\centering}\n      - \\usepackage{lscape}\n      - \\newcommand{\\blandscape}{\\begin{landscape}}\n      - \\newcommand{\\elandscape}{\\end{landscape}}\n      \n  docx: default\n    \ncategories: [Article, Coups, Autocoups, Leadership Survival]\nbibliography: references.bib\n#include-before-body: title.tex\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n\n\n\n\n## Acknowledgements {.unnumbered}\n\nThe completion of this thesis has been a significant journey, filled with hard\nwork, learning, and moments of joy. Throughout this time, I have received support\nand encouragement from many individuals, without whom this dissertation would not\nhave been possible.\n\nFirst and foremost, I would like to express my deepest gratitude to my great\nsupervisor, Professor Kristian Skrede Gleditsch, for his invaluable guidance,\nunwavering support, and insightful feedback throughout this journey. His\nexpertise and encouragement have been instrumental in shaping this dissertation.\nI would also like to extend my heartfelt thanks to the chair of my board panel,\nProfessor Han Dorussen, for his continuous support and constructive criticism,\nwhich have significantly enhanced the quality of my research.\n\nI am profoundly grateful for the comments, advice, and suggestions from several\nesteemed scholars who have contributed to this work. Dr. Brian J Phillips, Dr.\nPrabin Khadka, and Dr. Winnie Xia, their expertise and thoughtful input have been\ngreatly appreciated and have enriched this dissertation.\n\nFinally, I want to thank my family for their unwavering support and love. To my\nbeloved wife, Ji Zhi, who has been my rock throughout this journey, and to my\ndear daughter, Siyan, and son, Sisheng, who have been my source of joy and\nmotivation. I am deeply thankful to my father for his enduring support, and to\nthe memory of my late mother, whose love and guidance continue to inspire me.\n\nAll errors and faults are my own.\n\n## Abstract {.unnumbered}\n\nThis dissertation examines the dynamics of irregular power transitions,\nparticularly coups and autocoups, and their influence on leader survival. It\nhighlights the critical role of power dynamics, shaped by **regime type**, in\ndetermining coup success rates and attempt frequency. Utilizing a **double probit\nmodel with sample selection**, the study reveals that expected coup success\nsignificantly influences attempts, with military regimes facing a heightened\nvulnerability due to their power structure.\n\nWhile often understudied, autocoups are shown to have a substantial impact on\ndemocratic trends. This research introduces a refined definition of autocoups\nalongside a novel dataset encompassing events from 1945 to 2022, enabling a more\nrobust quantitative analysis.\n\nEmploying survival analysis, the study compares the longevity of leaders who rise\nto power through coups versus autocoups. The findings demonstrate that\ncoup-installed leaders face a significantly shorter tenure and higher risk of\nremoval. This contrasts with autocoup leaders who manipulate the system to extend\ntheir rule, suggesting the potential for autocoups to incentivize power grabs and\ncontribute to democratic backsliding.\n\nThis work contributes significantly to the political science literature by:\n\n-   Defining key concepts: It establishes a clear definition of autocoups, a\n    previously understudied phenomenon.\n\n-   Introducing a novel dataset: This dataset enables researchers to conduct more\n    comprehensive quantitative analyses of autocoups.\n\n-   Establishing a general framework: The framework provides a comparative\n    approach to studying the dynamics of irregular power transitions and their\n    impact on democratic stability.\n\n**keywords:** *Coups, Autocoups, Power transitions, Leadership Survival*\n\n## Introduction\n\n### Research question\n\n\n\n\n\n\n\n\n\n\n\nIrregular power transitions, marked by a disregard for constitutional procedures,\nare a critical area of study in political science. They not only disrupt\nestablished rules but often require unconstitutional tactics to secure power.\nFurthermore, these transitions can inspire copycat behaviour among other\nambitious leaders.\n\nDespite their central role in political science and the extensive research\nconducted on irregular power transitions, a long-standing question continues to\nintrigue political scientists: ***Why are some leaders ousted before their terms\nexpire, while others complete their full terms or even overstay beyond their\noriginally mandated limits?*** In other words, why do some leaders survive for\ndecades while others last for only years, months, or even days? This dissertation\nfocuses on this question and seeks to provide a comprehensive analysis, dedicated\nto understanding how leaders come to power through unconstitutional means and\nwhat factors determine the duration of a leader's rule following an irregular\nascent.\n\n### Analyses on coups and autocoups in a general framework\n\nWhen discussing irregular power transitions, the concepts that often come to mind\nare irregular entries or exits, such as coups, assassinations, rebellions,\nprotests, and foreign interventions. Among these methods, coups hold a prominent\nposition due to their frequent occurrence. According to the Archigos dataset\n[@goemans2009], from 1945 to 2015, there were approximately 145 instances of\nirregular leader exits, with coups[^1] accounting for more than half (79\nleaders). The often-cited Global Instances of Coups (GIC)[^2] dataset\n[@powell2011] records even more leaders (245 cases) removed by coups from 1950 to\n2023.\n\nGiven their prevalence and substantial influence on political systems, coups have\nbeen extensively studied, particularly since 2000 [@thyne2019]. Consequently, the\nconcept of a coup is comparatively clear and widely accepted in academic circles.\nMany scholars, including this study, follow the definition by @powell2011, which\ndescribes coups as \"illegal and overt attempts by the military or other elites\nwithin the state apparatus to unseat the sitting executive... \\[a coup is\nsuccessful\\] if the perpetrators seize and hold power for at least seven days\"\n(P. 252). Although debates persist, two elements are clear: first, the\nperpetrators are elites within the ruling group, and the victims of coups are\nincumbent executive leaders. Second, the strategy or aim of a coup involves\ncompletely removing the incumbents, not merely seizing part of their power or\nforcing them to concede on specific policies. Beyond defining coups, several\ndatasets have been developed for quantitative analyses, such as the Global\nInstances of Coups [@powell2011], the Cline Centre Coup d’État Project Dataset\n[@peyton2024], and the Colpus Dataset [@chin2021]. These datasets are\nwell-developed and frequently used in political science research.\n\nHowever, irregular power transitions are not limited to irregular entries and\nexits but should also include irregular \"overstays.\" Using illegal means to\noverthrow an incumbent leader before their term expires is undoubtedly an\nirregular power transition. Similarly, an incumbent using illegitimate means to\nextend their term beyond term limits is also an irregular power transition.\n\nAlthough academic attention to irregular retention of power has increased since\nthe 1990s, especially after Peru’s President Alberto Fujimori's self-coup in\n1992, it remains comparatively understudied and has several shortcomings. First,\nthere is no universally accepted terminology for this \"overstaying in power\" type\nof irregular power transition, unlike the clear term \"coup.\" Consequently,\nvarious terms such as self-coup, autogolpe, and executive coup are used by\ndifferent scholars. This dissertation will use 'autocoup' to refer to this type\nof irregular power transition, which will be thoroughly discussed in Chapter 3.\nSecond, there is no consensus on the definition of an autocoup. Existing\ndefinitions remain vague, often conflating power expansions and power\nextensions[^3]. For example, @cameron1998a defines an autogolpe as a temporary\nsuspension of the constitution and dissolution of Congress by the executive, who\nthen rules by decree. This definition focuses on power expansion instead of power\nextension, leading to conceptual confusion and misalignment with the definition\nof a classic coup. Third, a consensus autocoup dataset is lacking. While several\nrelated datasets exist, as discussed by @baturo2022 in coding their Incumbent\nTakeover dataset, the terminologies, definitions, and coverage years vary,\nlacking wide acknowledgement and extensive academic exploration. In summary,\nautocoup has not been analysed in a comparative manner connected with coups.\n\nAnalysing coups and autocoups separately is less problematic. However, from a\ncomprehensive framework perspective on irregular power transitions and leader\nsurvival, coups and autocoups should be, and can be, analysed within the same\nframework. Both coup and autocoup significantly influence democratic backsliding\nand are the most frequent means of irregular power transition. Furthermore, as\nboth are called \"coups,\" classic coups and autocoups are very similar since a\ncoup is launched to replace the current leader, while an autocoup is staged to\nreplace the future leader.\n\n### Academic Contributions\n\nThis study addresses a critical gap in the literature by offering a comprehensive\nframework for analysing both coups and autocoups, which are the most common forms\nof irregular power transitions. While existing research often examines these\ntopics separately with varying terminologies, definitions, methods, and datasets,\nthis dissertation integrates these elements to provide a unified perspective on\nirregular power transitions and leader survival.\n\nOur contributions are threefold:\n\n-   **Emphasis on power dynamics and regime types**: We highlight the significant\n    role of power dynamics, particularly the influence of regime types, in\n    determining the success and frequency of coup attempts. Our analysis\n    underscores how the expected chances of coup success motivate such attempts,\n    with military regimes being notably susceptible.\n\n-   **Refined definition and novel dataset for autocoups:** We introduce a\n    refined definition of autocoups and develop a novel dataset covering events\n    from 1945 to 2022. This enables a comparative analysis with classic coups,\n    providing clearer insights into the nature and impact of autocoups on\n    political systems.\n\n-   **Survival analysis of leaders from different entry modes:** By applying\n    survival analysis to existing coup data and our new autocoup dataset, we\n    demonstrate how different modes of entry into power significantly affect\n    leader survival. Our findings reveal that leaders who come to power through\n    coups typically have shorter tenures and face higher removal risks compared\n    to those who extend their rule through autocoups.\n\nOur analysis of irregular power transitions is particularly relevant to\nunderstanding democratic backsliding. These transitions violate democratic norms\nand disrupt the path towards stable democracy. Leaders who gain power through\nirregular means often employ undemocratic tactics, such as suppressing\nopposition, to consolidate their illegitimate hold on power. This creates a\nvicious cycle where the erosion of democratic institutions is both a cause and\nconsequence of efforts to maintain power.\n\n### Overview of the thesis\n\nThis study is structured into three main chapters beyond the introduction, each\naddressing key aspects of irregular power transitions and their implications for\npolitical stability and democratic processes.\n\n**Chapter 2** examines the determinants of classic coup attempts. While extensive\nresearch exists on coups, most studies focus on observable factors before coups,\nsuch as economic performance, political stability, previous coups, and\ncoup-proofing strategies. This chapter, however, emphasizes the less observable\nbut crucial factor of expected chances of coup success, which have been often\noverlooked. Utilizing the double probit model with sample selection, the analysis\nreveals that expected success rates significantly influence coup attempts. These\nsuccess rates are primarily shaped by the balance of power between incumbents and\nchallengers, which is largely determined by regime type. The findings indicate\nthat military regimes face a much higher risk of coups compared to dominant-party\nregimes.\n\n**Chapter 3** focuses on the concept of autocoups, specifically on power\nextensions by incumbent leaders. It distinguishes autocoups from broader concepts\nlike self-coups or executive coups by redefining them as instances where\nincumbent leaders refuse to transition power as mandated, thereby overstaying in\noffice. Based on this refined definition, a novel dataset of autocoup events from\n1945 to 2022 is introduced, encompassing 110 attempts and 87 successes. The\nchapter includes case studies and empirical analyses that demonstrate the utility\nof this dataset for quantitative research, providing a basis for empirical\nanalysis on autocoups.\n\n**Chapter 4** investigates how the method of power acquisition impacts the\nlongevity of leaders who come to power through coups versus those who extend\ntheir rule through autocoups. The hypothesis is that the method of accession\nsignificantly affects leader tenure. Using the Cox proportional hazards model and\na time-dependent Cox model, the chapter provides evidence of differing survival\ntimes between these two types of leaders. The results indicate that leaders who\ncome to power through coups face a significantly higher risk of removal compared\nto those who extend their rule through autocoups. This finding highlights the\nimplications for political stability and democratic processes, suggesting that\nthe relatively low cost and high returns of autocoups could incentivize\nincumbents to seize power in this manner, potentially leading to democratic\nbacksliding and the personalization of power.\n\nIn **Chapter 5**, the study concludes by summarizing the main findings,\ndiscussing policy implications, and acknowledging the limitations of the\nresearch. It also outlines directions for future research, emphasizing the need\nfor further exploration of irregular power transitions, particularly coups and\nautocoups.\n\n## Power Dynamics and Coup Attempts: A Selection Mechanism Analysis\n\n### Introduction\n\n\n\n\n\n\n\n\n\n\n\nCoups, defined as \"illegal and overt attempts by the military or other elites\nwithin the state apparatus to unseat the sitting executive\" [@powell2011, P.252],\noccur with varying frequency across countries, with some experiencing them more\noften than others. According to GIC dataset, Latin American countries such as\nBolivia witnessed 23 coups\nbetween 1950 and 1984, while Argentina experienced\n20 during a similar time\nframe. However, Mexico's authoritarian period from 1917 to 2000 saw no coups at\nall. In Africa, Sudan endured 17\ncoups between 1955 and 2023, whereas South Africa has not experienced any coup\nsince 1950. Similar patterns are observed in the Middle East and South Asia.\n\nThe varying frequency of coup attempts has captivated political scientists for\ndecades, leading to extensive research on the subject. As highlighted by\n@gassebner2016, despite approximately one hundred potential determinants of coups\nbeing suggested, no consensus has been reached. In an effort to address this\nissue, they have tested 66 factors proposed in previous literature using three\nmillion model permutations in an extreme bounds analysis (ibid.).\n\nExamining previous research, which has tested around 100 variables as potential\ndeterminants of coups, raises an important question beyond simply understanding\nwhy coups are more frequent in some countries than others. The critical question\nis: Can we establish a framework to help scholars focus on the most relevant\nfactors of coups, rather than sifting through over 100 variables without reaching\na consensus?\n\nReviewing previously proposed variables of coups, it is evident that all focus on\npre-coup conditions, with no consideration given to post-coup factors. This means\nmore attention is paid to factors observable before a coup, such as military\nforce or spending, economic performance, political stability, and previous coups.\n\n\n\n\n\n::: {#tbl-coups .cell tbl-cap='Top 10 countries with the most coup attempts'}\n::: {.cell-output-display}\n\\begingroup\n\\setlength\\LTleft{0.05\\linewidth}\n\\setlength\\LTright{0.05\\linewidth}\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\setlength{\\LTpost}{0mm}\n\\begin{longtable}{@{\\extracolsep{\\fill}}lccr}\n\\toprule\nCountry & Coup Attempted & Coup Succeeded & Success Rate \\\\ \n\\midrule\\addlinespace[2.5pt]\nBolivia & 23 & 11 & 47.8\\% \\\\ \nArgentina & 20 & 7 & 35.0\\% \\\\ \nSudan & 17 & 6 & 35.3\\% \\\\ \nHaiti & 13 & 9 & 69.2\\% \\\\ \nVenezuela & 13 & 0 & 0.0\\% \\\\ \nIraq & 12 & 4 & 33.3\\% \\\\ \nSyria & 12 & 8 & 66.7\\% \\\\ \nThailand & 12 & 8 & 66.7\\% \\\\ \nEcuador & 11 & 5 & 45.5\\% \\\\ \nBurundi & 11 & 5 & 45.5\\% \\\\ \nGuatemala & 10 & 5 & 50.0\\% \\\\ \nTotal & 491 & 245 & 49.9\\% \\\\ \n\\bottomrule\n\\end{longtable}\n\\begin{minipage}{\\linewidth}\n\\emph{Source: GIC dataset}\\\\\n\\end{minipage}\n\\endgroup\n\n:::\n:::\n\n\n\n\n\nHowever, coups are high-stakes gambles with an all-or-nothing nature. Due to its\nillegality, the consequences of a failed coup can be severe, with perpetrators\nrisking imprisonment, exile, or even death. In some instances, repercussions\nextend to their families, which means coup plotters would not take the risk\nwithout some assurance of success.\n\nHistorical coup attempts and their success rates provide valuable hints about\ncoup plotters' decision-making processes. Despite the significant risks\nassociated with coups, as shown in @tbl-coups, there have been 491 coups\nworldwide since 1950. Importantly, about half of these coups have been\nsuccessful. At first glance, coups appear to be a high-success-rate political\nventure. However, compared to over 12,000 country-years since 1950, the\noccurrence of 491 coups is relatively rare, accounting for only about 4%\n(GIC).\n\nThe low occurrence rate and high success rate clearly indicate that the\ninitiation of coups is highly selective. In other words, the likelihood of a coup\noccurring depends greatly on its probability of success. However, the probability\nof success is not a factor that can be observed before a coup, at least not to\noutsiders and researchers, but coup plotters surely have more information on the\npossible outcome of coups.\n\nSince coup plotters meticulously assess potential outcomes before staging a coup,\ncoup researchers should also analyse what factors might affect the outcome of\ncoups. Otherwise, we ran the risk of selection bias. When considering the factors\nthat most affect the outcomes of coups, the current literature predominantly\nidentifies military power as the decisive factor in the success of coups.\nUltimately, military power is determined by the power structure within the\nregime.\n\nUnlike coup plotters, who have a clearer understanding of power structures and\ndynamics, including their supporters, followers, bystanders, and opponents,\nresearchers are not able to accurately observe this information. However, we can\nanalyse the most relevant factors which determine the balance of power and are\nobservable to us. This leads us to **regime type**, which reflects the\ndistribution of power within a government, encompassing who controls the\nmilitary, sets policy, and appoints officials. Since coup plotters consider the\nbalance of power within the regime before acting, this study argues that regime\ntype plays a crucial role in shaping coup attempts. Analysing which regime types\nare more susceptible to coups can offer valuable insights.\n\nWe employ a **double probit model with sample selection** to address the\nselection bias. This model allows us to analyze both the factors influencing coup\nsuccess and the factors related to the decision to initiate a coup attempt in the\nfirst place.\n\nThis study contributes to the literature in two key ways. First, it emphasizes\nthe importance of focusing on expected success rates as a driver of coup\nattempts, offering a more targeted approach compared to past studies. Second, it\nhighlights the significance of regime type as a factor influencing coup\nlikelihood, even when researchers lack perfect knowledge of a regime's internal\npower dynamics.\n\nThe subsequent section (Section 2) explores the dynamics of coup attempts and\ntheir outcomes. Section 3 delves into the research design, outlining the\nmethodology and variables used in the analysis. Section 4 presents and discusses\nthe empirical findings. Finally, Section 5 concludes the chapter by summarizing\nthe key insights and their implications.\n\n### Dynamics of coup attempts and outcomes\n\nCoup attempts are driven by a complex interplay of factors, including motivations\n(**disposition**) and the resources and opportunities available to succeed\n(**capability**).\n\n#### Motivations for coups\n\nThis section focuses on the motivations that compel challengers to undertake\ncoups. We can categorize coup motivations into three main types:\n\n**Personal Ambition:** Personal ambition is a significant motivator for the\nmajority of coup plotters, driven by the allure of absolute power, prestige, and\nwealth. The prospect of seizing absolute power provides an unparalleled\nopportunity to shape national policies, control resources, and make significant\ndecisions without constraints. The pursuit of prestige and recognition, along\nwith the potential for immense economic gain and wealth, further incentivizes\nindividuals. Additionally, the desire to leave a lasting legacy and make a\nhistorical impact can compel individuals to undertake the risky venture of\nstaging a coup.\n\n**Purported National Interest:** Sometimes coups are justified as necessary\ninterventions to address national crises, uphold the constitution, or facilitate\na transition to democracy. While the motivations behind such claims require\nscrutiny, genuine examples do exist. For instance, the 2010 coup in Niger ousted\nPresident Tandja, who attempted an unconstitutional third term by dissolving the\nopposing court and calling a self-serving referendum [@ginsburg2019].\n\n**Self-Preservation:** In some cases, coups serve as pre-emptive strikes against\nperceived threats. Coup leaders might not necessarily seek power, but rather fear\nelimination or political persecution by the incumbent regime. An example is Idi\nAmin's 1971 coup against Ugandan President Obote, who was attempting to remove\nAmin from his military command position [@sudduth2017].\n\nThese motivations are often most prevalent in autocratic regimes, where\njustifications under the guise of national interest or self-preservation can be\nused to mask personal agendas. Stable democracies rarely face the same level of\nconstitutional crises or political persecution that might necessitate a coup.\nHowever, new established democracies can be vulnerable to instability, economic\ndownturns, and democratic backsliding, creating opportunities for coup plotters\nto exploit these weaknesses and justify their actions.\n\nDespite the potential motivations outlined above, coups remain relatively\nuncommon, occurring in only about 4% of country-years since 1950. The main reason\nis that coup perpetrators face inherent disadvantages compared to incumbent\nleaders, highlighting the importance of capability. Even the most motivated\nplotters need the resources and opportunities to succeed. The next section will\nexplore the concept of capability in greater detail.\n\n#### Capability for coups\n\nFor coup plotters, the decision to act hinges not only on their motivations but\nalso on a calculated assessment of their chances of success. Several factors can\ninfluence this threshold:\n\n-   **Military Strength**: A clear advantage in military capabilities compared to\n    the incumbent regime significantly increases the odds of a successful coup.\n\n-   **Internal Divisions within the Regime**: Existing fractures within the\n    government's power structure can present opportunities for coup plotters to\n    exploit weaknesses and gain support from disgruntled factions.\n\n-   **Public Support**: Widespread discontent with the incumbent regime,\n    especially within the military or key sectors of society, can create an\n    environment ripe for a successful coup.\n\n-   **Foreign Backing**: External support from powerful nations can provide\n    resources, legitimacy, and even direct military intervention to tip the\n    scales in favour of the coup plotters.\n\nThe high success rate of coups since 1950, as shown in @tbl-coups, might suggest\nthat coups are not particularly difficult to succeed. However, it is important to\nconsider selection bias. We only observe attempted coups, not the numerous\ndispositions and conspiracies that never came to light. Analysing launched coup\ndata alone can be misleading.\n\nTo gain a more comprehensive understanding of coup attempts and their likelihood,\nwe need to move beyond historical data and employ a theoretical framework that\naccounts for selection bias. This framework will allow us to analyze the factors\ninfluencing both the success of coups and the decision to attempt a coup in the\nfirst place. The next section will delve into such a framework and its\nimplications for our understanding of coup attempts.\n\n#### Framework of coup success\n\nAn oft-cited framework [@gassebner2016; @aidt2019] provides a structured approach\nto assess the disposition and capability of coup attempts by evaluating the\nanticipated benefits for coup plotters. The expected pay-off of coups can be\nrepresented by the equation:\n\n$$\n\\begin{aligned}\nE(U) = p \\times B + (1 - p) \\times (-C)\n\\end{aligned}\n$$ {#eq-eq1}\n\nHere, $\\mathbf B$ represents the return of a successful coup, $\\mathbf C$\nsignifies the cost of a failed coup, and $p$ represents the probability of coup\nsuccess. The condition for staging a coup is when the expected benefit is\npositive, meaning that the expected pay-off is greater than 0. Rearranging the\nequation, we get:\n\n$$\n\\begin{aligned}\np \\times B > (1 - p) \\times C\n\\end{aligned}\n$$ {#eq-eq2}\n\n@eq-eq2 implies that for @eq-eq1 to hold, the expected benefits earned from\nsuccessful coups must outweigh the expected cost of failed coups.\n\nWhile seemingly clear, the equation faces practical challenges. Quantifying\n$\\mathbf B$ (the value of a successful coup) and $\\mathbf C$ (the cost of\nfailure) is difficult. The loss of life, freedom, or loved ones after a failed\ncoup, as well as the value of assuming leadership after a successful coup, are\nintangible concepts that defy precise measurement. As evidenced by the 1979 coup\nin Ghana[^4], the fate of the coup leader(s) hangs in the balance; they are high\nlikely to be killed if the coup fails, or to execute others if the coup succeeds.\n\nHowever, these challenges do not render the framework useless. Firstly, its core\nlogic remains valuable, offering insights into how coup plotters might assess the\nreturn and cost of their actions. Secondly, given the significant and elusive\nnature of precise values for $\\mathbf B$ and $\\mathbf C$, they can be treated as\nroughly equal. Consequently, there is no need to fret over how to measure and\ncompare these values precisely. Instead, we can shift our focus from $\\mathbf B$\nand $\\mathbf C$, to the probability of success ($p$), simplifying @eq-eq2 to:\n\n$$\n\\begin{aligned}\np > (1-p)\n\\end{aligned}\n$$ {#eq-eq3}\n\n@eq-eq3 suggests that, to hold @eq-eq2 true, a success probability greater than\n$50\\%$ is necessary. Interestingly, empirical data on coups since 1950 somewhat\nsupports this notion. As shown in @tbl-coups, the overall success rate is\n$49.9\\%$. While this falls short of the $50\\%$ threshold, it's important to\nconsider two factors. Firstly, this is an average rate, not necessarily\nreflective of the probabilities assessed by coup plotters beforehand. Secondly,\noutliers such as irrational actors and coups driven by self-preservation may not\nprioritize success probabilities. Taking these points into account, we can\npropose our first hypothesis:\n\n> ***H1: The fundamental determinant of a coup attempt is the perceived chance of\n> success. Coup plotters likely require a success threshold of at least 50%.***\n\nThis leads us to the next crucial question: What factors determine coup success,\ninfluencing the very decision to attempt one? We will discuss it in the next\nsection.\n\n#### Regime types and power dynamics\n\nThe high success rate in historical data is merely a post-event statistical\ndescription, not indicative of the probability of any specific coup. Importantly,\ncoup plotters do not rely on past success rates as their guide; instead, they\nassess their chances based on their unique context.\n\nMilitary strength undeniably plays a critical role in coup attempts. Control of\nthe armed forces offers a significant advantage, explaining why military coups\ndominate discussions on the topic. Much of the literature treats \"coup\" and\n\"military coup\" interchangeably, with scholars like @powell2011 finding that half\nof 14 studies attribute coups solely to the military. Consequently, significant\nfocus, from both researchers and policy-makers, centres on the balance of power\nbetween civilian and military authorities, or among military factions themselves.\nStrategies like \"keeping the military content\" [@aidt2019] or \"providing them\nwith resources\" [@huntington1991democratization] aim to reduce military\nintervention. Empirical research informs coup-proofing strategies that either\ndecrease the military's desire for coups or raise barriers to success\n[@leon2013a; @powell2018].\n\nHowever, while military power is decisive, it complicates the analysis. As\n@tbl-regimes demonstrates, military regimes, despite concentrated military\ncontrol, exhibit surprising instability, experiencing the most frequent coup\nattempts. This highlights a crucial issue: the intra-military component. Treating\nthe military as a monolithic entity ignores its complex internal dynamics\n[@singh2016]. Any military comprises diverse groups with their own hierarchies,\nfostering suspicion, competition, and vigilance rather than unity. The\nclandestine nature of coups necessitates small, secretive groups. Plotters are\nunsure of other factions' stances and fear their opposition or intervention, as\nexemplified by the swiftly thwarted 2021 Niger coup[^5]. The success of a coup\nhinges heavily on other military factions' reactions [@geddes1999].\n\nMoreover, military force is not the only factor shaping the balance of power.\nInternal divisions within the ruling elites, public support, and foreign backing\nalso play important roles. Since the balance of power is not a clearly observable\nvariable, especially difficult to measure for outsiders and academic scholars, we\ncan shift our focus from who controls power in a specific context to what factors\nshape the balance of power. This leads us to regime type, as the classification\nof regime type is based mainly on the power structure. For example,\n\"...definition of regimes emphasizes the rules that identify the group from which\nleaders can come and determine who influences leadership choice and policy\"\n[@geddes2014, p. 314]. We will leverage this framework to categorize autocracies\nbased on leadership origin and decision-making, classifying regimes into three\nmain categories: military, personalist, and dominant-party.\n\n-   **Military Regimes:** Characterized by the dominance of a junta—a group of\n    military officers who control the regime's power structure, including\n    leadership selection and policy formulation. Examples include the Brazilian\n    regime (1964-1985), the Argentine regime (1976-1983), and the Salvadoran\n    regime (1948-1984) [@geddes1999].\n\n-   **Personalist Regimes:** Power resides with a single, charismatic leader who\n    controls policy, the military, and succession. Regimes like Rafael Trujillo's\n    in the Dominican Republic (1930-1961), Idi Amin's in Uganda (1971-1979), and\n    Jean-Bédel Bokassa's in the Central African Republic (1966-1979) exemplify\n    personalist rule (ibid.).\n\n-   **Dominant-Party Regimes:** Power rests within a well-organized ruling party,\n    with leaders acting as its representatives. The party structure and ideology\n    foster internal cohesion and a long-term vision. Examples include the Partido\n    Revolucionario Institucional (PRI) in Mexico, the Revolutionary Party of\n    Tanzania (CCM), and Leninist parties in various Eastern European countries\n    (ibid.).\n\nThe critical distinction between regime types lies in the unique power balance\nestablished during their seizure of power, often through irregular and violent\nmeans, frequently involving military confrontations. This power struggle\ntypically results in the emergence of the most competent group—be it a military\njunta, a political party, or a strongman—as the core leadership. Furthermore, the\nearly stages of new regimes are often marked by internal purges to consolidate\npower and eliminate potential rivals [@sudduth2017; @roessler2011].\n\nFollowing these external challenges and internal purges, new power dynamics\nemerge in three primary forms: dominant-party regimes, personalist regimes, and\nmilitary regimes. These contrasting power dynamics significantly influence a\nregime's susceptibility to coups. Dominant-party regimes, characterized by a\nwell-organized party with clear ideology, hierarchy, and discipline, exhibit the\ngreatest resilience against coups due to their institutionalized structures and\nunified leadership. Personalist regimes, where power centers around a single\nstrong leader, are relatively stable during the leader's tenure. However, they\nface a higher risk of coups, particularly due to the lack of clear succession\nplans and vulnerabilities associated with the leader's personal weaknesses,\nhealth issues, and finite lifespan. Military regimes, characterized by power\nstruggles within a junta, are the most vulnerable to coups. The absence of a\nclear final authority in military regimes often leads to internal conflicts, and\nthe presence of multiple military factions increases the likelihood of resolving\ndisputes through force, making these regimes the least stable. @tbl-regimes1\nsummarises the key characteristics of the three main regime types.\n\nThese contrasting power dynamics significantly influence a regime's\nsusceptibility to coups. As @tbl-regimes confirms, military regimes, despite\nrepresenting only 5.6% of country-years, experience a disproportionate share of\ncoups, accounting for over 22% of all occurrences. Personalist regimes face a\nsimilarly high coup risk, constituting 23% of coups while representing only 13%\nof country-years. Conversely, dominant-party regimes, with their\ninstitutionalized structures and unified leadership, exhibit the greatest\nresilience. They represent 22.6% of country-years but account for only 16.7% of\ncoups. The column \"Coup Likelihood\" clearly illustrates the varying risks:\nmilitary regimes have the highest likelihood at 17.2%, followed by personalist\nregimes at 7.7%, and dominant-party regimes at 3.2% (excluding *Other* regime\ntypes).\n\n> ***H2: Due to their balance of power dynamics, military regimes are more prone\n> to coups, followed by personalist regimes, while dominant-party regimes are the\n> least likely to experience coups among the three.***\n\n\\newpage\n\n\\blandscape\n\n\n\n\n\n::: {#tbl-regimes1 .cell tbl-cap='Main features of different types of regimes'}\n::: {.cell-output-display}\n\\begingroup\n\\setlength\\LTleft{0\\linewidth}\n\\setlength\\LTright{0\\linewidth}\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\setlength{\\LTpost}{0mm}\n\\begin{longtable}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedright\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedright\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedright\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedright\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedright\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\nRegime Type & Power Concentration & Succession & Military Alignment & Stability & Examples \\\\ \n\\midrule\\addlinespace[2.5pt]\nMilitary & Junta & Unclear & May have significant influence & Low & Brazil (1964-1985), Argentina (1976-1983) \\\\ \nPersonalist & Single Leader & Unclear or dependent on leader's will & Subordinated to leader & Moderate (initially), Low (long-term) & Dominican Republic (Trujillo, 1930-1961) \\\\ \nDominant-Party & Party Leadership & Institutionalized & Aligned with the party & High & Mexico (PRI), China (CPC) \\\\ \n\\bottomrule\n\\end{longtable}\n\\begin{minipage}{\\linewidth}\n\\emph{Source: GWF \\& Author}\\\\\n\\end{minipage}\n\\endgroup\n\n:::\n:::\n\n\n\n\n\n\\newpage\n\n\n\n\n\n::: {#tbl-regimes .cell tbl-cap='Regime types and coups since 1950'}\n::: {.cell-output-display}\n\\begingroup\n\\setlength\\LTleft{0\\linewidth}\n\\setlength\\LTright{0\\linewidth}\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\setlength{\\LTpost}{0mm}\n\\begin{longtable}{@{\\extracolsep{\\fill}}lrrrrrr}\n\\toprule\nRegime Type & Country Year & Share & Num of Coups & Percent of Coups & Success Rate & Coup Likelihood \\\\ \n\\midrule\\addlinespace[2.5pt]\nDemocracy & 5303 & 46.7\\% & 122 & 24.8\\% & 51.6\\% & 2.3\\% \\\\ \nDominant-Party & 2569 & 22.6\\% & 82 & 16.7\\% & 53.7\\% & 3.2\\% \\\\ \nPersonal & 1477 & 13.0\\% & 113 & 23.0\\% & 44.2\\% & 7.7\\% \\\\ \nMonarchy & 1056 & 9.3\\% & 25 & 5.1\\% & 56.0\\% & 2.4\\% \\\\ \nMilitary & 638 & 5.6\\% & 110 & 22.4\\% & 48.2\\% & 17.2\\% \\\\ \nOther & 322 & 2.8\\% & 39 & 7.9\\% & 53.8\\% & 12.1\\% \\\\ \nTotal & 11365 & 100.0\\% & 491 & 100.0\\% & 49.9\\% & 4.3\\% \\\\ \n\\bottomrule\n\\end{longtable}\n\\begin{minipage}{\\linewidth}\n\\emph{Source: REIGN and GIC Datasets}\\\\\n\\end{minipage}\n\\endgroup\n\n:::\n:::\n\n\n\n\n\n\\elandscape\n\n### Research Design\n\n#### Double probit with sample selection model\n\nThis study employs a sophisticated statistical approach to account for the\nselective nature of coup attempts. While coup attempt rates vary across regimes\n(as discussed previously), success rates tend to be surprisingly consistent,\nhovering around 50% (as shown in @tbl-regimes). This suggests that coup attempts\nare not random acts, but rather strategically planned and undertaken only when\nthe odds of success appear favourable. A standard statistical model would not\naccount for this selectivity, potentially leading to biased results.\n\nTo address this issue, we utilize a two-stage sample selection model, similar to\nthe approach used by @powell2012. This model has two parts:\n\n-   **Selection Equation (Stage 1):** This stage analyzes the factors influencing\n    whether a coup attempt occurs in a particular regime. The primary explanatory\n    variable here is regime type, as previously discussed. Additional control\n    variables may also be included, denoted by $\\mathbf{XB}$.\n\n-   **Outcome Equation (Stage 2):** This stage focuses on the probability of\n    success for those coup attempts that actually take place.\n\nThe primary explanatory variables are regime types, as previously discussed.\nControl variables are included in $\\mathbf{XB}$. The selection equation (first\nstage) models the probability that a coup attempt occurs and can be expressed as\nfollows:\n\n$$\n\\begin{aligned}\ny_1^*=\\alpha_0 + \\alpha_1 Regime_i + \\mathbf {XA} + \\mu_{1i}\n\\end{aligned}\n$$ {#eq-eq4}\n\nHere, ${y_1}^*$ is an unobserved variable, which may be known to coup plotters.\n$Regime_i$ is a categorical variable (*military*, *personalist*, or\n*dominant-party*). $\\mathbf{XB}$ captures other control variables, such as the\neconomic crisis index, previous coups, military expenditure, etc.\n\nThe observed binary outcome $\\mathbf{y_1}$ is:\n\n$$\n\\begin{aligned}\ny_1 = \n\\begin{cases} \n1 &\\text{if $y_1^*>0$ (coup attempt occurs)} \\\\\n0 &\\text{if $y_1^*\\le0$ (no coup attempt)}\n\\end{cases}\n\\end{aligned}\n$$\\\nIn the first stage, if $y_1^*\\le0$, no coup attempt occurs in a given\ncountry-year, indicating that the unobserved variable does not reach the\nthreshold. If $y_1^*>0$, at least one coup attempt is made in a country-year,\nindicating that the unobserved variable surpasses the threshold. The probability\nis expressed as:\n\n$$\n\\begin{aligned}\nProb(y_1 =1)&=Prob(y_{1}^*>0) \\\\\n&=\\Phi(\\alpha_0 + \\alpha_1 Regime_i + \\mathbf{XA})\n\\end{aligned}\n$$ {#eq-eq4a}\n\nSimilarly, the outcome equation (second stage) models the probability that a coup\nattempt is successful, given that it occurs:\n\n$$\n\\begin{aligned}\ny_2^*=\\beta_0 + \\beta_1 Regime_i + \\mathbf {XB} + \\mu_{2i}\n\\end{aligned}\n$$ {#eq-eq5}\n\nThe observed outcome $y_2$ is:\n\n$$\n\\begin{aligned}\ny_2 = \n\\begin{cases} \n1 &\\text{if $y_2^*>0$ (coup succeeds)} \\\\\n0 &\\text{if $y_2^*\\le0$ (coup fails)}\n\\end{cases}\n\\end{aligned}\n$$\n\nThe probability equations is:\n\n$$\n\\begin{aligned}\nProb(y_2=1|y_1 =1)=\\Phi(\\beta_0 + \\beta_1 Regime_i + \\mathbf{XB})\n\\end{aligned}\n$$ {#eq-eq5a}\n\n#### Variables\n\n-   Dependent variable\n\nOur analysis utilizes data on coup attempts and outcomes from @powell2011. A\nsuccessful coup is defined as one where the incumbent leader is removed from\npower for more than seven days. The dataset covers the period from 1950 to 2023\nand includes information on 491 coup attempts, with roughly half (245) being\nsuccessful. Descriptive statistics for these coup attempts and regime types can\nbe found in @tbl-coups and @tbl-regimes.\n\n-   Key Independent Variable: Regime Type\n\nThe core variable of interest is regime type, categorized following the\nclassification system of @geddes2014 (GWF). We focus on military, personalist,\nand dominant-party regimes, with democracies and monarchies included for\ncomparison. Descriptive statistics for regime types are presented in\n@tbl-regimes.\n\n-   Control variables\n\nOur control variables are chosen based on the research of @gassebner2016. They\nanalyzed 66 factors potentially influencing coups and found that slow economic\ngrowth, prior coup attempts, and other forms of political violence are\nparticularly significant factors. Therefore, we include economic performance,\npolitical violence, and the number of previous coups as our main control\nvariables.\n\n**Economic Performance:** We measure economic performance using the current-trend\n($CT$) ratio developed by @krishnarajan2019. This ratio compares a country's\ncurrent GDP per capita to the average GDP per capita over the previous five\nyears. A higher $CT$ ratio indicates stronger economic performance. We use GDP\nper capita data (in constant 2017 international 1000 dollars, PPP) from the V-Dem\ndataset by @fariss2022, lagged by one year to reflect the prior year's economic\nimpact. For a country $i$ at year $t$, the $CT$ ratio is calculated as follows:\n$$\n\\begin{aligned}\nCT_{i,t} = {GDP/cap_{i,t} \\over {1 \\over 5} {\\sum_{k=1}^5GDP/cap_{i,t-k}}}\n\\end{aligned}\n$$\n\n**Political Violence:** We capture overall regime stability by including a\nviolence index that encompasses all types of internal and interstate wars and\nviolence. This data comes from the Major Episodes of Political Violence dataset\nby Marshall [@marshall2005current].\n\n**Previous coups:** The number of previous coups in a country is included in the\nfirst-stage (selection) model to assess its influence on the likelihood of a coup\nattempt. However, it is excluded from the second-stage model (outcome) because\nthe number of past coups may not directly impact the outcome of a specific coup\nattempt. Recognizing that previous coups from a long time ago might not\nsignificantly affect the current situation, I ran another regression using the\ntime distance since the last coup instead of the number of previous coups for\ncomparison. This approach accounts for the diminishing impact of past events over\ntime, providing a potentially more accurate assessment of how historical coup\nactivity influences the likelihood of current coup attempts.\n\n### Results and Discussion\n\n::: {.content-visible when-format=\"html\"}\n\n\n\n\n::: {#tbl-model .cell tbl-cap='Sample Selection Model of Regime Type and Coup Success, 1950-2019'}\n\n```{.r .cell-code}\ndownload.file(\"https://raw.githubusercontent.com/reddylee/Datasets/main/political_violence.csv\", \"data/political_violence.csv\")\npolitical_violence <- fread(here(\"data/political_violence.csv\")) |> \n  dplyr::select(ccode, year, violence = actotal)\n\ngdp <- vdem |> \n  dplyr::select(ccode = COWcode, year, gdppc = e_gdppc) |> \n  filter(year > 1940) |> \n  mutate(ct = gdppc / lag(rollapply(gdppc, width = 5, FUN = mean,\n                               align = 'right', fill = NA)),\n         .by = c(ccode)) \n\ndownload.file(\"https://www.uky.edu/~clthyn2/coup_data/powell_thyne_ccode_year.txt\", \"data/coup_all.csv\")\ncoup_all <- fread(here(\"data/coup_all.csv\")) |> \n  mutate(coup = case_when(\n    coup1 == 0 ~ 0,\n    coup1 == 2 | coup2 == 2 | coup3 == 2 | coup4 == 2 ~ 2,\n    TRUE ~ 1\n  )) |>\n  group_by(ccode) %>%\n  arrange(year) %>%\n  mutate(pre_coups = lag(cumsum(coup %in% c(1, 2)), default = 0),\n         last_coup_year = lag(case_when(coup %in% c(1, 2)  ~ year,\n                                        TRUE ~ NA_integer_)),\n         last_coup_year = case_when(year == min(year) ~ year,\n                                    TRUE ~ last_coup_year)) |> \n  fill(last_coup_year, .direction = \"down\") |>\n  mutate(time_since_last_coup = year - last_coup_year,\n         coup_dummy = case_when(pre_coups == 0 ~ 0,\n                                TRUE ~ 1)) |>\n  dplyr::select(ccode, year, coup, pre_coups, time_since_last_coup, coup_dummy) \n\nreg_data <- regimes |> \n  dplyr::select(country = extended_country_name,\n         ccode = reign_cowcode, year, regime_type) |>\n  left_join(coup_all, by = join_by(ccode, year)) |> \n  left_join(political_violence, by = join_by(ccode, year)) |>\n  left_join(gdp, by = join_by(ccode, year)) |> \n  filter(!is.na(gdppc)) |> \n  mutate(violence = na.locf(violence, .by = ccode)) \n\nmodel_1 <- reg_data |>\n  filter(regime_type != \"other\") |>\n  mutate(regime = fct_relevel(regime_type, \"dominant-party\"),\n         ect = (ct-1)*100) |>\n  selection(coup > 0 ~ regime + ect + gdppc + violence + coup_dummy*time_since_last_coup,\n            coup > 1 ~ regime + ect + gdppc + violence,\n            data = _) \n\nmodel_1_selection <- model_1\nmodel_1_selection$param$index$betaO <- model_1$param$index$betaS\nmodel_1_selection$param$index$betaS <- model_1$param$index$betaO\n\nmodel_2 <- reg_data |>\n  filter(regime_type != \"other\") |>\n  mutate(regime = fct_relevel(regime_type, \"dominant-party\"),\n         ect = (ct-1)*100,\n         Coup = coup) |>\n  select(Coup, regime, ect, gdppc, violence, coup_dummy = pre_coups) |> \n  selection(Coup > 0 ~ regime + ect + gdppc + violence + coup_dummy,\n            Coup > 1 ~ regime + ect + gdppc + violence,\n            #method = \"2step\",\n            data = _) \n\nmodel_2_selection <- model_2\nmodel_2_selection$param$index$betaO <- model_2$param$index$betaS\nmodel_2_selection$param$index$betaS <- model_2$param$index$betaO\n\nstargazer(model_2_selection, model_2, model_1_selection, model_1,\n          type = \"html\",\n          header = F,\n          dep.var.caption = \"\",\n          dep.var.labels = c(\"Model 1\", \"Model 2\"),\n          #dep.var.labels.include = T,\n          #multicolumn = T,\n          #title = \"Sample Selection Model of Regime Types and Coups, 1950-2019\",\n          column.labels = c(\"Coup Attempts\", \"Coup Outcome\",\"Coup Attempts\", \"Coup Outcome\"),\n          intercept.bottom = F,\n          #label = \"results\",\n          covariate.labels = c(\"Constant\", \"Regime: Democracy\", \"\\\\hspace{1.6cm}Military\", \"\\\\hspace{1.6cm}Monarchy\", \"\\\\hspace{1.6cm}Personalist\", \"Economic trend\", \"GDP per capita\", \"Political violence\", \"Previous coups (P)\", \"Yrs since coup (Y)\", \"Interaction term: P * Y\"),\n          summary.logical = F,\n          column.sep.width = \"7pt\",\n          font.size = \"small\"\n          )\n```\n\n\n<table style=\"text-align:center\"><tr><td colspan=\"5\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"></td><td colspan=\"2\">Model 1</td><td colspan=\"2\">Model 2</td></tr>\n<tr><td style=\"text-align:left\"></td><td>Coup Attempts</td><td>Coup Outcome</td><td>Coup Attempts</td><td>Coup Outcome</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(1)</td><td>(2)</td><td>(3)</td><td>(4)</td></tr>\n<tr><td colspan=\"5\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Constant</td><td>-1.774<sup>***</sup></td><td>-1.803<sup>***</sup></td><td>-1.663<sup>***</sup></td><td>-0.653</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.058)</td><td>(0.360)</td><td>(0.088)</td><td>(0.518)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Regime: Democracy</td><td>0.056</td><td>0.068</td><td>0.043</td><td>0.042</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.072)</td><td>(0.121)</td><td>(0.075)</td><td>(0.192)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">1.6cmMilitary</td><td>0.687<sup>***</sup></td><td>0.596<sup>***</sup></td><td>0.345<sup>***</sup></td><td>0.247</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.084)</td><td>(0.170)</td><td>(0.091)</td><td>(0.229)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">1.6cmMonarchy</td><td>0.282<sup>**</sup></td><td>0.178</td><td>0.234<sup>*</sup></td><td>0.088</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.118)</td><td>(0.201)</td><td>(0.123)</td><td>(0.310)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">1.6cmPersonalist</td><td>0.319<sup>***</sup></td><td>0.128</td><td>0.134<sup>*</sup></td><td>-0.145</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.075)</td><td>(0.170)</td><td>(0.080)</td><td>(0.205)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Economic trend</td><td>-0.015<sup>***</sup></td><td>-0.004</td><td>-0.014<sup>***</sup></td><td>0.009</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.002)</td><td>(0.007)</td><td>(0.002)</td><td>(0.008)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">GDP per capita</td><td>-0.028<sup>***</sup></td><td>-0.028<sup>***</sup></td><td>-0.016<sup>***</sup></td><td>-0.016</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.003)</td><td>(0.006)</td><td>(0.003)</td><td>(0.010)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Political violence</td><td>0.033<sup>**</sup></td><td>0.033<sup>*</sup></td><td>0.038<sup>***</sup></td><td>0.025</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.013)</td><td>(0.020)</td><td>(0.013)</td><td>(0.031)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Previous coups (P)</td><td>0.030<sup>***</sup></td><td></td><td>0.447<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.010)</td><td></td><td>(0.086)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Yrs since coup (Y)</td><td></td><td></td><td>-0.018<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td>(0.004)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Interaction term: P * Y</td><td></td><td></td><td>-0.013<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td>(0.005)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td></tr>\n<tr><td colspan=\"5\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Observations</td><td>9,606</td><td>9,606</td><td>9,606</td><td>9,606</td></tr>\n<tr><td style=\"text-align:left\">Log Likelihood</td><td>-1,663.646</td><td>-1,663.646</td><td>-1,598.603</td><td>-1,598.603</td></tr>\n<tr><td style=\"text-align:left\">rho</td><td>0.898<sup>***</sup> (0.158)</td><td>0.898<sup>***</sup> (0.158)</td><td>0.386<sup>*</sup> (0.234)</td><td>0.386<sup>*</sup> (0.234)</td></tr>\n<tr><td colspan=\"5\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"><em>Note:</em></td><td colspan=\"4\" style=\"text-align:right\"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>\n</table>\n:::\n\n\n\n\n\nThe double probit model with sample selection, estimated using the\nsampleSelection package [@sampleSelection-2] in R, provides valuable insights\ninto the factors influencing coup attempts and their outcomes across different\nregime types from 1950 to 2019 (@tbl-model). We present two models that differ\nslightly in their treatment of previous coups: Model 1 incorporates the number of\nprevious coups, while Model 2 utilizes the time elapsed since the last coup.\n:::\n\n::: {.content-visible unless-format=\"html\"}\n\n\n\n\n\n\\begin{table}[!htbp] \\centering \n  \\caption{Sample Selection Model of Regime Types and Coups, 1950-2019} \n  \\label{results_coup} \n\\small \n\\begin{tabular}{@{\\extracolsep{7pt}}lcccc} \n\\\\[-1.8ex]\\hline \n\\hline \\\\[-1.8ex] \n\\\\[-1.8ex] & \\multicolumn{2}{c}{Model 1} & \\multicolumn{2}{c}{Model 2} \\\\ \n & Coup Attempts & Coup Outcome & Coup Attempts & Coup Outcome \\\\ \n\\\\[-1.8ex] & (1) & (2) & (3) & (4)\\\\ \n\\hline \\\\[-1.8ex] \n Constant & $-$1.774$^{***}$ & $-$1.803$^{***}$ & $-$1.663$^{***}$ & $-$0.653 \\\\ \n  & (0.058) & (0.360) & (0.088) & (0.518) \\\\ \n  & & & & \\\\ \n Regime: Democracy & 0.056 & 0.068 & 0.043 & 0.042 \\\\ \n  & (0.072) & (0.121) & (0.075) & (0.192) \\\\ \n  & & & & \\\\ \n \\hspace{1.6cm}Military & 0.687$^{***}$ & 0.596$^{***}$ & 0.345$^{***}$ & 0.247 \\\\ \n  & (0.084) & (0.170) & (0.091) & (0.229) \\\\ \n  & & & & \\\\ \n \\hspace{1.6cm}Monarchy & 0.282$^{**}$ & 0.178 & 0.234$^{*}$ & 0.088 \\\\ \n  & (0.118) & (0.201) & (0.123) & (0.310) \\\\ \n  & & & & \\\\ \n \\hspace{1.6cm}Personalist & 0.319$^{***}$ & 0.128 & 0.134$^{*}$ & $-$0.145 \\\\ \n  & (0.075) & (0.170) & (0.080) & (0.205) \\\\ \n  & & & & \\\\ \n Economic trend & $-$0.015$^{***}$ & $-$0.004 & $-$0.014$^{***}$ & 0.009 \\\\ \n  & (0.002) & (0.007) & (0.002) & (0.008) \\\\ \n  & & & & \\\\ \n GDP per capita & $-$0.028$^{***}$ & $-$0.028$^{***}$ & $-$0.016$^{***}$ & $-$0.016 \\\\ \n  & (0.003) & (0.006) & (0.003) & (0.010) \\\\ \n  & & & & \\\\ \n Political violence & 0.033$^{**}$ & 0.033$^{*}$ & 0.038$^{***}$ & 0.025 \\\\ \n  & (0.013) & (0.020) & (0.013) & (0.031) \\\\ \n  & & & & \\\\ \n Previous coups (P) & 0.030$^{***}$ &  & 0.447$^{***}$ &  \\\\ \n  & (0.010) &  & (0.086) &  \\\\ \n  & & & & \\\\ \n Yrs since coup (Y) &  &  & $-$0.018$^{***}$ &  \\\\ \n  &  &  & (0.004) &  \\\\ \n  & & & & \\\\ \n Interaction term: P * Y &  &  & $-$0.013$^{***}$ &  \\\\ \n  &  &  & (0.005) &  \\\\ \n  & & & & \\\\ \n\\hline \\\\[-1.8ex] \nObservations & 9,606 & 9,606 & 9,606 & 9,606 \\\\ \nLog Likelihood & $-$1,663.646 & $-$1,663.646 & $-$1,598.603 & $-$1,598.603 \\\\ \n$\\rho$ & 0.898$^{***}$  (0.158) & 0.898$^{***}$  (0.158) & 0.386$^{*}$  (0.234) & 0.386$^{*}$  (0.234) \\\\ \n\\hline \n\\hline \\\\[-1.8ex] \n\\textit{Note:}  & \\multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\\\ \n\\end{tabular} \n\\end{table} \n\n\n\n\n\nThe double `probit` model with sample selection, estimated using the\n`sampleSelection` package [@sampleSelection-2] in R, provides valuable insights\ninto the factors influencing coup attempts and their outcomes across different\nregime types from 1950 to 2019 (Table \\ref{results_coup}). We present two models\nthat differ slightly in their treatment of previous coups: Model 1 incorporates\nthe number of previous coups, while Model 2 utilizes the time elapsed since the\nlast coup.\n:::\n\n\\newpage\n\n#### The Selection Model: Coup Attempts\n\n\n\n\n\n::: {#tbl-mfx1 .cell tbl-cap='Average marginal effects of coup attempts (Selection of Model 1)'}\n::: {.cell-output-display}\n\\begingroup\n\\setlength\\LTleft{0.025\\linewidth}\n\\setlength\\LTright{0.025\\linewidth}\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\setlength{\\LTpost}{0mm}\n\\begin{longtable}{@{\\extracolsep{\\fill}}llrr}\n\\toprule\nTerm & Contrast & AME\\textsuperscript{\\textit{1}} & Ratio Percent \\\\ \n\\midrule\\addlinespace[2.5pt]\nRegime: Democracy & mean(democracy - dominant-party) & 0.003 & 13.030 \\\\ \n{\\hspace{47.25pt}Military} & mean(military - dominant-party) & 0.070 & 277.730 \\\\ \n{\\hspace{47.25pt}Monarchy} & mean(monarchy - dominant-party) & 0.020 & 80.620 \\\\ \n{\\hspace{47.25pt}Personal} & mean(personal - dominant-party) & 0.024 & 93.980 \\\\ \nEconomic trend & mean(+1) & -0.001 & -2.850 \\\\ \nGDP per capita & mean(+1) & -0.002 & -5.400 \\\\ \nPolitical violence & mean(+1) & 0.003 & 6.550 \\\\ \nPrevious coups & mean(+1) & 0.002 & 5.930 \\\\ \n\\bottomrule\n\\end{longtable}\n\\begin{minipage}{\\linewidth}\n\\textsuperscript{\\textit{1}}AME: Average Marginal Effect\\\\\n\\end{minipage}\n\\endgroup\n\n:::\n:::\n\n\n\n\n\nIn the selection model (Column 1), military and personalist regimes exhibit\nsignificant positive coefficients at the 1% level, indicating a higher likelihood\nof experiencing coup attempts compared to dominant-party regimes. Control\nvariables also exhibit effects in expected directions. Stronger economic\nperformance, indicated by higher economic growth trends and GDP per capita\nlevels, correlates with a lower risk of coup attempts. This suggests that better\neconomic conditions and relatively higher living standards reduce incentives for\ncoups. Political violence shows a positive and significant effect on coup\nattempts, indicating that higher levels of instability increase the likelihood of\ncoups. The positive coefficient for the number of previous coups suggests a\n\"copycat\" effect from earlier incidents.\n\nWhile interpreting `probit` model results directly is not intuitive, @tbl-mfx1,\ngenerated using `marginaleffects` package [@marginaleffects], helps clarify the\nregime effects. The Average Marginal Effect (AME) column shows changes in\nprobability when a variable increases by one unit (for numeric variables) or\ncompared to a reference category (for categorical variables). For instance, the\nmilitary regime's marginal effect of 0.07 indicates that the probability of coup\nattempts in military regimes is 7 percentage points (pp) higher than in\ndominant-party regimes, ceteris paribus. For GDP per capita, the marginal effect\nof -0.002 suggests that a \\$1000 increase reduces the probability of coup\nattempts by 0.2 pp under average conditions.\n\nThe Ratio column displays the relative change in percent. While a 7 pp increase\nmight seem modest, it is substantial in context. Given that the average\nprobability of a coup attempt in dominant-party regimes is approximately 2.53%,\nthe 7 pp increase means military regimes are about 277.7% more likely to\nencounter coups than dominant-party regimes—a significant change. Similarly,\npersonalist regimes show a 2.4 pp higher probability, about 94% more likely\ncompared to dominant-party regimes. Monarchies display a positive effect similar\nto personalist regimes, reflecting that monarchies are essentially a subset of\npersonalist regimes with royal titles.\n\nControl variables, however, show weak effects in predicting coup attempts. None\nof their marginal effects reach 1 pp in probability, and all are less than 7% in\nratio. Given that the actual probability of a coup attempt is only 2% to 3%,\nthese small increases or decreases can be considered negligible.\n\nThese results align with our theoretical expectations regarding internal power\nstruggles within military juntas and succession vulnerabilities in personalist\nregimes, underscoring the importance of regime structure in understanding coup\nlikelihood.\n\nModel 2 employs years since the last coup instead of the number of previous\ncoups. Due to most countries not experiencing coups, an interaction term between\nprevious coups (as a binary variable indicating presence or absence of coups) and\nyears since the last coup is used. Generally, Model 2 shows results in the same\ndirection as Model 1, albeit with relatively lower coefficients (@tbl-mfx2).\n\n\n\n\n\n::: {#tbl-mfx2 .cell tbl-cap='Average marginal effects of coup attempts (Selection of Model 2)'}\n::: {.cell-output-display}\n\\begingroup\n\\setlength\\LTleft{0.025\\linewidth}\n\\setlength\\LTright{0.025\\linewidth}\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\setlength{\\LTpost}{0mm}\n\\begin{longtable}{@{\\extracolsep{\\fill}}llrr}\n\\toprule\nTerm & Contrast & AME\\textsuperscript{\\textit{1}} & Ratio Percent \\\\ \n\\midrule\\addlinespace[2.5pt]\nRegime: Democracy & mean(democracy - dominant-party) & 0.003 & 8.930 \\\\ \n{\\hspace{47.25pt}Military} & mean(military - dominant-party) & 0.028 & 91.650 \\\\ \n{\\hspace{47.25pt}Monarchy} & mean(monarchy - dominant-party) & 0.018 & 57.040 \\\\ \n{\\hspace{47.25pt}Personal} & mean(personal - dominant-party) & 0.009 & 30.090 \\\\ \nEconomic trend & mean(+1) & -0.001 & -2.530 \\\\ \nGDP per capita & mean(+1) & -0.001 & -2.890 \\\\ \nPolitical violence & mean(+1) & 0.003 & 7.330 \\\\ \nPrevious coups (P) & mean(1 - 0) & 0.023 & 91.990 \\\\ \nNA & mean(+1) & -0.002 & -5.050 \\\\ \n\\bottomrule\n\\end{longtable}\n\\begin{minipage}{\\linewidth}\n\\textsuperscript{\\textit{1}}AME: Average Marginal Effect\\\\\n\\end{minipage}\n\\endgroup\n\n:::\n:::\n\n\n\n\n\n#### The Outcome Model: Coup Success\n\nThe outcome model (Columns 2 and 4 in Table \\ref{results}) reveals determinants\nof coup success. Military regimes demonstrate a higher probability of coup\nsuccess compared to dominant-party regimes, aligning with expectations that\nmilitary regimes face higher coup risks due to their increased chances of\nsuccess. Personalist and monarchical regimes show slight positive effects on coup\nsuccess, but these effects are not statistically significant.\n\nControl variables exhibit different patterns in the outcome model compared to the\nselection model. Both GDP per capita and political violence maintain a weak\ninfluence, similar to their effects in the selection model. However, the economic\ntrend shows a less significant negative effect on coup success.\n\nThese results indicate that regime type remains a significant determinant of both\ncoup attempts and successes, even after controlling for other factors, strongly\nsupporting the proposed theoretical framework.\n\n\n\n\n\n\n\n\n\n\n\n#### Discussion\n\nThe $\\rho$ values of 0.898 in Model 1 and 0.386 in Model 2, significant at 1% and\n10% levels respectively, are crucial parameters in the sample selection model.\nThese values represent the correlation between the error terms of the selection\nequation (coup attempts) and the outcome equation (coup outcomes). A high and\nsignificant $\\rho$ suggests that unobserved factors influencing the likelihood of\na coup attempt are strongly correlated with those influencing the likelihood of a\nsuccessful coup. Practically, this indicates that the selection model is\nappropriate and that accounting for selection bias (i.e., the fact that only\ncoups with high chances of success will be attempted) is critical for obtaining\nunbiased estimates. The high $\\rho$ value indicates that the same underlying\nconditions that lead to a coup attempt also affect its success, underscoring the\nimportance of considering both stages in the analysis.\n\nThe results strongly support the choice of the sample selection model.\nSignificant coefficients with theoretically consistent directions suggest the\nmodel effectively captures key aspects of coup dynamics. Regimes with weaker\ninstitutional structures are more vulnerable to coup attempts, while better\neconomic conditions make coups less likely overall. The model effectively\naddresses the non-random nature of coup attempts by treating selection and\noutcome as separate processes.\n\nThe observed disparity between coup attempt rates and success rates across\nregimes points towards selection bias, further validating the use of the sample\nselection model. This model acknowledges that coups are not random events, but\nrather strategic actions undertaken when the odds appear favourable.\n\nIn summary, the double `probit` model with sample selection proves to be a\nwell-suited approach for this research. It provides robust insights into the\nfactors influencing both the likelihood of coup attempts and their success rates\nacross different regime types. The findings highlight the crucial role of regime\nstructure and the selective nature of coup attempts, supporting the theoretical\nframework and empirical strategy employed in this study.\n\n#### Implications\n\nThe finding that regime type plays a crucial role in determining coup attempts,\nwhile not surprising, has received relatively little attention as a primary\nresearch focus. However, even if this result is acknowledged more widely by\nacademics or politicians, it is unlikely to be implemented as a coup-proofing\nstrategy.\n\nFirstly, regime type is not a policy that can be easily altered. It is largely\nestablished during the formation of the regime, resulting from power struggles\nwithin the ruling group. As previously discussed, there are specific reasons why\none regime type is chosen over another. Regimes established through irregular\nmeans are unlikely to transition to a more stable regime type peacefully and\nsmoothly.\n\nSecondly, even if a particular regime type is more effective at preventing coups,\nthis may hold little significance for those in power. Autocratic leaders often\nprioritize personal power and survival over long-term regime stability, as more\nstable systems may not benefit them personally. Democratic norms and constraints\nmay be seen as obstacles to their goals rather than as safeguards against\ninstability.\n\nWhile this conclusion might seem discouraging, it is not entirely pessimistic.\nThe power game involves not only the top leaders but also the majority of other\nelites. While top leaders may prioritize personal gains, other elites, including\nthe military, economic elites, and civil society, have a vested interest in a\nstable political environment. Therefore, it is possible to reach a consensus for\na political system that is less susceptible to coups, potentially benefiting a\nbroader spectrum of society.\n\n### Conclusion\n\nMotivated by the lack of consensus despite numerous empirical studies on the\ndeterminants of coups, this study introduces a novel approach that prioritizes\ndeterminants based on their impact on coup success. By analysing coup success\nrates, the study hypothesizes that the expected outcomes of coups are critical\ndeterminants of their occurrence. Utilizing a double `probit` model with sample\nselection, I investigate and confirm the relationship between regime types and\ncoup attempts.\n\nThe findings suggest that regime type plays a significant role in the likelihood\nof coup attempts. Military and personalist regimes, characterized by weaker\ninstitutional frameworks and higher vulnerability during power transitions, are\nmore susceptible to coups. This underscores the importance of supporting\ninitiatives that strengthen constitutional institutions within these regimes.\n\nThe research also finds that stronger economic performance is associated with a\nlower risk of coups, suggesting that policies promoting economic development can\nbe effective in reducing coup risk.\n\nThe study shows that the most efficient coup-proofing strategies involve the\nestablishment of strong institutions. In contrast, purges, random shifting of\nmilitary officers, or increased military expenditures are less effective.\nHowever, few autocratic leaders, particularly dictators or military juntas, are\nwilling to institutionalize their regimes, as such reforms may constrain their\npower or shorten their terms. While institutions benefit the regime, they do not\nnecessarily benefit the leaders themselves.\n\nFuture research could explore specific institutional reforms that are most\neffective in improving stability across different regimes.\n\n## Autocoups: Conceptual Clarification and Analysis of Power Extensions by Incumbent Leaders\n\n### Abstract {.unnumbered}\n\nThis study aims to clarify the concept of autocoups, specifically focusing on\npower extensions by incumbent leaders. By distinguishing autocoups from the\nbroader and more ambiguous concepts of self-coups or executive takeover, which\nencompass both executive power aggrandizement and power extension, this research\nredefines the concept of autocoups. Based on this refined definition, I introduce\na novel dataset of autocoup events from 1945 to 2022. Using the newly compiled\ndataset, the research includes three types of case studies that provide\nqualitative insights into the dynamics of autocoups. Additionally, an empirical\nanalysis on the determinants of autocoup attempts and success is offered to\ndemonstrate how the autocoup dataset can be employed for more quantitative\nresearch. This study contributes to the existing literature by providing a\nclearer conceptual framework and a novel dataset of autocoups. It enhances our\nunderstanding of the mechanisms and motivations behind power extensions by\nincumbent leaders and examines the implications for democratic backsliding,\ndemocratic breakdown, personalization, and autocratic deterioration. The insights\ngained from this study could draw more attention to the effects of autocoups on\npower transitions, political stability, and democratic resilience.\n\nkeywords: *Coups, Autocoups, Political Leadership*\n\n\\newpage\n\n### Introduction\n\nThe study of irregular power transitions, encompassing both irregular entries and\nexits from office, has long been a central topic in political science. However,\none form of irregular power transition - the incumbent leader's refusal to\nrelinquish power - remains relatively understudied. This scenario, where leaders\noverstay their mandated term limits for one or more terms, or even indefinitely,\nlacks a universally accepted term in the existing literature. To address this\ngap, this study adopts the term \"autocoup\" to denote this phenomenon.\n\nCoups, being the primary form of irregular power transitions, have received\nsignificant scholarly attention. Research by @goemans2009 indicate that coups\naccount for a substantial portion of such transitions, with roughly two-thirds\n(65.8%) of 374 irregular exits occurring through coups. Additionally, @frantz2016\ndemonstrate that coups are the most common form of exit in autocracies,\nsurpassing regular transitions by a third.\n\nHowever, while coups were once frequent, recent decades have witnessed a decline\nin their occurrence [@bermeo2016; @thyne2019]. Conversely, autocoups appear to be\non the rise, particularly since the Cold War's end [@ginsburg2010evasion;\n@baturo2014; @versteeg2020law]. Despite the significant political impact and\nrising prevalence of autocoups, their study lags behind that of classical coups,\nwhich are extensively documented due to their historical frequency [@thyne2019].\n\nThis research aims to bridge this gap by focusing on the understudied phenomenon\nof autocoups as they are at least equally important and warrant comprehensive\nanalysis. Firstly, autocoups are typically accompanied by a disregard for the\nrule of law, weakened institutions, and potential democratic backsliding or\nauthoritarian personalization. Secondly, like traditional coups, successful\nautocoups increase the risk of future irregular power transitions. Research\nindicates that since 1945, approximately 62 percent of leaders who overstayed\ntheir term limits through autocoups in non-democratic countries were either\nousted or assassinated while in office [@baturo2019]. Thirdly, failed autocoups\noften trigger instability that fuels protests, violence, and even civil wars.\n\nDespite their significance, autocoups are understudied compared to traditional\ncoups. Although several relevant concepts and terminologies such as self-coups,\nautocoups, autogolpes, incumbent takeovers, executive aggrandizement, overstay,\nand continuismo have been proposed and discussed [@marsteintredet2019;\n@baturo2022], there is no clear and widely accepted term to describe these\nevents. Different terms are often used interchangeably or inconsistently, leading\nto confusion. Moreover, due to the lack of clear concepts, the collection of\nautocoup datasets is still in its early stages compared to the rich datasets of\ntraditional coups. Hence, the limited existing studies on autocoups have\nprimarily relied on case studies [@cameron1998; @antonio2021; @pion-berlin2022],\nwith few focusing on quantitative analyses.\n\nTo fully understand irregular political leadership transitions and survival, we\nneed to redefine and clarify the term \"autocoup\" first. Based on a clear\ndefinition, we can introduce an autocoup dataset that can be used for further\nempirical analysis. This study aims to address these knowledge gap surrounding\nautocoups and contribute in three areas. First, it clarifies the terminology by\ndefining autocoups based mainly on power extension. Second, it introduces a new\ndataset of autocoups since 1945 based on this refined definition. Finally, the\nresearch utilizes this dataset for a quantitative analysis of the factors that\ninfluence leaders' decisions to attempt autocoups.\n\nThe subsequent section, based on a comprehensive review of the definitions of\npower expansions and power extensions, proposes a precise definition of\nautocoups. This will be followed by an introduction to the new autocoup dataset\nin Section 3. In Section 4 and 5, I will explain the determinants of autocoup\nattempts through two case studies and demonstrate how the novel autocoup dataset\ncollected in this study can be used in empirical analysis. Finally, I will\nconclude this chapter in Section, summarizing the key insights gained from the\nstudy and suggesting avenues for future research.\n\n### Autocoups: A literature review and clarification of definitions\n\nCompared to coups, which are clearly defined and widely accepted as illegal\nattempts by elites within the ruling group to overthrow the leadership\n[@powell2011], the concept of autocoups (also known as self-coups or autogolpes)\nsuffers from a lack of consistency and clarity. This ambiguity hinders our\nunderstanding and study of a critical phenomenon in irregular power transitions.\nTo address this gap, we need to tackle two key issues: terminology and\ndefinition.\n\n#### Terminology\n\nThe most common term in autocoup literature is self-coup, or autogolpe in Spanish\n[@przeworski2000; @cameron1998a; @bermeo2016; @helmke2017; @marsteintredet2019].\nThis term gained academic prominence after Peruvian President Alberto Fujimori\ndissolved Congress, temporarily suspended the constitution, and ruled by decree\nin 1992 [@mauceri1995; @cameron1998]. However, as @marsteintredet2019 point out,\nthe term \"self-coup\" can be misleading, as it implies a coup against oneself,\nwhich is inaccurate since it is not self-directed but targets other state\ninstitutions or apparatus.\n\nAnother approach to describe coups staged by incumbents is to use terms with\nadjectives or modifiers, such as presidential coup, executive coup,\nconstitutional coup, electoral coup, judicial coup, slow-motion coup, soft coup,\nand parliamentary coup [@marsteintredet2019]. While these terms can be helpful in\nspecific contexts, their proliferation often adds to the overall confusion rather\nthan providing clarification. Most of these terms focus on the specific methods\nused by coup perpetrators but fail to clearly identify the perpetrator,\nnecessitating further explanation. In fact, many of these methods could be\nemployed either by or against executive leaders.\n\nA third alternative involves terms like \"incumbent takeover\" or \"overstay\".\nIncumbent takeover referrs to \"an event perpetuated by a ruling executive that\nsignificantly reduces the formal and/or informal constraints on his/her power\"\n[@baturo2022, p.374], based on earlier research [@svolik2014]. While overstay is\ndefined as \"staying longer than the maximum term as it stood when the candidate\noriginally came in office” [@ginsburg2011evasion, p.1844]. These terms identify\nthe perpetrator (the incumbent) and/or the nature of the event\n(overstaying/extending power). However, they do not highlight the illegality or\nillegitimacy of these actions. Therefore, they cannot serve as a direct\ncounterpart to \"coup,\" which clearly denotes the illegality of leadership\nousters, while \"takeover\" or \"overstay\" diminish the severity.\n\nTherefore, this study strongly advocates for \"autocoup\" as the most accurate and\nappropriate term. It avoids the pitfalls of other terms by clearly conveying the\nessence of the phenomenon as a coup-like power grab and effectively\ndistinguishing autocoups from classical coups by highlighting the perpetrator.\n\n#### Definition\n\nWhile terminology is important, another issue arises with the previous definition\nof autocoups: should we emphasize power expansion or power extension? Power\nExpansion refers to situations where an executive branch expands its power beyond\nits original boundaries, often by encroaching on the authority of other branches\nlike the legislature or judiciary. Power Extension, on the other hand, refers to\nsituations where a leader extends their tenure in office beyond the originally\nmandated term limits. Existing definitions of self-coup or autocoup sometimes\ntouch upon power extensions, but they primarily focus on power expansions, which\nhas several drawbacks.\n\nFirstly, defining autocoups primarily in terms of power expansion does not align\nwell with the definition of a coup. When we define a classical coup, the focus is\nclearly on the ouster of the current leader, not merely a limitation or\nrestriction on their power. Using the same logic, a more appropriate definition\nof an autocoup should prioritize the extension of executive leadership. We would\nnot classify an event as a coup if a vice president seizes some power from the\npresident, as long as the president remains in office. Similarly, an executive\nleader acquiring more power from other branches should not automatically qualify\nas an autocoup if their term limits remain unchanged.\n\nSecondly, emphasizing power expansion raises issues regarding the purpose of\nlaunching an autocoup. As @cameron1998a defined, a self-coup is \"a temporary\nsuspension of the constitution and dissolution of congress by the executive, who\nrules by decree until new legislative elections and a referendum can be held to\nratify a political system with broader executive power\" [@cameron1998a, p.220].\nHowever, without extending their time in office, the leader faces significant\nrisks once their term expires, as they could face legal or political\nrepercussions for the autocoup itself, leaving behind an overly powerful\nexecutive branch for the successor. Although the term \"self-coup\" gained\nprominence from the 1992 Fujimori case in Peru, which initially involved seizing\npower from other institutions, it is important to note that Fujimori ultimately\nextended his term limits through constitutional amendments. The 1993 Constitution\nallowed Fujimori to run for a second term, which he won with popularity in April\n1995. Shortly after Fujimori began his second term, his supporters in Congress\npassed a law of \"authentic interpretation\" which effectively allowed him to run\nfor another term in 2000, which he won amid suspicions and rumors. However, he\ndid not survive the third term. In 2000, facing charges of corruption and human\nrights abuses, Fujimori fled Peru and took refuge in Japan [@ezrow2019].\n\nThirdly, measuring the extent of power expansion to qualify as an autocoup can be\nchallenging. Power expansion might occur as a sudden, significant event, as seen\nwith Fujimori in 1992, or it could be gradual and incremental, as in the case of\nPutin since assuming power in 1999 [@chaisty2019]. In the latter case, it is\nunclear whether each step should be considered an autocoup or if the entire\nprocess together should be labelled as such. If the latter, determining the point\nat which it becomes an autocoup is again problematic.\n\nTherefore, this study argues that a more accurate definition of autocoups should\nprioritize power extension as the core characteristic.\n\nIn light of this discussion, we formally define an autocoup as *the practice of\ncurrent political leaders extending their time in office beyond their originally\nmandated term limits*. Three key points need to be highlighted for this\ndefinition. Firstly, this definition refers to the actual leaders of the country,\nregardless of their official titles. Typically, this would be the president;\nhowever, in some cases, such as in Germany, the primary leader is the premier, as\nthe president is a nominal head of state. Secondly, while the primary\ncharacteristic of an autocoup is extending the term in office, this definition\ndoes not exclude instances of power expansion. Both aspects can coexist, but the\nextension of the term is the central element. Thirdly, autocoups, by their\nnature, subvert legal norms and established power transfer mechanisms. While they\nmay employ seemingly legal tactics, their essence is illegitimacy. This critical\naspect will be explored further in Chapter III.\n\n### Introduction to the Autocoup Dataset\n\n#### Defining the scope\n\nDefining any concept or term inevitably involves borderline cases that are\ndifficult to categorize. In the context of autocoups, it is particularly\nchallenging to determine whether a specific instance of overstaying should be\ncoded as an autocoup. To avoid ambiguity and dilemmas, we will code all instances\nof incumbents extending their original mandated term in office as autocoups,\nregardless of whether the extension is patently illegal or superficially legal.\n\nThis approach is taken because a truly legitimate amendment to power transition\ninstitutions should only apply to subsequent leaders, not the incumbent. If the\nincumbent changes the rules to their own benefit, the legitimacy of such changes\nis questionable, even if the amendment procedures appear legal. We have valid\nreasons to question their motivations since they are the beneficiaries of these\nreforms.\n\nEven so, some cases remain unclear. For example, consider a two-term limit\npresidency where the leader wins a second term. Allegations of election rigging\nmight surface, raising suspicions about the fairness of the election results. If\nsuch suspicions can be verified with evidence or judicial verdict, the case would\nundoubtedly be coded as an autocoup. However, proving election rigging in\ncountries with powerful executives can be difficult. In such instances, we will\nnot classify it as an autocoup unless a formal judicial verdict confirms the\nrigging.\n\nEven in contexts where leaders lack clear term limits or the constitution allows\nindefinite terms, identifying autocoups remains possible. We will discuss and\nexplain this in the next section.\n\n#### **Classifying autocoups** {#sec-classify}\n\nAutocoups can manifest in various forms. To understand this phenomenon better, we\ncan categorize them based on several key factors:\n\n-   **Methods Employed:** This refers to the specific strategies incumbents use\n    to extend their hold on power. Examples include constitution amending or\n    reinterpreting, election cancelling, delaying or rigging.\n\n-   **Degree of Legality:** This dimension captures the extent to which an\n    autocoup deviates from established legal norms. It can range from minor\n    rule-bending to outright constitutional violations.\n\n-   **Duration of Extension:** This category focuses on the length of time the\n    incumbent leader remains in office beyond their designated term limits. It\n    could be a single additional term, multiple terms, or even a lifetime hold on\n    power.\n\n-   **Outcomes:** This factor examines whether the autocoup attempt is successful\n    or ultimately fails.\n\nThis study will primarily focus on the **methods** employed by incumbents to\nstage autocoups. However, we will also code for other relevant aspects like the\ndegree of legality, duration of extension, and outcomes whenever information is\navailable. This multifaceted approach allows for a more nuanced understanding of\nthe variations within autocoups.\n\n##### Evasion of term limits {.unnumbered}\n\nEvasion of term limits is a common tactic employed in autocoups. Incumbents often\nresort to seemingly legal manoeuvres to extend their hold on power. These\nmanoeuvres primarily involve manipulating constitutional provisions through\nvarious means. The incumbents may pressure legislative bodies (congress) or\njudicial institutions (Supreme Court) to reinterpret existing term limits, amend\nthe constitution to extend terms, or even replace the constitution altogether.\nThis might also involve popular vote through referendums, or a combination of\nthese approaches. The extension can range from a single term to indefinite rule.\n\nThese manoeuvres primarily involve manipulating constitutional provisions through\nvarious means.\n\n**Changing Term Length:** Incumbents might lengthen the official term duration\n(e.g., from 4 to 6 years) to stay in office longer, even if the number of allowed\nterms remains unchanged. Examples, in the dataset, include Presidents Dacko (CAR,\n1962), Kayibanda (Rwanda, 1973), and Pinochet (Chile, 1988).\n\n-   **Enabling re-election:** This approach involves incumbents modifying legal\n    or constitutional frameworks to permit themselves to run for leadership\n    again, despite initial restrictions. These restrictions might include\n    prohibitions on re-election, bans on immediate re-election, or term limits\n    that the incumbents have already reached. An illustrative example is\n    President Menem of Argentina in 1993, who leveraged this tactic to extend his\n    tenure.\n\n-   **Removing Term Limits Altogether:** This approach, as seen with President Xi\n    Jinping of China in 2018, technically allows the leader to rule for life,\n    although they may still need to participate in elections (a formality in such\n    cases).\n\n-   **Leader for Life:** This differs from removing term limits as the leader\n    still faces elections (although potentially rigged or uncontested). An\n    example is Indonesia's President Sukarno, who attempted to declare himself\n    president for life in 1963 (ultimately unsuccessful).\n\nThese methods are often used in combination. Initially, the duration of a term is\nextended, followed by amendments to allow re-election, then the removal of term\nlimits, and finally, the declaration of the leader for life. For example, Haitian\nPresident François Duvalier amended the constitution in 1961 to permit immediate\nre-election and then declared himself president for life in 1964.\n\n##### Election Manipulation or Rigging {.unnumbered}\n\nElection manipulation or rigging is the second most commonly used tactic to\nextend an incumbent's tenure.\n\n-   **Delaying or Removing Elections:** Delaying or removing scheduled elections\n    without legitimate justification is a frequent method used by incumbents to\n    maintain power. For instance, Chadian President François Tombalbaye delayed\n    general elections until 1969 after assuming power in 1960. Similarly, Angolan\n    President José Eduardo dos Santos suspended elections throughout his rule\n    from 1979 to 2017.\n\n-   **Refusing Unfavourable Election Results:** Incumbents may refuse to accept\n    unfavourable election results and attempt to overturn them through\n    illegitimate means. For example, President Donald Trump of the United States\n    refused to accept the results of the 2020 election and tried to overturn\n    them.\n\n-   **Rigging Elections:** Winning elections with an extraordinarily high\n    percentage of votes is highly questionable. This study will code elections\n    where the incumbent wins more than 90% of the vote as autocoups. For\n    instance, President Teodoro Obiang of Equatorial Guinea has consistently won\n    elections with over 95% of the vote in multi-party elections since 1996,\n    indicating election rigging.\n\n-   **Excluding Opposition in Elections:** Manipulating the electoral process by\n    excluding opposition parties or candidates from participation, effectively\n    creating a one-candidate race, clearly signifies an autocoup.\n\n##### **Figurehead** {.unnumbered}\n\nTo circumvent term limits, some incumbents might choose a close associate to act\nas a figurehead, taking the office publicly while the incumbent retains real\npower behind the scenes. This can be achieved through seemingly subordinate\npositions.\n\nOne example is Russia in 2008. Facing term limits, President Putin selected\nDmitry Medvedev to run for president. After the election, Medvedev appointed\nPutin as Prime Minister. However, most analysts believe Putin wielded the true\npower throughout this period.\n\n##### Reassigning supreme authority to a new role {.unnumbered}\n\nThis tactic involves an incumbent leader manipulating the constitution or legal\nframework to create a new position of power, or elevate an existing one, before\nstepping down from their current role. They then strategically take on this new\nposition, effectively retaining significant control despite appearing to\nrelinquish power. For example, in 2017, Recep Tayyip Erdoğan, the Prime Minister\nof Turkey, spearheaded a constitutional referendum that transitioned the country\nfrom a parliamentary system to a presidential one. This new system concentrated\nsignificant executive power in the presidency. Following the referendum's\napproval, Erdoğan successfully ran for the newly established presidency,\neffectively retaining control under a different title.\n\n##### One-Time Arrangement for Current Leaders {.unnumbered}\n\nThis strategy involves special arrangements that extend the term or tenure of\ncurrent leaders without altering the underlying institutions. For example,\nLebanon extended President Émile Lahoud's term by three years in 2004 through a\none-time arrangement.\n\n#### Data Coding\n\n\n\n\n\n::: {#tbl-source .cell tbl-cap='Sources of coding autocoup dataset'}\n\\begingroup\n\\setlength\\LTleft{0\\linewidth}\n\\setlength\\LTright{0\\linewidth}\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\begin{longtable}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 60.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 60.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedright\\arraybackslash}p{\\dimexpr 60.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 60.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedright\\arraybackslash}p{\\dimexpr 150.00pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\nSource & Years & Unit of Research & Obervations & Authors \\\\ \n\\midrule\\addlinespace[2.5pt]\n{\\cellcolor[HTML]{EDEDE9}{\\textcolor[HTML]{000000}{Archigos}}} & {\\cellcolor[HTML]{EDEDE9}{\\textcolor[HTML]{000000}{1875-2015}}} & {\\cellcolor[HTML]{EDEDE9}{\\textcolor[HTML]{000000}{Leaders}}} & {\\cellcolor[HTML]{EDEDE9}{\\textcolor[HTML]{000000}{3409}}} & {\\cellcolor[HTML]{EDEDE9}{\\textcolor[HTML]{000000}{ Hein Goemans, Kristian Skrede Gleditsch, Giacomo Chiozza (2009)}}} \\\\ \nPLAD & 1989-2023 & Leaders & 1334 & Pietro Bomprezzi et al. (2024) \\\\ \n{\\cellcolor[HTML]{EDEDE9}{\\textcolor[HTML]{000000}{Incumbent Takeover}}} & {\\cellcolor[HTML]{EDEDE9}{\\textcolor[HTML]{000000}{1913-2019}}} & {\\cellcolor[HTML]{EDEDE9}{\\textcolor[HTML]{000000}{Incumbent takeovers}}} & {\\cellcolor[HTML]{EDEDE9}{\\textcolor[HTML]{000000}{279}}} & {\\cellcolor[HTML]{EDEDE9}{\\textcolor[HTML]{000000}{Alexander Baturo, Jakob Tolstrup (2022)}}} \\\\ \n\\bottomrule\n\\end{longtable}\n\\endgroup\n:::\n\n\n\n\n\nThe autocoup dataset, like most dataset coding procedures, is based on existing\nstudies and datasets. @tbl-source outlines the main sources for coding the\nautocoup dataset. The Archigos dataset [@goemans2009] and the Political Leaders’\nAffiliation Database (PLAD) dataset [@bomprezzi2024wedded] provide comprehensive\ndata on all leaders from 1875 to 2023, although our coding only includes\nautocoups since 1945. These datasets help identify the actual rulers of\ncountries, saving time in distinguishing real leaders from nominal heads of\nstate.\n\nThe Incumbent Takeover dataset [@baturo2022], which integrates data from 11\nrelated datasets, offers a broad spectrum of cases where leaders significantly\nreduce the constraints on their power, encompassing both power expansions and\nextensions. Since some executive takeovers do not qualify as autocoups due to the\nlack of term extensions, I cross-referenced the Archigos dataset, which includes\ndetailed trajectories of leaders' entries and exits from power, to verify the\nqualifications for autocoups.\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\nIn total, I coded 110 observations, with\n95 overlapping with the candidate data\nfrom Incumbent Takeover. The remaining\n15 events were newly\ncoded by the author through verification with other sources such as Archigos, and\nnews reports.The main deviation from the Incumbent Takeover dataset arises from\nexcluding power expansions that do not involve attempts to extend tenure.\n\nThe main variables included in the autocoup dataset are:\n\n-   **Country Identification:**\n\n    -   `ccode` and `country`: These variables come from the Correlates of War\n        project [@stinnett2002] and identify the countries included in the\n        dataset, which are widely used in political science datasets, ensuring\n        consistency and compatibility across different studies and datasets.\n\n-   **Leader Information:**\n\n    -   `leader_name`: This variable follows the Archigos dataset's coding and\n        records the name of the de facto leader who wielded power in the country.\n\n-   **Timeline Variables:**\n\n    -   `entry_date`: Captures the date the leader assumed power.\n\n    -   `exit_date`: Records the date the leader left office.\n\n    -   `autocoup_date`: Indicates the date the autocoup is considered to have\n        occurred. Since extensions often happen incrementally, this date reflects\n        a significant event marking the extension, such as a legislative vote or\n        successful referendum.\n\n    -   `extending_date`: Represents the start date of the leader's additional\n        term acquired through the autocoup.\n\n    The `entry_date` and `exit_date` come from the Archigos and PLAD datasets,\n    while the other two dates are coded by the dataset creator.\n\n-   **Power Transition Methods:**\n\n    -   `entry_method` and `exit_method`: These categorical variables record how\n        the leader entered and exited power (e.g., election, coup d'état, death).\n\n    -   `entry_regular` and `exit_regular`: These dummy variables indicate\n        whether the entry and exit methods were regular (e.g., election) or\n        irregular (e.g., coup).\n\n-   **Autocoup Details:**\n\n    -   `autocoup_method`: This key variable captures the various methods leaders\n        use to extend their stay in power (see @sec-classify for details).\n\n    -   `autocoup_outcome`: This variable indicates the outcome of the autocoup\n        attempt: \"fail and lose power\", \"fail but complete original tenure\", or\n        \"successful\". For successful coups, the additional term length can be\n        calculated from the difference between `exit_date` and `extending_date`.\n\n-   **Data Source:**\n\n    -   `source`: This variable identifies the dataset source used for coding,\n        primarily differentiating among \"Incumbent Takeovers\" or other sources.\n\n-   **Additional Notes:**\n\n    -   `notes`: This variable provides context for exceptional cases. For\n        instance, if a leader undertook multiple autocoup attempts, details are\n        recorded here.\n\nThe dataset encompasses a total of 14 variables along with the `notes` field.\n\n#### Data descriptions\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\nAccording to our primary coding, we have identified 110 autocoup\ncases from 1945 to 2022, involving 73 countries. As shown in\n@tbl-autocoup_method, the most common autocoup method is enabling re-election,\naccounting for 46 events. This is followed\nby removing term limits altogether, with 14\ncases, and then delaying elections and declaring the leader for life, each with\n9 cases.\n\nExamining the success rates of autocoups, the total success rate is 79%, which is\nsignificantly higher than the roughly 50% success rate of classical coups. This\nsuggests that incumbents are in an advantageous position to expand or extend\ntheir powers as executive leaders. They can do so openly and gradually, whereas\ncoup plotters must operate in secrecy and face numerous challenges such as\npromissory issues and the risk of betrayal or exposure.\n\nHowever, the success rates vary significantly across different methods. Removing\nterm limits, delaying elections, declaring the leader for life, and cancelling\nelections are all 100% successful. In contrast, there are only 4 cases of\nrefusing election results, with just one succeeding. Although this sample is\nsmall, it suggests that in regimes where general elections are held and\nincumbents lose, the system is relatively more democratic. In such cases,\nincumbents must run for office without the ability to rig elections, making it\nless likely for them to overturn election results.\n\n\n\n\n\n::: {#tbl-autocoup_method .cell tbl-cap='Autocoup methods and success rates (1945-2021)'}\n::: {.cell-output-display}\n\\begingroup\n\\setlength\\LTleft{0\\linewidth}\n\\setlength\\LTright{0\\linewidth}\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\begin{longtable}{@{\\extracolsep{\\fill}}>{\\raggedright\\arraybackslash}p{\\dimexpr 135.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 105.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 105.00pt -2\\tabcolsep-1.5\\arrayrulewidth}>{\\raggedleft\\arraybackslash}p{\\dimexpr 75.00pt -2\\tabcolsep-1.5\\arrayrulewidth}}\n\\toprule\nAutocoup Method & Autocoup Attempted & Autocoup Succeeded & Success Rate \\\\ \n\\midrule\\addlinespace[2.5pt]\nEnabling re-election & 46 & 33 & 71.74\\% \\\\ \nRemoving term limits & 14 & 14 & 100.00\\% \\\\ \nDelaying elections & 9 & 9 & 100.00\\% \\\\ \nLeader for life & 9 & 9 & 100.00\\% \\\\ \nChanging term length & 7 & 5 & 71.43\\% \\\\ \nFigurehead & 6 & 5 & 83.33\\% \\\\ \nOne-time arrangement & 5 & 4 & 80.00\\% \\\\ \nRefusing election results & 4 & 1 & 25.00\\% \\\\ \nReassigning power role & 4 & 2 & 50.00\\% \\\\ \nRigging elections & 3 & 2 & 66.67\\% \\\\ \nCancelling elections & 3 & 3 & 100.00\\% \\\\ \nTotal & 110 & 87 & 79.09\\% \\\\ \n\\bottomrule\n\\end{longtable}\n\\endgroup\n\n:::\n:::\n\n\n\n\n\n### Determinants of Autocoup Attempts: Case Studies\n\n#### High Frequency and Success Rate of Autocoups in Post-Communist Countries\n\nFrom the dataset, we observe that in post-communist countries, both the frequency\nand success rate of autocoups are notably high. Post-communist countries refer to\nthose that were communist regimes before the collapse of the Soviet Union, while\nmost of them developed into 'hybrid regimes' [@nurumov2019] and only a few remain\ncommunist regimes after the collapse. In these countries, there are 12 documented\ncases of autocoups aimed at prolonging incumbency, with only 2 of these attempts\nfailing. Examining the cases in post-communist countries, several characteristics\nstand out:\n\n-   **Inherited Authoritarian Systems**: Although most of these countries\n    transitioned from communist regimes to non-communist governments (with the\n    exception of China), they inherited the authoritarian systems of their\n    communist past.\n\n-   **Continuity of Former Elites**: The transitions did not result in the\n    removal or overthrow of the previous ruling groups. Instead, the former\n    communist elites remained in power.\n\n-   **Subverted Democratic Processes**: Despite the introduction of general\n    elections and term limits in most of these countries, the legacy of the\n    former communist regimes often led to term limits being ignored and elections\n    being rigged [@nurumov2019].\n\nFor example, Alexander Lukashenko was a member of the Supreme Soviet of the\nByelorussian Soviet Socialist Republic before the dissolution of the Soviet\nUnion. After the dissolution, he became head of the interim anti-corruption\ncommittee of the Supreme Council of Belarus. Elected as the first president of\nBelarus in 1994, he has held the office ever since. Initially, the 1994\nconstitution set a maximum of two successive presidential terms, but Lukashenko\nremoved this limit in 2004. Furthermore, international monitors have not regarded\nBelarusian elections as free and fair, except for his initial win. Despite\nsignificant protests against him, Lukashenko claimed to win with a high vote\nshare, often exceeding 80% in each election. This pattern is evident in all five\nCentral Asian countries of the former Soviet Union. Similarly, the\npost-dissolution leaders of these countries were high officials or heads of the\nformer Soviet republics who continued their leadership in the presidency.\n\nAnother long-ruling example is Nursultan Nazarbayev, who was the first president\nof Kazakhstan from 1991 until 2019. He had been the real leader as the First\nSecretary of the Communist Party of Kazakhstan before the dissolution of the\nSoviet Union. After independence, he was elected as the first president and held\nthe office until 2019, through various means like resetting the term limits due\nto the implementation of new constitutions. However, he did not officially\neliminate the term limits but made an exemption for the First President,\nNazarbayev [@nurumov2019]. Unlike Lukashenko, who is still the incumbent of\nBelarus, Nazarbayev passed the presidency to Kassym-Jomart Tokayev, a specially\ndesignated successor, in 2019. However, he retained significant influence as the\nChairman of the Security Council of Kazakhstan until 2022.\n\n\\clearpage\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n#### Autocoups for immediate re-election: Cases of Latin American countries\n\nLatin America has a long history of maintaining term limit conventions. Simón\nBolívar, the founding father of Bolivia, was a strong advocate for term limits,\nstating in 1819, “Nothing is as dangerous as allowing the same citizen to remain\nin power for a long time... That’s the origin of usurpation and tyranny”\n[@ginsburg2019]. Although Bolívar eventually changed his stance, arguing in his\n1826 Constitution Assembly speech that “a president for life with the right to\nchoose the successor is the most sublime inspiration for the republican order,”\nterm limits became a convention in Latin America. Approximately 81% of Latin\nAmerican constitutions between independence and 1985 imposed some form of term\nlimits on the presidency [@marsteintredet2019a].\n\nReviewing the cases in Latin American countries, we notice that:\n\n-   **Striving for Re-election:** Non-re-election or non-immediate re-election\n    has been common in Latin America, unlike other presidential countries where\n    two terms are more popular. Autocoup leaders in Latin America often attempt\n    to overstay a consecutive term.\n\n-   **Resisting long extensions:** Autocoups for one more term are often\n    successful, while attempts to overstay beyond this are frequently\n    unsuccessful.\n\nAccording to @marsteintredet2019a, non-consecutive re-election was mandated in\nabout 64.9% of all constitutions between independence and 1985, while 5.9% banned\nre-election entirely. However, adherence to these conventions has varied across\nthe region. Since Mexico introduced non-re-election institutions in 1911 at the\nstart of the Mexican Revolution, they have never been violated since then\n[@klesner2019]. Panama, along with Uruguay, has never changed the rules of\nre-election, and since Costa Rica prohibited immediate presidential re-election\nin 1859, the country has only experienced a brief period between 1897 and 1913 in\nwhich the incumbent president could be re-elected [@marsteintredet2019a]. In many\nother countries, however, constitutions have been frequently amended or violated.\nThe pursuit of re-election or consecutive re-election has been a significant\ntrigger for autocoups aimed at power extension in Latin American countries. There\nare 32 documented autocoup cases, with over 50% (17 cases) attempting to enable\nre-election.\n\nUnlike those who attempt to overstay in office indefinitely, many Latin American\nleaders exit after their second term expires. Examples include President Menem of\nArgentina (1988-1999), President Fernando Cardoso of Brazil (1995-2003),\nPresident Danilo Medina of the Dominican Republic (2012-2020), and President Juan\nOrlando Hernández of Honduras (2014-2022) [@ginsburg2019; @marsteintredet2019a;\n@landau2019; @baturo2019; @neto2019]. This does not mean none of them tried to\nextend even longer, but most did not manipulate the process by abusing their\npower and accepted their unsuccessful outcomes soon.\n\nFor instance, President Menem of Argentina successfully extended one term by\namending the constitution in 1994 to allow one executive re-election and was\nre-elected in 1995. However, when he attempted to reset his term, arguing that\nhis first term from 1988 to 1995 did not count since it was under previous\nconstitutions, his appeal was unanimously ruled out by the Supreme Court in March\n1999 [@llanos2019]. A similar scenario occurred with President Álvaro Uribe of\nColombia (2002-2010) [@baturo2019]. In contrast, Daniel Ortega, the incumbent\npresident of Nicaragua, successfully extended his presidency. In 2009, the\nSupreme Court of Justice of Nicaragua allowed his re-running in 2011. In 2014,\nthe National Assembly of Nicaragua approved constitutional amendments that\nabolished term limits for the presidency, allowing Ortega to run for an unlimited\nnumber of five-year terms, making him president since 2007 [@close2019].\n\n\n\n\n\n\n\n\n\n\n\n#### As common as classical coups: Cases of African countries\n\nClassical coups have been very common in Africa, accounting for about 45% of all\ncoups (219 out of 491) globally since 1950, involving 45 out of 54 African\ncountries [@powell2011]. Autocoups, although less common compared to coups, still\nhave a significant presence in Africa. Among 113 documented autocoup cases, 46%\n(52 cases) occurred in Africa, involving 36 countries. The success rate of coups\nin Africa is roughly 50%, while the success rate of autocoups is about 83%, which\nis higher than both the success rate of coups and the average global success rate\nof autocoups, approximately 78%.\n\nIdentifying a clear pattern of autocoups in Africa is challenging, similar to the\ncase with coups. Various factors have been proposed:\n\n-   **Natural Resources**: Countries rich in natural resources, particularly oil\n    or diamonds, may see leaders more likely to attempt and succeed in extending\n    their terms [@posner; @cheeseman2015; @cheeseman2019a].\n\n-   **Quality of Democracy**: The quality of democracy is a critical factor\n    influencing respect for term limits [@reyntjens2016].\n\n-   **International Influence**: International aid or donor influence can play a\n    significant role in discouraging attempts at power extension [@brown2001;\n    @tangri2010].\n\n-   **Organized Opposition and Party Unity**: The extent of organized opposition\n    and the president's ability to enforce unity within the ruling party are\n    crucial factors [@cheeseman2019].\n\nUsing the Africa Executive Term Limits (AETL) dataset, @cassani2020 highlights\nhuman rights abuses and the desire for impunity as main drivers for incumbents to\ncling to power. The more authoritarian a leader, the more likely they are to\nattempt to break term limits and overstay in office. Additionally, a leader's\nability to secure the loyalty of the armed forces through public investment\nincreases the chances of success in overstaying.\n\nDespite both coups and autocoups being prevalent, there has been a noticeable\nshift since the end of the Cold War in 1991. Coups have decreased, while\nautocoups have increased. This trend is partly due to the introduction of\nmulti-party elections in Africa in the 1990s, which also brought in term limits\nfor executives [@cassani2020; @cheeseman2019]. Before 1991, personal or military\nrule was more common, and term limits were less frequent. Post-1991, with more\nterm limits introduced, challenges to these limits have increased. However, this\ndoes not imply that violations are more common than adherence to term limits.\n\n### Empirical Analysis: A Simple Example of Utilizing the Autocoup Dataset\n\nWith the availability of the autocoup dataset, we can conduct quantitative\nanalyses beyond traditional case studies. This chapter provides a simple example\nof demonstrating how to utilize the dataset. To analyse the determinants of\nautocoup attempts, we employ a `probit` regression model. This model is\nappropriate for binary dependent variables, allowing us to estimate the\nprobability of an autocoup attempt given the independent variables.\n\n#### **Dependent Variable**\n\n-   **Autocoup Attempts**: This binary variable indicates whether an autocoup was\n    attempted during the tenure of an incumbent leader, based on the data\n    introduced in this study.\n\n-   **Autocoup Success:** This binary variable indicates whether an attempted\n    autocoup of the incumbent leader succeeded, based on the data introduced in\n    this study.\n\n#### **Independent Variables**\n\n-   **Economic Performance:** This variable is measured using two indicators:\n    economic level and economic growth trend.\n\n    **Economic Level:** Represented by GDP per capita. This measure provides an\n    indication of the overall economic health and standard of living in a\n    country.\n\n    **Economic Growth Trend:** Assessed using the current-trend (CT) ratio,\n    developed by @krishnarajan2019. The CT ratio compares a country's current GDP\n    per capita to the average GDP per capita over the previous five years. A\n    higher CT ratio signifies stronger economic performance.\n\n$$\n\\begin{aligned}\nCT_{i,t} = {GDP/cap_{i,t} \\over {1 \\over 5} {\\sum_{k=1}^5GDP/cap_{i,t-k}}}\n\\end{aligned}\n$$\n\nThe GDP per capita data, expressed in constant 2017 international dollars (PPP)\nand measured in units of \\$10,000, is sourced from the V-Dem dataset by\n@fariss2022. To account for the economic impact of the previous year, this data\nis lagged by one year.\n\n-   **Political Stability:** This variable captures overall regime stability by\n    including a violence index that encompasses all types of internal and\n    interstate wars and violence. The data for this index is sourced from the\n    Major Episodes of Political Violence dataset by Marshall. This index provides\n    a comprehensive measure of the level of violence and conflict within a\n    country, which can significantly impact power transitions.\n    [@marshall2005current].\n\n-   **Degree of Democracy:** The level of democracy is gauged using Polity 5\n    scores at the entry year for each respective country. These scores range from\n    -10 (fully autocratic) to +10 (fully democratic), capturing the extent of\n    democratic versus autocratic governance. This dataset is sourced from the\n    Centre for Systemic Peace (CSP)\\[\\^1\\] and provides an essential measure of\n    political regime type, which might influence the political stability and\n    power transitions.\n\n-   **Population Size:** To account for its potential impact on leaders' tenures,\n    the log of the population size is considered. This transformation helps in\n    managing the wide range of population sizes across different countries. The\n    data is sourced from the V-Dem dataset and is evaluated to understand its\n    influence on power transitions. Larger populations may present more\n    governance challenges and potential sources of opposition, thereby affecting\n    the stability and longevity of a leader's tenure.\n\n-   **Leader's Age:** The age of the leader is included as an additional variable\n    in the analysis, offering insights into potential correlations with\n    leadership strength. Older leaders may have different experiences, networks,\n    and health considerations that could influence their ability to maintain\n    power. This data is sourced from the leaders dataset by [@goemans2009].\n\nDifferent from analysing the determinants of coups, which theoretically could\nhappen in each year, we assume that autocoup happens only once during the tenure\nof the incumbent. Because once the incumbent succeeds an autocoup, there is no\nnecessary to stage another one. Of course, this is not the case in real time. A\nleader who successfully overstayed one term could try to overstay additional\nterm, or even strive for leadership for life. A leader who failed in the first\nattempt might make another try if they are not removed due the first failure. To\nsimplify the analysis, we overlook those possibilities.\n\nTherefore, in the `probit` model, the unit of analysis in autocoups is the whole\ntenure of the leader, not country-year. So, we need to settle a base-year for the\nvariables. For leaders who staged an autocoup, we take the year of their first\nattempts as the base-year, while for leaders who did not attempt to overstay, we\ntake the middle year of their tenure as the base-year.\n\nUnlike the analysis of coup determinants, which could theoretically occur in any\ngiven year, we assume that an autocoup happens only once during an incumbent\nleader's tenure. Once an incumbent succeeds in staging an autocoup, there is no\nneed for another attempt. However, this assumption does not always reflect\nreality. A leader who successfully extends their term might attempt further\nextensions, striving for lifelong leadership. Conversely, a leader who fails in\ntheir first attempt may try again if they are not removed from power after the\ninitial failure. For simplicity, we overlook these possibilities in our analysis.\n\nTherefore, in our `probit` model, the unit of analysis for autocoups is the\nentire tenure of a leader, rather than a country-year. We establish a base year\nfor the variables: for leaders who staged an autocoup, we use the year of their\nfirst attempt as the base year; for leaders who did not attempt to overstay, we\nuse the middle year of their tenure as the base year.\n\n#### Results and discussions\n\n\n\n\n\n\n\\begin{table}[!htbp] \\centering \n  \\caption{Determinants of autocoup attempts and success (1945-2018)} \n  \\label{results} \n\\begin{tabular}{@{\\extracolsep{50pt}}lcc} \n\\\\[-1.8ex]\\hline \n\\hline \\\\[-1.8ex] \n & Coup Attempts & Coup Outcome \\\\ \n\\\\[-1.8ex] & (1) & (2)\\\\ \n\\hline \\\\[-1.8ex] \n Constant & $-$1.576$^{**}$ & $-$0.790 \\\\ \n  & (0.621) & (1.958) \\\\ \n  & & \\\\ \n Regime: Dominant-party & 0.152 & 0.690$^{*}$ \\\\ \n  & (0.155) & (0.408) \\\\ \n  & & \\\\ \n \\hspace{1.6cm}Military & $-$0.158 & 0.621 \\\\ \n  & (0.203) & (0.542) \\\\ \n  & & \\\\ \n \\hspace{1.6cm}Personalist & 0.911$^{***}$ & 1.631$^{***}$ \\\\ \n  & (0.172) & (0.458) \\\\ \n  & & \\\\ \n  GDP per capita & $-$0.010 & 0.065 \\\\ \n  & (0.011) & (0.046) \\\\ \n  & & \\\\ \n Economic trend & 0.598 & 0.138 \\\\ \n  & (0.516) & (1.781) \\\\ \n  & & \\\\ \n Political 5 & 0.002 & 0.003 \\\\ \n  & (0.003) & (0.010) \\\\ \n  & & \\\\ \n Political violence & $-$0.050 & 0.134 \\\\ \n  & (0.037) & (0.133) \\\\ \n  & & \\\\ \n Age & $-$0.001 & 0.004 \\\\ \n  & (0.002) & (0.017) \\\\ \n  & & \\\\ \n Population(log) & $-$0.040 & 0.027 \\\\ \n  & (0.047) & (0.145) \\\\ \n  & & \\\\ \n\\hline \\\\[-1.8ex] \nObservations & 813 & 102 \\\\ \nLog Likelihood & $-$281.765 & $-$43.604 \\\\ \nAkaike Inf. Crit. & 583.531 & 107.207 \\\\ \n\\hline \n\\hline \\\\[-1.8ex] \n\\textit{Note:}  & \\multicolumn{2}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\\\ \n\\end{tabular} \n\\end{table} \n\n\n\n\n\nTable \\ref{results} summarizes the findings from the `probit` regression models\nbased on our analysis of the determinants of autocoup attempts and their success.\n\nModel 1, which examines autocoup attempts, reveals only one significant predictor\nbesides the constant term. Among the regime types, personalist regimes\nsignificantly increase the likelihood of autocoup attempts, all else being equal.\nThis suggests that leaders in personalist regimes are more prone to attempt to\nextend their power through autocoups compared to leaders in democratic regimes.\nLeaders in dominant-party and military regimes, however, show no significant\ndifference in the likelihood of attempting an autocoup compared to democratic\nleaders.\n\nThe model for autocoup success (Model 2) shows similar dynamics. Personalist\nregimes again have a strong positive and significant effect on the success of\nautocoups compared to democratic leaders. Dominant-party regimes also show a\npositive and marginally significant effect. However, a detailed examination\nreveals that about half of the successful autocoups in dominant-party regimes (9\nout of 20) exhibit a personalist style, such as \"party-personal-military\"\nregimes.\n\nThis is logical since personalist leaders are typically much more powerful than\nother types of leaders, making them more inclined and capable of overstaying in\npower.\n\nOther factors play an insignificant role in determining the attempts and outcomes\nof autocoups. This aligns with our conclusions on the determinants of classic\ncoups. Both coups and autocoups are significantly affected by power dynamics. As\npower transitions involve the struggle between seizing and maintaining power, the\nbalance of power status quo inevitably matters in both coups and autocoups. This\nalso explains the high success rate of autocoups. Compared to power challengers,\nincumbents are in an obviously advantageous position. Incumbent leaders can use\nstate power to their benefit, which is difficult to counteract. Even the abuse of\npower is often unchecked under a powerful leader's rule.\n\nThe threshold for removing or impeaching an incumbent leader is very high.\nWithout more than a majority or even greater support, it is very difficult to\nsucceed. Using illegal means such as a coup is even more challenging, as the\ncosts are high, the consequences are severe, and the likelihood of success is\nvery low.\n\n#### Conclusion\n\nThis study provides a comprehensive analysis of autocoups, specifically focusing\non political events where incumbent leaders illegitimately extend their tenure in\npower. By refining the concept and distinguishing it from broader definitions,\nsuch as 'self-coups', 'autogolpes', 'executive takeover', we introduce a novel\ndataset of autocoups (1945-2022). Through this more precise definition and\ndataset, we enhance the understanding and methods of analyzing the dynamics of\nirregular power transitions and the survival of political leaders.\n\nOur findings reveal that personalist regimes are far more likely to experience\nautocoup attempts and are more likely to succeed compared to democracies.\nDominant-party systems, often exhibiting personalist characteristics, also show\nan association with successful autocoups. While regime type significantly\ninfluences autocoups, other factors appear less impactful, mirroring classic\ncoups where the balance of power is a more essential determinant. The high\nsuccess rate of autocoups can be attributed to the inherent advantages incumbents\npossess, such as control over or abuse of state power and the difficulty of\nremoving or impeaching them through legal or illegal means.\n\nHowever, there are several limitations that future research could address.\nFirstly, the definition of an autocoup requires further commentary and discussion\nto gain wider acceptance. Accordingly, the dataset of autocoups requires further\ncase-by-case verification to improve accuracy, although debates on some ambiguous\ncases will likely persist. Secondly, due to the nature of autocoups, which are\nless frequent than classic coups (491 coups versus 110 autocoups during the same\nperiod), the quantitative analysis cannot be conducted as a country-year variable\nas in coups. This raises the issue of choosing a base year. For example, when\nanalyzing how GDP level or growth rate, the democratic index (such as Polity 5),\nor the age of the leader affect autocoup attempts, we need to decide which year's\nvalue should be used. In this study, we chose the middle year of a leader's\ntenure or the year they staged the autocoup, but determining the most appropriate\nyear requires further discussion.\n\nDespite these limitations, this research enhances our understanding of the\nmechanisms and motivations behind autocoups, contributing to the literature on\npolitical stability and democratic resilience. Future studies could build on this\nwork by employing the dataset to explore more power dynamics or examine the\nlong-term impacts of these events on political systems, particularly on\ndemocratic backsliding, democratic breakdown, and personalization of power.\n\n## Power Acquisition and Leadership Survival: A Comparative Analysis of Coup-Entry and Autocoup Leaders\n\n## Conclusion\n\n### Main Findings\n\nThis study delves into the dynamics and implications of irregular power\ntransitions, focusing on coups and autocoups. The findings illuminate the complex\ninterplay between incumbents and challengers fighting for power.\n\nFirstly, our analysis reveals that the expected success rate of a coup attempt\nsignificantly influences its likelihood. This success rate is heavily influenced\nby the balance of power between the incumbent regime and challengers, which is\nlargely determined by regime type. We find that military regimes, although with\nmore control over their own military forces, face a higher risk of coups compared\nto dominant-party regimes.\n\nSecondly, the study introduces a redefined concept: the autocoup. Defined as an\nincumbent leader's refusal to relinquish power as mandated, this research\ndistinguishes autocoups from broader terms like self-coups. Based on this\ndefinition, we present the first publicly available dataset of autocoup events\nfrom 1945 to 2022, encompassing 110 attempts and 87 successful autocoups. Case\nstudies and empirical analyses demonstrate the dataset's utility for quantitative\nresearch, providing a robust foundation for further analysis on autocoups.\n\nThirdly, employing survival analysis techniques, the study finds clear\ndifferences in leader longevity between those who come to power through coups and\nthose who extend their rule through autocoups. The results indicate that\ncoup-installed leaders face a significantly higher risk of removal compared to\nautocoup leaders who manipulate the system to extend their rule.\n\n### Policy Implications\n\nThe findings of this study offer valuable insights for policy-makers concerned\nwith promoting and protecting global democracy, which has faced increasing\nchallenges despite a general post-WWII trend towards democratization. Notably,\nthe \"third wave\" of democratization [@huntington1991democratization] witnessed a\nsurge in democratic transitions in the late 20th century. Since the Cold War's\nend, democratic nations have outnumbered non-democratic ones (@fig-democracy)\nwith the gap widening.\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Comparison of the number of democratic and non-democratic countries (1945-2020)](tem_files/figure-pdf/fig-democracy-1.pdf){#fig-democracy fig-align='center'}\n:::\n:::\n\n\n\n\n\nHowever, a \"democratic recession\" has emerged in recent years [@diamond2008].\nFreedom House reports an 18th consecutive year of global freedom decline in 2023\n[@freedomhouse2024freedom]. While few countries have completely regressed to\nautocracy, the average global democracy level has fallen back to pre-2000 levels.\nNotably, democratic backsliding often occurs within regimes, with democracies\nbecoming less liberal and autocracies becoming less competitive [@mechkova2017].\n\nThis research highlights irregular power transitions as a significant factor in\ndemocratic backsliding within regimes. These transitions, often coups or\nautocoups, violate democratic norms and disrupt the path towards stable\ndemocracies. Leaders who gain power through irregular means often resort to\nundemocratic tactics to maintain control, creating a vicious cycle of eroding\ndemocratic institutions.\n\nOur findings suggest that the shorter lifespans and potentially severe\nconsequences associated with coups may deter potential coup leaders. Conversely,\nautocoups appear to be a more tempting option for power-hungry leaders due to\ntheir higher success rates, seemingly moderate consequences, and extended leader\ntenure after the autocoup. This trend may explain the decline in classic coups\nsince the 1990s alongside the rise of autocoups [@bermeo2016].\n\n### Limitations and directions for future research\n\nThis study offers a novel framework for analysing irregular power transitions,\nbut some limitations require further exploration:\n\n-   **Data refinement:** Defining and classifying autocoups is a new approach.\n    Future research should validate this classification system through additional\n    studies and expert evaluations.\n\n-   **Data harmonization:** The current analysis faces challenges due to\n    mismatched units (country-year vs. leader) between coup and autocoup\n    datasets. Future efforts should explore data harmonization techniques for\n    more robust comparisons.\n\n-   **Democratic backsliding:** While this study establishes a connection between\n    irregular power transitions and democratic backsliding, further empirical\n    evidence is needed to solidify this link.\n\nSeveral avenues exist for future research:\n\n-   **Terminology and data collection:** Refining the \"autocoup\" concept and\n    achieving wider recognition will facilitate more accurate and comprehensive\n    data collection.\n\n-   **Dataset expansion:** Expanding the autocoup dataset with more cases and\n    integrating it with data on other irregular leadership transitions can\n    provide a more holistic view of political survival after these events.\n\n-   **Power dynamics and long-term impacts:** Utilizing this dataset, future\n    studies can delve deeper into power dynamics at play and explore the\n    long-term consequences of irregular transitions on political systems,\n    particularly regarding democratic backsliding, breakdown, and personalization\n    of power.\n\nIn conclusion, this study sheds light on the dynamics of irregular power\ntransitions, specifically focusing on coups and autocoups. By redefining\nautocoups, classifying the dataset, analysing determinants, and comparing leader\nlongevity, we establish a framework for understanding irregular transitions and\nleader survival. This work contributes to a deeper understanding of democratic\nresilience and political stability. Future research can build upon this\nfoundation by conducting further empirical analyses based on the novel autocoup\ndataset and continuing to refine the framework.\n\n\n\n\n\n\\newpage\n## References\n\n\n\n\n\n[^1]: According to the Archigos dataset, \"Removed by Military, without Foreign\n    Support\" and \"Removed by Other Government Actors, without Foreign Support\" in\n    the variable `exitcode` are classified as coups.\n\n[^2]: According to the Archigos dataset, \"Removed by Military, without Foreign\n    Support\" and \"Removed by Other Government Actors, without Foreign Support\" in\n    the variable `exitcode` are classified as coups.\n\n[^3]: The definitions and concepts of power expansion and power extension can be\n    vague. In this study, we define power expansion as an incumbent acquiring\n    additional authority from other state apparatuses, whereas power extension\n    refers to an incumbent prolonging their tenure beyond the designated term in\n    office.\n\n[^4]: According to the Archigos dataset, \"Removed by Military, without Foreign\n    Support\" and \"Removed by Other Government Actors, without Foreign Support\" in\n    the variable `exitcode` are classified as coups.\n\n[^5]: The definitions and concepts of power expansion and power extension can be\n    vague. In this study, we define power expansion as an incumbent acquiring\n    additional authority from other state apparatuses, whereas power extension\n    refers to an incumbent prolonging their tenure beyond the designated term in\n    office.\n",
    "supporting": [
      "tem_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{caption}\n\\usepackage{longtable}\n\\usepackage{colortbl}\n\\usepackage{array}\n\\usepackage{anyfontsize}\n\\usepackage{multirow}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}