---
format: pdf
---

```{r}
library(tidyverse)
library(stargazer)
library(sampleSelection)
library(vdemdata)
library(democracyData)
```

```{r}
#| results: 'asis'

mydata <- reg_data |> 
  filter(regime_type != "other") |>
  mutate(regime = relevel(factor(regime_type), "dominant-party")) |> 
  drop_na() 

model_selection <- mydata |> 
  glm(coup > 0 ~ regime + ct + violence + gdppc, 
      data = _,
      family = binomial(link = probit)) 
summary(model_selection)
```

```{r}
probit_lp <- predict(model_selection)
mills0 <- dnorm(probit_lp) / pnorm(probit_lp)
summary(mills0)
imr <- mills0[mydata$coup > 0]
summary(imr)
```

We can see the regression model in Table @tblcars.

```{r}
qplot(imr, geom = 'histogram', bins = 30)
```

```{r}
mydata |> 
  filter(coup > 0) |>
  glm(coup > 1 ~ regime + ct + violence + imr, 
      data = _,
      family = binomial(link = probit)) |>
  summary()
```

```{r}
data()
```

```{r}
0.754*1.6
exp(1.2064)
```

```{r}
0.774/(1-0.774)

pnorm(0.1 + 0.774 + 0.15)
pnorm(0.1 + 0.15)
```

```{r}
0.85/0.59
```

```{r}
0.774/0.5
```

```{r}
(0.32)
```

```{r}
pnorm(0.53)/0.5
```

```{r}
exp(2.2)
exp(0.862)
```

```{r}
pnorm(0.7) - pnorm(0.5)
```

```{r}
pnorm(0.2)
```

```{r}
library(mfx)
library(foreign)
mydata <- read.dta("https://dss.princeton.edu/training/Panel101.dta")
probitmfx(y_bin ~ x1 + x2 + x3, data=mydata)
```

```{r}
reg_data |> 
  filter(regime_type != "other") |>
  mutate(regime = relevel(factor(regime_type), "dominant-party")) |>
  glm(coup > 0 ~ regime + ct + violence + gdppc, 
    data = _,
    family = binomial(link = probit)) |> 
  summary()
```

```{r}
reg_data |> 
  filter(regime_type != "other") |>
  mutate(regime = relevel(factor(regime_type), "dominant-party")) |>
  probitmfx(coup > 0 ~ regime + ct + violence + gdppc, 
    data = _)
```

```{r}
reg_data |> 
  filter(regime_type != "other") |>
  mutate(regime = relevel(factor(regime_type), "dominant-party")) |>
  logitmfx(model_2step, data = _)
```

```{r}
reg_data |> 
  filter(regime_type != "other") |>
  mutate(regime = relevel(factor(regime_type), "dominant-party")) |>
  logitor(model_2step, data = _)
```

```{r}
reg_data |> 
  filter(regime_type != "other") |>
  mutate(regime = relevel(factor(regime_type), "dominant-party")) |>
  logitor(coup > 0 ~ regime + ct + violence + gdppc, data = _)
```

```{r}
reg_data |> 
  filter(regime_type != "other") |>
  mutate(regime = relevel(factor(regime_type), "dominant-party")) |>
  glm(coup > 0 ~ regime + ct + violence + gdppc, 
      data = _,
       family=binomial(link = logit)) |> 
  summary()
```

```{r}
reg_data |> 
  filter(regime_type != "other") |>
  mutate(regime = relevel(factor(regime_type), "dominant-party")) |>
  selection(coup > 0 ~ regime + ct + violence + gdppc,
            coup > 1 ~ regime + ct + violence, data = _
            ) |> 
  summary()
```

```{r}
pnorm(0.754)/(1-pnorm(0.754))
pnorm(0)/(1-pnorm(0))
pnorm(0.755)/pnorm(0)
```

```{r}
leader <- read.csv("ps/leader_list_8_21.csv")
Archigos <- read.csv("http://ksgleditsch.com/data/1March_Archigos_4.1.txt", sep="\t")
```

```{r}
IncumbentTakeovers <- read_excel("data/IncumbentTakeovers.xls")
```

```{r}
codebook |> 
  view()

gwf_all |> 
  view()

REIGN |> 
  view()
```

## Since last coup

```{r}
# Load necessary libraries
library(dplyr)
library(zoo)  # For na.locf

# Sample data (replace this with your actual data)
data <- tibble::tribble(
  ~ccode, ~year, ~coup,
  1, 2000, 0,
  1, 2001, 1,
  1, 2002, 0,
  1, 2003, 2,
  1, 2004, 0,
  1, 2005, 0,
  1, 2006, 1,
  2, 2000, 0,
  2, 2001, 0,
  2, 2002, 2,
  2, 2003, 0,
  2, 2004, 0,
  2, 2005, 1,
  2, 2006, 0,
  3, 2000, 0,
  3, 2001, 0,
  3, 2002, 0,
  3, 2003, 0,
  3, 2004, 0,
  3, 2005, 0,
  3, 2006, 0
)

# Calculate years since last coup or from the first year if no coups
data <- data %>%
  group_by(ccode) %>%
  arrange(year) %>%
  mutate(
    first_year = min(year),
    last_coup_year = if_else(coup == 1 | coup == 2, year, NA_integer_),
    last_coup_year = zoo::na.locf(last_coup_year, na.rm = FALSE),
    years_since_last_coup = if_else(is.na(last_coup_year), year - first_year, year - last_coup_year)
  ) %>%
  ungroup()

# View the result
print(data)

```

## Marginal effects

```{r}
library(tidyverse)
library(sampleSelection)
library(marginaleffects)
data(Mroz87)

m <- selection(lfp ~ educ + age + kids5 + kids618 + nwifeinc,
               wage >= 5 ~ educ + exper, data = Mroz87)

summary(m)
avg_slopes(m) |> 
  view()
```

```{r}
avg_slopes(m, type = "unconditional", part = "outcome")#coefficients of outcome

avg_slopes(m, type = "response", part = "selection")# marginal effects of selection

avg_slopes(m, type = "link", part = "selection")#coefficients of selection
```

```{r}
?predict.sampleSelection
```
