% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  12pt,
]{article}
\usepackage{xcolor}
\usepackage[top = 3cm,bottom = 3cm,left = 3cm,right = 2.7cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{2}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
  \setmainfont[]{Times New Roman}
  \setsansfont[]{Arial}
  \setmonofont[]{Courier New}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\usepackage{anyfontsize}
\usepackage{multirow}
\usepackage{sectsty}
\chapterfont{\centering}
\usepackage{lscape}
\newcommand{\blandscape}{\begin{landscape}}
\newcommand{\elandscape}{\end{landscape}}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Power Acquisition and Leadership Survival: A Comparative Analysis of Autocoup and Coup-installed Leaders},
  pdfauthor={Zhu Qi},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={blue},
  pdfcreator={LaTeX via pandoc}}


\title{Power Acquisition and Leadership Survival: A Comparative Analysis
of Autocoup and Coup-installed Leaders}
\author{Zhu Qi}
\date{2025-11-19}
\begin{document}
\maketitle


\setstretch{1.618}
\section*{Abstract}\label{abstract}
\addcontentsline{toc}{section}{Abstract}

This study examines political leader survival following irregular
transitions, comparing classic coups d'état with autocoup (incumbent
power extension). Employing a rigorous time-dependent Cox model on a new
dataset, I test if the mode of accession affects tenure length. The
analysis reveals that the initial hypothesis---that autocoup leaders
survive longer---is rejected. Once dynamic contextual variables are
controlled for, the method of irregular entry (coup vs. autocoup) does
not independently predict survival. Instead, longevity is overwhelmingly
determined by regime type and economic performance. Military and
personalist regimes exhibit high instability, while GDP growth provides
a strong protective effect. The research concludes that the
institutional and economic environment, not the specific method of power
seizure, is the principal determinant of political longevity following
irregular transitions.

\textbf{Keywords:} \emph{Coups, Autocoups, Leadership Survival, Cox
Model}

\newpage

\section{Introduction}\label{introduction}

Why some political leaders achieve lasting longevity while others are
quickly removed remains a central question in political science. While
general theories of political survival are rare, existing scholarship
has emphasized a broad spectrum of factors, ranging from objective
conditions---such as economic performance
(\citeproc{ref-palmer1999}{Palmer and Whitten 1999};
\citeproc{ref-williams2011}{Williams 2011}), natural resource wealth
(\citeproc{ref-smith2004}{Smith 2004}), and societal stability
(\citeproc{ref-arriola2009}{Arriola 2009})---to strategic behaviours,
including elite co-optation, repression, and institutional manipulation
(\citeproc{ref-gandhi2007}{Gandhi and Przeworski 2007};
\citeproc{ref-morrison2009}{Morrison 2009};
\citeproc{ref-davenport2021}{Davenport, RezaeeDaryakenari, and Wood
2021}).

Among the mechanisms of leadership turnover, coups d'état are the most
consequential and, consequently, the most studied form of irregular
transition (\citeproc{ref-goemans2009}{Goemans, Gleditsch, and Chiozza
2009}; \citeproc{ref-svolik2014}{Svolik 2014}). Coup-driven exits
account for nearly two-thirds of all irregular leader removals between
1945 and 2015 (\citeproc{ref-frantz2016}{Frantz and Stein 2016}).

Yet, despite extensive research on classic coups, a crucial and growing
subset of irregular transitions remains systematically underexamined:
the autocoup. Defined as an incumbent leader dismantling institutional
constraints to illegally entrench or extend their rule, this form of
self-engineered power extension has received far less attention than
traditional coups, even as its empirical relevance rises. Since 1945, at
least 64 successful autocoups have been identified, constituting a
substantial share of irregular leadership trajectories
(\citeproc{ref-zhu2024}{Zhu 2024}). Crucially, the success rate of
autocoups (77 percent) significantly exceeds that of traditional coups
(approximately 50 percent) (\citeproc{ref-powell2011}{Powell and Thyne
2011}), suggesting they represent a uniquely effective pathway to
prolonged power.

Comparative analysis of coup-installed and autocoup leaders is
particularly scarce. This omission is surprising because preliminary
evidence suggests fundamentally different survival dynamics. Despite the
shared challenge of irregular accession, leaders who achieved power via
autocoups exhibit significantly longer average post-event tenures---a
gap that can exceed five years---compared to those installed by coups. A
log-rank survival test confirms a statistically significant divergence,
with autocoup leaders consistently facing lower hazards of removal
(Figure~\ref{fig-logrank}).

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{_leader_survival_CPS_files/figure-pdf/fig-logrank-1.pdf}}

}

\caption{\label{fig-logrank}Survival curves of autocoup and
coup-installed leaders}

\end{figure}%

Building on these observations, this article argues that the mode of
irregular accession is a fundamental determinant of leadership survival.
Coup-installed leaders typically confront heightened and immediate
challenges from competing military factions and entrenched societal
forces. In stark contrast, autocoup leaders consolidate control from a
position of incumbency, allowing them to neutralize institutional veto
players and rivals \emph{before} the irregular transition is complete.

Using Cox proportional hazards and time-dependent Cox models, this study
tests this claim. While preliminary models suggested that the method of
accession impacted longevity, the more robust analysis reveals no
statistically significant difference in survival risk between autocoup
leaders and coup-installed leaders. This finding indicates that the
institutional and economic context, rather than the initial mode of
irregular entry, is the crucial factor shaping post-accession tenure.

This study makes two core contributions. First, methodologically, it
provides a rigorous systematic empirical investigation into the survival
of autocoup leaders, a crucial but understudied subset of irregular
transitions, by employing superior time-dependent survival models.
Second, substantively, by showing that the initial method of accession
is subsumed by contextual factors (regime type and economic dynamics),
this research refines our understanding of authoritarian durability. It
redirects scholarly focus from the specific event of the coup or
autocoup toward the structural conditions that truly enable or curtail
political longevity in the 21st century.

The remainder of this article proceeds as follows. Section 2 introduces
the definition and data coding of autocoups. Section 3 reviews the
theoretical foundations of political survival. Section 4 details the
research design and methodology. Section 5 presents and interprets the
empirical findings. Section 6 concludes by discussing how the method of
accession reshapes our understanding of authoritarian durability and the
future of irregular transitions.

\section{Autocoup: Definition and
Dataset}\label{autocoup-definition-and-dataset}

While studies of irregular leadership transitions traditionally focus on
coups d'état due to their frequency and impact, this article examines a
distinct form: an incumbent leader's refusal to relinquish power. This
phenomenon has received comparatively less scholarly attention, despite
its growing importance. Since the end of the Cold War, classic coups
have declined, while these ``incumbent retention'' or ``overstay''
strategies have become more frequent
(\citeproc{ref-ginsburg2010evasion}{Ginsburg, Melton, and Elkins 2010};
\citeproc{ref-baturo2014}{Baturo 2014};
\citeproc{ref-versteeg2020law}{Versteeg et al. 2020}).

\subsection{Terminology}\label{terminology}

The literature employs a diverse terminology for this phenomenon. The
most prevalent term is `self-coup' (or its Spanish equivalent,
autogolpe) (\citeproc{ref-przeworski2000}{Przeworski et al. 2000};
\citeproc{ref-cameron1998a}{Maxwell A. Cameron 1998a};
\citeproc{ref-bermeo2016}{Bermeo 2016}; \citeproc{ref-helmke2017}{Helmke
2017}; \citeproc{ref-marsteintredet2019}{Marsteintredet and Malamud
2019}). This term gained prominence after Peruvian President Alberto
Fujimori dissolved Congress and suspended the constitution in 1992
(\citeproc{ref-mauceri1995}{Mauceri 1995};
\citeproc{ref-cameron1998}{Maxwell A. Cameron 1998b}). However,
`self-coup' can be misleading; as Marsteintredet and Malamud
(\citeproc{ref-marsteintredet2019}{2019}) observes, the leader acts
against state institutions, not against themselves.

Other terms use modifiers to specify the mechanism, such as
``presidential,'' ``executive,'' ``constitutional,'' or ``judicial''
coups, while others describe the process, like ``slow-motion'' or
``soft'' coups (\citeproc{ref-marsteintredet2019}{Marsteintredet and
Malamud 2019}). Another prominent concept is `incumbent takeover',
defined as ``an event perpetuated by a ruling executive that
significantly reduces the formal and/or informal constraints on his/her
power'' (\citeproc{ref-svolik2014}{Svolik 2014};
\citeproc{ref-baturo2022}{Baturo and Tolstrup 2022, 374}).

These varying terms often create conceptual ambiguity, focusing on
procedural mechanisms or conflating legal and extra-legal actions. This
study adopts the term `\textbf{autocoup}' as the most analytically
coherent. It precisely identifies both the actor (the incumbent, auto-)
and the act (a coup), clearly conveys the illegitimate nature of the
behaviour, and establishes a theoretical link to conventional coups. It
thus provides a robust term for the unified analytical framework this
study seeks to establish.

\subsection{Definition}\label{definition}

Existing definitions of irregular power retention, particularly the
encompassing term `self-coup', often fail to adequately distinguish
between two fundamentally different concepts: \emph{power expansion} and
\emph{tenure extension}. Power expansion refers to an incumbent's
acquisition of greater authority or control over state apparatuses
during their mandated term. In contrast, Tenure extension specifically
denotes a leader's illegitimate act of prolonging their time in office
beyond the originally mandated constitutional limit.

Most previous research on autocoups does not sufficiently distinguish
between two related but fundamentally distinct concepts: power expansion
and tenure extension. However, this study contends that a precise
definition of the autocoup must prioritize tenure extension as its
defining characteristic. This focus offers greater conceptual clarity
and is more easily operationalised. While power expansion frequently
serves as a prerequisite for or accompaniment to tenure extension, it is
the extension itself, not the expansion of authority, that constitutes
the autocoup event.

I therefore define an autocoup as \textbf{\emph{the extension of an
incumbent leader's tenure in office beyond the originally mandated
limit, achieved through extra-constitutional means}}.

This definition places the violation or evasion of mandated term limits
at the centre of the concept, providing a more precise and consistent
framework for analysis.

\subsection{Data coding}\label{data-coding}

The autocoup dataset is constructed by integrating and refining several
established political science datasets to ensure reliability and
comprehensiveness (see Table~\ref{tbl-source}).

I use the Archigos dataset (\citeproc{ref-goemans2009}{Goemans,
Gleditsch, and Chiozza 2009}) and the Political Leaders' Affiliation
Database (PLAD) (\citeproc{ref-bomprezzi2024wedded}{Bomprezzi et al.
2024}) to identify de facto national leaders and their precise time in
office from 1945 to 2023. These sources are essential for distinguishing
de facto rulers from nominal heads of state.

The Incumbent Takeover dataset (\citeproc{ref-baturo2022}{Baturo and
Tolstrup 2022}), which synthesizes eleven sources, serves as my primary
inventory of potential events. This dataset catalogs a broad range of
cases where executives curtailed institutional constraints on their
authority. However, because that dataset includes both power expansion
and tenure extension cases, I cross-referenced its entries with Archigos
and PLAD to isolate only those events that meet our specific definition
of an autocoup (i.e., those involving tenure extension).

\begin{table}

\caption{\label{tbl-source}Main Data Sources for Coding the Autocoup
Dataset}

\centering{

\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}llrr}
\toprule
Dataset & Authors & Coverage & Obervations \\ 
\midrule\addlinespace[2.5pt]
Archigos & Goemans et al (2009) & 1875-2015 & 3409 \\ 
PLAD & Bomprezzi et al. (2024) & 1989-2023 & 1334 \\ 
Incumbent Takeover & Baturo and Tolstrup (2022) & 1913-2019 & 279 \\ 
\bottomrule
\end{tabular*}

}

\end{table}%

In total, I identified and coded 83 autocoup events: 50 were adapted
from cases within the Incumbent Takeover dataset and 33 were newly
identified by the author through cross-verification of Archigos, PLAD,
and contemporary news sources.

While the dataset builds on the valuable Incumbent Takeover project, it
is not a replication. The principal point of departure is conceptual: of
the 279 cases catalogued in the Incumbent Takeover dataset, I excluded
229 because they entailed power consolidation without an accompanying
attempt to extend the leader's tenure. Such events fall outside our
operational definition of an autocoup.

\section{Theoretical Framework: Survival Dynamics of Autocoup and
Coup-Installed
Leaders}\label{theoretical-framework-survival-dynamics-of-autocoup-and-coup-installed-leaders}

While the literature on leadership survival is extensive, studies of
irregular transitions often either focus heavily on coup-installed
leaders or aggregate various types of non-constitutional rulers. This
article addresses a critical gap by disaggregating these categories,
conducting a focused comparison between two distinct types of irregular
leaders: those installed by a coup and those who execute an autocoup.
Based on preliminary evidence from Figure~\ref{fig-logrank}, I argue
that despite both paths representing an irregular transition, the method
of entry or retention fundamentally alters a leader's subsequent
survival prospects. This section establishes the theoretical framework
for this comparison, beginning with key definitions, then analyzing the
divergent challenges these leaders face, and concluding with a testable
hypothesis.

\subsection{Key definitions and scope}\label{key-definitions-and-scope}

To ensure conceptual clarity, I first operationalise key terms.
Following Powell and Thyne (\citeproc{ref-powell2011}{2011}), a coup is
defined as ``illegal and overt attempts by the military or other elites
within the state apparatus to unseat the sitting executive.'' As defined
previously, an autocoup is ``the extension of an incumbent leader's
tenure in office beyond the originally mandated limit, achieved through
extra-constitutional means.''

From these definitions, I also identify two leader types. Coup-Installed
Leader is the individual who assumes power \emph{following} a successful
coup, regardless of their direct role in its execution. This broad
definition includes both the primary instigators and those selected to
lead the post-coup regime. Autocoup Leader is an incumbent leader who
successfully uses extra-constitutional means to extend their tenure,
effectively beginning a new, irregular term in office.

This study compares the post-autocoup tenure of autocoup leaders with
the post-coup tenure of coup-installed leaders. To ensure a meaningful
analysis of survival dynamics and filter out ephemeral episodes, I apply
a six-month tenure threshold to both groups. This comparative focus is
motivated by the distinct challenges of illegitimacy, uncertainty, and
instability that both leader types face, allowing for a nuanced analysis
of how their different starting positions influence longevity.

\subsection{Challenges in power
consolidation}\label{challenges-in-power-consolidation}

Both autocoup and coup-installed leaders must consolidate power in the
face of significant challenges. However, the nature and intensity of
these challenges differ markedly across the three key domains of
illegitimacy, uncertainty, and instability. As Table~\ref{tbl-leaders}
outlines, these differences place coup-installed leaders at a
significant relative disadvantage.

\blandscape

\begin{table}

\caption{\label{tbl-leaders}Main features of autocoup and coup-installed
leaders}

\centering{

\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}>{\raggedright\arraybackslash}p{\dimexpr 112.50pt -2\tabcolsep-1.5\arrayrulewidth}>{\raggedright\arraybackslash}p{\dimexpr 225.00pt -2\tabcolsep-1.5\arrayrulewidth}>{\raggedright\arraybackslash}p{\dimexpr 225.00pt -2\tabcolsep-1.5\arrayrulewidth}}
\toprule
Feature & Autocoup Leader & Coup Entry Leader \\ 
\midrule\addlinespace[2.5pt]
Illegitimacy & Normally attained through
lawful procedures, but
lacking consensus
legitimacy & Blatantly illegal \\ 
Uncertainty & Initially with some certainty, but decreases as the leader's age grows or health worsens & Significant uncertainty initially \\ 
Instability & Relatively stable & Unstable except when a strongman emerges or constitutional institutions are established \\ 
Balance of Power & Generally in a better position of power & Initially unclear and challenging to establish a balance \\ 
\bottomrule
\end{tabular*}

}

\end{table}%

\elandscape

\subsubsection{Illegitimacy}\label{illegitimacy}

While both leaders lack democratic legitimacy, its manifestation differs
significantly. Coup-Installed Leaders face immediate and unambiguous
illegitimacy. Their power originates from an overt, often violent,
rupture of the established order. This act generates immediate domestic
and international condemnation, undermining pre-existing norms and
institutions.

Autocoup Leaders, in contrast, typically employ a strategy of
manipulation. They leverage a procedural façade, bending or breaking
legal institutions to create a veneer of constitutionality. While this
``democratic'' cover may be thin, it obscures the irregular nature of
the transition, mitigates immediate backlash, and buys the leader
critical time to consolidate power.

\subsubsection{Uncertainty}\label{uncertainty}

The irregular path to power creates uncertainty regarding tenure and
succession for both types. Coup-Installed Leaders confront a threefold
uncertainty. First, the immediate aftermath involves a power struggle
within the new ruling coalition or junta. Second, their tenure is
inherently precarious, subject to internal rivalries, popular unrest, or
counter-coups. Third, the lack of established succession mechanisms
amplifies this ambiguity.

Autocoup Leaders present a more certain picture. The central question of
\emph{who} rules is already settled: the incumbent. By retaining power,
the autocoup leader signals an intention to rule indefinitely or on an
extended timeline, which can, in itself, create a perception of
stability and predictability, at least in the short term.

\subsubsection{Instability}\label{instability}

Precarious legitimacy and uncertainty breed instability, but the
stabilization tasks for each leader type are distinct. Coup-Installed
Leaders must rapidly reshape the state's power dynamics. This often
requires purges of the old elite and crackdowns on opponents, generating
significant instability and alienating potential allies. They must
simultaneously build a new support structure while managing domestic and
international pressures, limiting their options and undermining
long-term stability.

Autocoup Leaders benefit from institutional and personnel continuity.
Because they are already in power, they can implement changes more
gradually, minimizing disruption and mitigating backlash. They face
opposition, but they are less likely to confront an immediate,
existential threat, affording them more time and leverage to solidify
their new grip on power.

\subsection{Hypothesis Development}\label{hypothesis-development}

Preliminary empirical evidence supports this theoretical distinction.
Analysis of survival data, as depicted in Figure~\ref{fig-logrank},
illustrates that the average survival period following an autocoup is
approximately five years longer than that of a leader installed by a
conventional coup.

This survival gap can be explained by the self-perpetuating cycles
created by their differing consolidation challenges. Coup-installed
leaders begin from a position of profound weakness. Their overt
illegitimacy and the instability from the coup itself make it difficult
to attract reliable support. This environment of persistent uncertainty
is compounded by historical precedent; as Powell and Thyne
(\citeproc{ref-powell2011}{2011}) notes, coups often occur in cycles,
with over a third of all attempts since 1950 occurring in the ten most
coup-prone countries. This history reinforces the leader's precarity,
inviting further challenges and shortening their expected tenure.

Autocoup leaders, conversely, leverage their initial advantages. The
veneer of legality and the continuity of state institutions provide a
stronger foundation. They are better positioned to attract and maintain
support, consolidate power incrementally, and face fewer immediate
threats of overthrow. This initial stability contributes to longer
tenures, which in turn reinforces the perception of their durability.

Based on this theoretical framework and the divergent challenges
identified, this study proposes the following hypothesis:

\begin{quote}
\textbf{H1: Political leaders who successfully extend their tenure
through autocoups will have a longer post-event tenure than leaders who
are installed by a coup d'état.}
\end{quote}

Testing this hypothesis will quantify the impact of the method of
irregular power acquisition on leadership longevity, offering a more
nuanced understanding of political survival.

\section{Research design}\label{research-design}

To test the central hypothesis that autocoup leaders exhibit longer
survival in office than coup-installed leaders, I utilize survival
analysis---a set of statistical methods designed to model the time until
an event occurs (in this case, the time until a leader is removed from
office). Specifically, I employ Cox proportional hazards and
time-dependent Cox models to estimate the effect of the primary
explanatory factor (leader type) on tenure length while controlling for
relevant covariates.

\subsection{Methodology: Survival
analysis}\label{methodology-survival-analysis}

I employ two variants of the Cox model to analyse leadership survival.
Cox Proportional Hazards (PH) model incorporates time-invariant
covariates (e.g., leader's age, country's coup history) measured at the
\emph{start} of the irregular tenure. It assumes the covariates have a
constant proportional effect on the hazard rate over time.

Time-dependent Cox model allows for the inclusion of covariates whose
values vary over time, such as annual economic performance or levels of
political violence. This approach offers a more dynamic and robust
analysis of survival.

The Cox model is preferred over the Kaplan-Meier estimator due to its
capacity to account for multiple explanatory variables simultaneously.
The model estimates the hazard ratio, which reflects the relative risk
of a tenure-ending event (ouster) at any given time. A higher hazard
ratio corresponds to a lower probability of survival, thus capturing the
critical dynamics of leadership vulnerability.

\subsection{Data and Variables}\label{data-and-variables}

The analysis relies on the following operationalised variables.

\subsubsection{Dependent Variables}\label{dependent-variables}

The dependent variable for survival analysis consists of two components:

\textbf{Survival Time:} This measures the duration of the leader's
tenure in days.

\begin{itemize}
\item
  For coup-installed leaders, this period begins on their day of
  accession.
\item
  For autocoup leaders, it begins on the date their original, legitimate
  term was set to expire, marking the start of their irregular tenure.
\end{itemize}

\textbf{End Point Status (Event):} This is a binary variable indicating
how the tenure concluded:

\begin{itemize}
\item
  \textbf{0 = Censored:} The leader's tenure ended through regular or
  `natural' means (e.g., term expiration, natural death, electoral loss,
  voluntary retirement).
\item
  \textbf{1 = Ousted (Event):} The leader was forcibly removed from
  office (e.g., via a subsequent coup, popular uprising, resignation
  under pressure, or assassination).
\end{itemize}

\subsubsection{Key independent variable}\label{key-independent-variable}

The primary independent variable of interest is \textbf{Leader Type}, a
categorical variable with three levels:

\begin{itemize}
\item
  Regular Leader (Reference Group): A leader who assumed power through
  regular, constitutional means.
\item
  Autocoup Leader: An incumbent who extended their tenure through
  extra-constitutional means.
\item
  Coup-Installed Leader: A leader who assumed power following a coup
  d'état.
\end{itemize}

\subsubsection{Control variables}\label{control-variables}

To isolate the effect of leader type, the models control for key
covariates as influencing leadership stability.

\textbf{Regime Type}: A categorical variable (democracy, hybrid,
autocracy) to account for broad institutional differences in leadership
stability and turnover norms.

\textbf{Polity V Score}: Used to control for the specific institutional
characteristics and degree of democratic or autocratic constraints on
the executive.

\textbf{Economic Performance}: Measured by macroeconomic indicators
(e.g., GDP growth) that influence a leader's resource base and popular
support.\begin{equation}\phantomsection\label{eq-eq6}{
    \begin{aligned}
    CT_{i,t} = {GDP/cap_{i,t} \over {1 \over 5} {\sum_{k=1}^5GDP/cap_{i,t-k}}}
    \end{aligned}
}\end{equation}

\textbf{Political Violence}: Accounts for the extent of civil conflict
or unrest that can directly threaten a leader's tenure.

\textbf{Population Size}: Included (often in log form) to control for
structural differences and governance challenges across states.

\subsubsection{Data Sources}\label{data-sources}

Data for all variables are compiled from several sources:

\textbf{The Archigos dataset} (\citeproc{ref-goemans2009}{Goemans,
Gleditsch, and Chiozza 2009}) and the Political Leaders' Affiliation
Database (PLAD) (\citeproc{ref-bomprezzi2024wedded}{Bomprezzi et al.
2024}) provide the core data on leader tenure and exit types.

\textbf{The Autocoup Dataset} (introduced in this study) is used to
identify autocoup leaders and the start date of their irregular tenure.

\textbf{Control variable data} is sourced from standard datasets (e.g.,
Polity V, World Bank, and datasets on political violence).

\section{Results and discussion}\label{results-and-discussion}

\subsection{Model results}\label{model-results}

The regression estimates from both the Cox Proportional Hazards (PH)
model and the time-dependent Cox model are presented in
Table~\ref{tbl-cox}. The two specifications yield divergent findings
regarding this study's central hypothesis.

\begin{table}

\caption{\label{tbl-cox}Cox Models for Survival Time of Different Types
of Leaders}

\centering{

\fontsize{9.8pt}{11.7pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lcccccccc}
\toprule
 & \multicolumn{4}{c}{\textbf{Cox PH Model}} & \multicolumn{4}{c}{\textbf{Time-dependent Cox Model}} \\ 
\cmidrule(lr){2-5} \cmidrule(lr){6-9}
\textbf{Characteristic} & \textbf{N} & \textbf{Event N} & \textbf{HR}\textsuperscript{\textit{1}} & \textbf{SE} & \textbf{N} & \textbf{Event N} & \textbf{HR}\textsuperscript{\textit{1}} & \textbf{SE} \\ 
\midrule\addlinespace[2.5pt]
{\bfseries Leader Type} &  &  &  &  &  &  &  &  \\ 
    Non-coup leaders & 1,506 & 195 & 1.00 & — & 8,039 & 196 & 1.00 & — \\ 
    Autocoup leaders & 58 & 20 & 1.21 & 0.247 & 507 & 20 & 1.22 & 0.244 \\ 
    Coup-installed leaders & 152 & 75 & 1.77*** & 0.155 & 998 & 75 & 1.26 & 0.170 \\ 
{\bfseries Regime Types} &  &  &  &  &  &  &  &  \\ 
    Dominant-party & 267 & 68 & 1.00 & — & 2,610 & 63 & 1.00 & — \\ 
    Military & 138 & 51 & 2.64*** & 0.194 & 656 & 60 & 3.17*** & 0.213 \\ 
    Personal & 137 & 61 & 1.70*** & 0.181 & 1,551 & 82 & 1.78*** & 0.175 \\ 
    Presidential & 346 & 42 & 1.42 & 0.229 & 1,819 & 39 & 1.31 & 0.269 \\ 
    Parliamentary & 711 & 35 & 1.29 & 0.245 & 2,555 & 31 & 1.28 & 0.292 \\ 
    Other & 117 & 33 & 2.27*** & 0.226 & 353 & 16 & 2.10** & 0.302 \\ 
{\bfseries GDP Growth Trend} & 1,716 & 290 & 0.62 & 0.984 & 9,544 & 291 & 0.13*** & 0.782 \\ 
{\bfseries GDP per capita} & 1,716 & 290 & 0.96*** & 0.008 & 9,544 & 291 & 0.96*** & 0.007 \\ 
{\bfseries Population: log} & 1,716 & 290 & 0.99 & 0.043 & 9,544 & 291 & 0.96 & 0.044 \\ 
{\bfseries Polity V score} & 1,716 & 290 & 0.98* & 0.013 & 9,544 & 291 & 0.99 & 0.015 \\ 
{\bfseries Political violence} & 1,716 & 290 & 0.98 & 0.030 & 9,544 & 291 & 1.06** & 0.027 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\textsuperscript{\textit{1}}*p\textless{}0.1; **p\textless{}0.05; ***p\textless{}0.01\\
Abbreviations: HR = Hazard Ratio, SE = Standard Error\\
\end{minipage}

}

\end{table}%

The standard Cox PH model, which uses only time-fixed covariates,
identifies a statistically significant difference in removal risk. In
this model, coup-installed leaders face a 77\% higher hazard of removal
compared to non-coup leaders (HR = 1.77, p \textless{} 0.01). The hazard
ratio for autocoup leaders (1.21) is not statistically significant.

However, the time-dependent Cox model, which is theoretically superior
as it accounts for evolving conditions (like economic performance and
political violence), contradicts this finding. In this more robust
model, no statistically significant difference in removal risk is found
between leader types. The hazard ratios for both autocoup (HR = 1.22)
and coup-installed (HR = 1.26) leaders are statistically
indistinguishable from the non-coup baseline.

Given the superior specification of the time-dependent model, we base
our principal interpretation on its results. This leads to a clear
rejection of the initial hypothesis (H1). Once key time-varying
contextual factors are controlled for, the manner of power acquisition
(coup vs.~autocoup) does not appear to have an independent,
statistically significant effect on leader survival.

Instead, the results indicate that survival is primarily determined by
institutional and contextual factors:

\begin{itemize}
\item
  Regime Type: This emerges as the most powerful predictor. Compared to
  the baseline of dominant-party regimes, leaders in military regimes
  face a 217\% higher risk of removal (HR = 3.17, p \textless{} 0.01).
  Leaders in personalist regimes (HR = 1.78, p \textless{} 0.01) and
  ``Other'' regimes (often transitional or provisional) (HR = 2.10, p
  \textless{} 0.05) are also significantly more vulnerable.
\item
  Economic Performance: Economic conditions are strongly associated with
  survival. Sustained GDP growth provides a powerful protective effect;
  a one-unit increase (e.g., 1\% growth above the 5-year average) is
  associated with an 87\% reduction in the hazard of removal (HR = 0.13,
  p \textless{} 0.01). Higher GDP per capita also has a modest but
  significant protective effect (HR = 0.96, p \textless{} 0.01).
\item
  Political Instability: Political violence is a destabilising force. A
  one-unit increase in the political violence index is associated with a
  6\% increase in the removal hazard (HR = 1.06, p \textless{} 0.05).
\end{itemize}

Other variables, including population size (log-transformed) and Polity
V scores, did not achieve statistical significance in the time-dependent
model.

\begin{figure}

\begin{minipage}{0.50\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{_leader_survival_CPS_files/figure-pdf/fig-coxHR-1.pdf}}

}

\subcaption{\label{fig-coxHR-1}Cox PH Model}

\end{minipage}%
%
\begin{minipage}{0.50\linewidth}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{_leader_survival_CPS_files/figure-pdf/fig-coxHR-2.pdf}}

}

\subcaption{\label{fig-coxHR-2}Time-dependent Cox Model}

\end{minipage}%

\caption{\label{fig-coxHR}Hazard Ratios and 95\% CIs for Leader Ousting}

\end{figure}%

Figure~\ref{fig-coxHR} displays the hazard ratios (HRs) with 95\%
confidence intervals for all covariates in the Cox Proportional Hazards
(PH) model (left panel) and the time-dependent Cox model (right panel).
Dots represent estimated HRs, and horizontal bars indicate the 95\%
confidence intervals. A value of 1 denotes no effect on the hazard of
removal. Covariates whose intervals cross the vertical reference line at
1 are not statistically significant at the 5\% level. Because it
captures time-varying conditions, the time-dependent Cox model forms the
primary basis for interpretation.

\subsection{Discussion}\label{discussion}

This result carries an important theoretical implication: after an
irregular seizure of power, the initial symbolic or procedural
differences between coups (external overthrow) and autocoups (internal
institutional manipulation) lose explanatory leverage. Both leader types
immediately confront similar structural vulnerabilities---contested
legitimacy, heightened elite uncertainty, and limited institutionalized
authority. Their subsequent survival depends less on how they entered
office and more on how effectively they navigate this shared environment
of instability.

The rejection of the initial hypothesis, however, does not diminish the
study's value; rather, it shifts the focus to the proximate political
and economic contexts that truly dictate longevity. The analysis
underscores that institutional and economic conditions---not accession
type---are the primary determinants of survival. Regime type stands out
as the strongest predictor: leaders in military, personalist, and
transitional regimes face substantially higher risks of removal. This
finding is consistent with theories linking high turnover to weak
institutions and poorly regulated elite competition. In these settings,
authority rests on fragile bargains and coercive capacity rather than
stable rules of succession, leaving leaders highly exposed to internal
rivals.

Two important contextual notes must be clarified regarding the findings.
First, these results are conditional on the exclusion of leaders who
survived for fewer than 180 days. This methodological choice is
analytically justified, as short-lived leaders (disproportionately found
among coup-installed regimes) often fail to achieve even minimal
consolidation and would artificially skew the hazard rates. Second, the
statistical finding that accession type is not a predictive factor does
not negate the observational reality that autocoup leaders still enjoy
longer average tenures than coup-installed leaders. The result simply
excludes the mode of accession as the causal predictive factor once
time-varying structural and performance variables are introduced into
the model.

\subsection{Methodological Validation}\label{methodological-validation}

As a final methodological check, the proportional hazards assumption was
validated using Schoenfeld residuals. The test results confirm that the
assumption is satisfied in both the standard Cox PH model (Global
\(p=0.12\)) and the time-dependent Cox model (Global \(p=0.23\)),
ensuring the reliability of the hazard ratio estimates.

\section{Conclusion}\label{conclusion}

This study provided a systematic analysis of the survival prospects of
political leaders who assumed office through irregular transitions
(coups and autocoups), employing robust survival analysis techniques,
including the time-dependent Cox model.

The principal finding of this study is that the mode of power
acquisition does not independently predict leadership duration once
dynamic contextual variables are considered. Although the simpler
standard Cox model suggested a higher risk of removal for coup-installed
leaders, this effect dissipated in the more rigorous time-dependent
model. This result indicates that leadership type itself is not a
significant determinant of political survival, challenging the initial
hypothesis.

Instead, leader survival is overwhelmingly determined by structural and
performance-based factors:

\begin{itemize}
\item
  Regime Type: This emerged as the most influential predictor. Leaders
  in military, personalist, and transitional (``other'') regimes face
  significantly higher hazards of removal than those in dominant-party
  systems. This highlights the profound institutional instability and
  elite factionalism associated with less consolidated political
  structures.
\item
  Economic Performance: Economic development is critically linked to
  stability. While higher GDP per capita is associated with greater
  leadership stability, GDP growth exerts an especially strong
  protective effect. Even modest increases in growth rates substantially
  reduce the risk of removal, reinforcing the link between
  performance-based legitimacy and political tenure.
\item
  Political Violence: Conversely, political violence consistently
  increases the likelihood of ousting, underscoring the destabilising
  impact of societal unrest and conflict on a leader's ability to
  maintain control.
\end{itemize}

Other structural variables, such as population size and Polity V scores,
did not attain statistical significance, suggesting that under
conditions of irregular accession, proximate and dynamic factors are
more consequential than long-term institutional attributes.

The robust findings regarding the factors that truly predict leadership
survival---or removal---carry clear policy implications for all leaders,
regardless of their path to power. The results show unequivocally that
personalist rule, military regimes, and poor economic management
significantly heighten the risk of violent overthrow. Therefore, for any
leader seeking long-term stability and reduced risk of removal, the
evidence strongly suggests two key priorities:

\begin{itemize}
\item
  Promote Institutionalized Governance: Leaders should strive to move
  away from highly personalist rule or military governance, as these
  regimes inherently raise the hazard of removal. Even under
  non-democratic conditions, fostering more rules-based, inclusive, and
  institutionalized governance systems can reduce the elite uncertainty
  and factionalism that fuel coups.
\item
  Prioritize Economic Performance: Maintaining high economic growth and
  improving GDP per capita is paramount. Leaders must prioritize
  policies that deliver tangible economic benefits, as sustained poor
  economic performance is one of the clearest signals that significantly
  raises the probability of them being violently ousted. The study
  suggests that focusing on these structural and performance metrics is
  far more effective for ensuring political longevity than attempting to
  manipulate the initial accession process.
\end{itemize}

In sum, this study concludes that regime characteristics and economic
dynamics, rather than the mode of accession, are the principal
determinants of political survival following irregular transitions to
power.

Methodologically, this work advances the field by demonstrating the
analytical necessity of time-dependent survival models in leadership
research. Substantively, it provides one of the first systematic
empirical investigations into the survival of autocoup leaders,
contributing valuable data to the growing literature on irregular
leadership transitions, while also pointing to the necessity of future
refinement and expansion of the newly constructed autocoup dataset.
These findings contribute to broader debates on authoritarian
resilience, executive instability, and the structural foundations of
political longevity.

\newpage

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-arriola2009}
Arriola, Leonardo R. 2009. {``Patronage and Political Stability in
Africa.''} \emph{Comparative Political Studies} 42 (10): 1339--62.
\url{https://doi.org/10.1177/0010414009332126}.

\bibitem[\citeproctext]{ref-baturo2014}
Baturo, Alexander. 2014. {``Democracy, Dictatorship, and Term Limits.''}
\url{https://doi.org/10.3998/mpub.4772634}.

\bibitem[\citeproctext]{ref-baturo2022}
Baturo, Alexander, and Jakob Tolstrup. 2022. {``Incumbent Takeovers.''}
\emph{Journal of Peace Research} 60 (2): 373--86.
\url{https://doi.org/10.1177/00223433221075183}.

\bibitem[\citeproctext]{ref-bermeo2016}
Bermeo, Nancy. 2016. {``On Democratic Backsliding.''} \emph{Journal of
Democracy} 27 (1): 5--19. \url{https://doi.org/10.1353/jod.2016.0012}.

\bibitem[\citeproctext]{ref-bomprezzi2024wedded}
Bomprezzi, Pietro, Axel Dreher, Andreas Fuchs, Teresa Hailer, Andreas
Kammerlander, Lennart Kaplan, Silvia Marchesi, Tania Masi, Charlotte
Robert, and Kerstin Unfried. 2024. {``Wedded to Prosperity? Informal
Influence and Regional Favoritism.''} Discussion Paper. CEPR.

\bibitem[\citeproctext]{ref-cameron1998a}
Cameron, Maxwell A. 1998a. {``Latin American Autogolpes : Dangerous
Undertows in the Third Wave of Democratisation.''} \emph{Third World
Quarterly} 19 (2): 219--39.
\url{https://doi.org/10.1080/01436599814433}.

\bibitem[\citeproctext]{ref-cameron1998}
Cameron, Maxwell A. 1998b. {``Self-Coups: Peru, Guatemala, and
Russia.''} \emph{Journal of Democracy} 9 (1): 125--39.
\url{https://doi.org/10.1353/jod.1998.0003}.

\bibitem[\citeproctext]{ref-davenport2021}
Davenport, Christian, Babak RezaeeDaryakenari, and Reed M Wood. 2021.
{``Tenure Through Tyranny? Repression, Dissent, and Leader Removal in
Africa and Latin America, 1990{\textendash}2006.''} \emph{Journal of
Global Security Studies} 7 (1).
\url{https://doi.org/10.1093/jogss/ogab023}.

\bibitem[\citeproctext]{ref-frantz2016}
Frantz, Erica, and Elizabeth A. Stein. 2016. {``Countering Coups:
Leadership Succession Rules in Dictatorships.''} \emph{Comparative
Political Studies} 50 (7): 935--62.
\url{https://doi.org/10.1177/0010414016655538}.

\bibitem[\citeproctext]{ref-gandhi2007}
Gandhi, Jennifer, and Adam Przeworski. 2007. {``Authoritarian
Institutions and the Survival of Autocrats.''} \emph{Comparative
Political Studies} 40 (11): 1279--1301.
\url{https://doi.org/10.1177/0010414007305817}.

\bibitem[\citeproctext]{ref-ginsburg2010evasion}
Ginsburg, Tom, James Melton, and Zachary Elkins. 2010. {``On the Evasion
of Executive Term Limits.''} \emph{Wm. \& Mary L. Rev.} 52: 1807.

\bibitem[\citeproctext]{ref-goemans2009}
Goemans, Henk E., Kristian Skrede Gleditsch, and Giacomo Chiozza. 2009.
{``Introducing Archigos: A Dataset of Political Leaders.''}
\emph{Journal of Peace Research} 46 (2): 269--83.
\url{https://doi.org/10.1177/0022343308100719}.

\bibitem[\citeproctext]{ref-helmke2017}
Helmke, Gretchen. 2017. {``Institutions on the Edge,''} January.
\url{https://doi.org/10.1017/9781139031738}.

\bibitem[\citeproctext]{ref-marsteintredet2019}
Marsteintredet, Leiv, and Andrés Malamud. 2019. {``Coup with Adjectives:
Conceptual Stretching or Innovation in Comparative Research?''}
\emph{Political Studies} 68 (4): 1014--35.
\url{https://doi.org/10.1177/0032321719888857}.

\bibitem[\citeproctext]{ref-mauceri1995}
Mauceri, Philip. 1995. {``State Reform, Coalitions, and The Neoliberal
{\emph{Autogolpe}} in Peru.''} \emph{Latin American Research Review} 30
(1): 7--37. \url{https://doi.org/10.1017/s0023879100017155}.

\bibitem[\citeproctext]{ref-morrison2009}
Morrison, Kevin M. 2009. {``Oil, Nontax Revenue, and the
Redistributional Foundations of Regime Stability.''} \emph{International
Organization} 63 (1): 107--38.
\url{https://doi.org/10.1017/s0020818309090043}.

\bibitem[\citeproctext]{ref-palmer1999}
Palmer, Harvey D., and Guy D. Whitten. 1999. {``The Electoral Impact of
Unexpected Inflation and Economic Growth.''} \emph{British Journal of
Political Science} 29 (4): 623--39.
\url{https://doi.org/10.1017/s0007123499000307}.

\bibitem[\citeproctext]{ref-powell2011}
Powell, and Thyne. 2011. {``Global Instances of Coups from 1950 to 2010:
A New Dataset.''} \emph{Journal of Peace Research} 48 (2): 249--59.
\url{https://doi.org/10.1177/0022343310397436}.

\bibitem[\citeproctext]{ref-przeworski2000}
Przeworski, Adam, Michael E. Alvarez, Jose Antonio Cheibub, and Fernando
Limongi. 2000. {``Democracy and Development,''} August.
\url{https://doi.org/10.1017/cbo9780511804946}.

\bibitem[\citeproctext]{ref-smith2004}
Smith, Benjamin. 2004. {``Oil Wealth and Regime Survival in the
Developing World, 1960{\textendash}1999.''} \emph{American Journal of
Political Science} 48 (2): 232--46.
\url{https://doi.org/10.1111/j.0092-5853.2004.00067.x}.

\bibitem[\citeproctext]{ref-svolik2014}
Svolik, Milan W. 2014. {``Which Democracies Will Last? Coups, Incumbent
Takeovers, and the Dynamic of Democratic Consolidation.''} \emph{British
Journal of Political Science} 45 (4): 715--38.
\url{https://doi.org/10.1017/s0007123413000550}.

\bibitem[\citeproctext]{ref-versteeg2020law}
Versteeg, Mila, Timothy Horley, Anne Meng, Mauricio Guim, and Marilyn
Guirguis. 2020. {``The Law and Politics of Presidential Term Limit
Evasion.''} \emph{Colum. L. Rev.} 120: 173.

\bibitem[\citeproctext]{ref-williams2011}
Williams, Laron K. 2011. {``Pick Your Poison: Economic Crises,
International Monetary Fund Loans and Leader Survival.''}
\emph{International Political Science Review} 33 (2): 131--49.
\url{https://doi.org/10.1177/0192512111399006}.

\bibitem[\citeproctext]{ref-zhu2024}
Zhu, Qi. 2024. {``Leadership Transitions and Survival: Coups, Autocoups,
and Power Dynamics.''} PhD thesis, University of Essex.

\end{CSLReferences}




\end{document}
