---
title: "Leadership Transitions and Survival: Coups, Autocoups, and Power Dynamics"
subtitle: "*Ph.D. Defense Presentation*"
author: "Zhu Qi"
date: last-modified
format: 
  revealjs:
    theme: [default, custom.scss]
    logo: /fig/essex.jpeg
    scrollable: true
    incremental: true
    auto-stretch: false
    slide-number: true
    chalkboard: true
    center: false
    number-sections: true
    number-depth: 2
    fade: true
    
    
editor: visual
---

## Contents {.unnumbered .center}

::: nonincremental
### [***1. Motivation and Main Questions***]{style="color:#3a86ff"}

### 2. Main Contributions

### 3. Main Arguments

### 4. Main Findings

### 5. Limitations and Future Research
:::

## *Motivations and Main Questions*

::::::: panel-tabset
### Key Focus

#### Examining coups and autocoups in the context of irregular leadership transitions

-   *Analyzing key factors driving their occurrences*

-   *Comparing leadership survival between coup-installed and autocoup leaders*

### Motivations

-   

    #### *Alarming decline of democracy and rise of autocratization*

::: notes
-   The Freedom House 2024 Report highlights this trend, revealing a disturbing
    18-year consecutive decline in global freedom.
:::

-   

    #### *Surge in autocoups since 2000*

::: notes
-   High-profile examples include Vladimir Putin in Russia and Xi Jinping in
    China, both of whom successfully extended their tenures through
    constitutional amendments. In the United States, former President Trump's
    refusal to accept the election results ignited debates over whether it
    constituted an attempted coup or autocoup.
:::

### Main Questions

-   

    #### *How do power dynamics among ruling groups affect classic coup attempts?*

-   

    #### *How can we analyze autocoups within a unified framework alongside coups in terms of irregular leadership transitions?*

::: notes
The extant literature has discussed coups and autocoups separately, but this
study aims to establish a unified framework to analyse both types of irregular
leadership transitions. By doing so, it seeks to provide a comprehensive
understanding of the dynamics of power acquisition and leadership survival.
:::

-   

    #### *How does the method of power acquisition impact leadership longevity?*

::: notes
Previous studies have discussed a lot about the political survival, but few have
compared the two significant and similar leaders: coup-installed and autocoup
leaders.
:::
:::::::

## Contents {.unnumbered .center}

::: nonincremental
### 1. Motivation and Main Questions

### [***2. Main Contributions***]{style="color:#3a86ff"}

### 3. Main Arguments

### 4. Main Findings

### 5. Limitations and Future Research
:::

## Main Contributions

:::::: panel-tabset
### ONE

#### *1. Emphasizing the key role of power dynamics and regime types in shaping coup attempts*

::: notes
This study examines the pivotal factor influencing the success or failure of coup
attempts: the power dynamics between incumbent leaders and those seeking to usurp
them.
:::

### TWO

#### *2. Refining the definition of autocoups and introducing a novel dataset*

::: notes
This study refines the definition of autocoups and develops a novel dataset
encompassing events from 1945 to 2023.
:::

### THREE

#### *3. Establishing a unified framework for analyzing coups and autocoups as irregular power transitions*

### FOUR

#### *4. Conducting a novel comparative analysis of leadership survival between coup-installed and autocoup leaders*

::: notes
Employing survival analysis on existing coup data and the newly compiled autocoup
dataset, this research demonstrates how different modes of power acquisition
significantly impact leadership survival.
:::
::::::

## Contents {.unnumbered .center}

::: nonincremental
### 1. Motivation and Main Questions

### 2. Main Contributions

### [***3. Main Arguments***]{style="color:#3a86ff"}

### 4. Main Findings

### 5. Limitations and Future Research
:::

## Main Arguments

:::: panel-tabset
### ONE

#### *1. Balance of power between incumbents and other elites in ruling groups significantly shapes potential outcomes of coups or autocoups, consequently determines their attempts*

::: notes
Previous studies on coups have analysed the determinants of coup attempts in a
great detail and proposed about 100 factors that could influence the likelihood
of a coup, without a consensus on the most important ones. This study pays
particular attention to the power dynamics among ruling groups, which is the
fundamental determinant of a coup attempt.
:::

### TWO

#### *2. Regime types pre-determine the balance of power among different factions.*

### THREE

#### *3. Method of power acquisition significantly impacts leadership survival*
::::

## Contents {.unnumbered .center}

::: nonincremental
### 1. Motivation and Main Questions

### 2. Main Contributions

### 3. Main Arguments

### [***4. Main Findings***]{style="color:#3a86ff"}

### 5. Limitations and Future Research
:::

## Main Findings

::: panel-tabset
### One

#### *1. Coup Attempts by Regime Type:*

-   Military regimes are 277.7% more likely to experience coups than
    dominant-party regimes

-   Attributed to differences in power dynamics among ruling groups

### Two

#### *2. Autocoup Analysis (1945-2023):*

-   Personalist regimes significantly more likely to experience and succeed in
    autocoup attempts compared to democracies

### Three

#### *3. Leadership Survival Comparison:*

-   Coup-installed leaders are 2.23 times more likely to be ousted than autocoup
    leaders
:::

## Contents {.unnumbered .center}

::: nonincremental
### 1. Motivation and Main Questions

### 2. Main Contributions

### 3. Main Arguments

### 4. Main Findings

### [***5. Limitations and Future Research***]{style="color:#3a86ff"}
:::

## Limitations and Future Research

::: panel-tabset
### Limitation

#### *Further refinement needed for autocoup definition and dataset*

### Future Research Directions

-   

    #### *More empirical analyses on autocoups based on the developed dataset*

-   

    #### *Exploration of long-term impacts of coups vs. autocoups on regime stability and economic development*
:::

##  {.center .unnumbered}

::: r-stack
[Thank you.]{style="color:#3a86ff; font-size: 3em; font-weight: bold;"}
:::

::::::::::::::
