---
title: Coups and Democracy
authors:
  - name: Reddy Lee
    affiliation: University of Essex
    roles: writing
    corresponding: true
date: "2024-03-30"
date-modified: last-modified
format:
  html:
    comments:
      hypothesis: true
  docx: default
  pdf: 
    link-citations: true
    linkcolor: blue
    fontsize: 12pt
    linestretch: 1.5
  revealjs: 
    output-file: second_paper1.html
  jats: default
  
other-links:
    - text: Download data
      href: mtcars.csv
      icon: download
      
code-link: true
code-overflow: wrap
code-fold: true
code-summary: "_Show the code_"
code-block-background: true
highlight-style: atom-one
code-line-numbers: true

bibliography: references.bib
abstract: |
  ***Among patients at high risk for post-ERCP pancreatitis, rectal indomethacin significantly reduced the incidence of the condition. (Funded by the National Institutes of Health; ClinicalTrials.gov number, NCT00820612. opens in new tab.)***
keywords: Coups, Democracy
execute:
  echo: true
---

## Section

This is a simple placeholder for the manuscript's main document [@knuth1984].

```{r}
1 + 1
```

```{r}
library(ggplot2)
```

Let's cite here [@debruin2020].

\newpage
## References
